rooch-network/rooch

crates/framework/mos-stdlib/sources/bcd.move, crates/framework/mos-stdlib/sources/table.move, crates/framework/src/natives/mod.rs, crates/framework/src/natives/mos_stdlib/bcd.rs, crates/framework/src/natives/mos_stdlib/mod.rs
Add `from_bytes` native function and `bcd` module for bcs bytes deserialization. Resolve #22 .
=> Add bcs deserialization 

.github/workflows/rust.yml, scripts/dev_setup.sh
The docs/contribtons branch have deleted after it merged to main branch, so the ci yaml file should reference to main branch.
=> [DevOps] Switch ci yaml file from docs/contributions to main branch

.github/workflows/rust.yml, Cargo.toml, crates/framework/Cargo.toml, crates/framework/mos-framework/Move.toml, crates/framework/mos-framework/sources/account.move, crates/framework/mos-stdlib/sources/any.move, crates/framework/mos-stdlib/sources/bcd.move, crates/framework/mos-stdlib/sources/copyable_any.move, crates/framework/src/addresses.rs, crates/framework/src/lib.rs, crates/framework/tests/cases/account/basic.exp, crates/framework/tests/cases/account/basic.move, crates/framework/tests/tests.rs, crates/integration-test-runner/Cargo.toml, crates/integration-test-runner/src/lib.rs, crates/integration-test-runner/tests/cases/call_std.exp, crates/integration-test-runner/tests/cases/call_std.move, crates/integration-test-runner/tests/tests.rs
1. The test-runner auto-generate the genesis module interface.
2. Add test to use `mos_stdlib` in integration tests
3. Fix `bcd::from_bytes` argument bug, use `vector<u8>` to replace `&vector<u8>`. Because we can not cast `ContainerRef` to rust Vec<u8> in MoveVM Value. 
4. Implement the `account::create_account` function, and add tests.
part of #16
=> [test_runner] Fix test runner and bcd argument bugs

Cargo.toml, crates/framework/Cargo.toml, crates/framework/mos-stdlib/Move.toml, crates/framework/mos-stdlib/sources/address.move, crates/framework/mos-stdlib/sources/hex.move, crates/framework/mos-stdlib/sources/object.move, crates/framework/mos-stdlib/sources/tx_context.move, crates/framework/src/natives/helpers.rs, crates/framework/src/natives/mod.rs, crates/framework/src/natives/mos_stdlib/mod.rs, crates/framework/src/natives/mos_stdlib/object.rs, crates/framework/src/natives/mos_stdlib/object_extension/mod.rs, crates/framework/src/natives/mos_stdlib/tx_context.rs, crates/framework/tests/cases/object/basic.exp, crates/framework/tests/cases/object/basic.move, crates/integration-test-runner/Cargo.toml, crates/integration-test-runner/src/lib.rs, crates/mos-types/Cargo.toml, crates/mos-types/src/lib.rs, crates/mos-types/src/object.rs, crates/mos-types/src/tx_context.rs, crates/moveos/Cargo.toml, crates/moveos/src/lib.rs, crates/moveos/src/moveos.rs, crates/moveos/src/vm/mod.rs, crates/moveos/src/vm/move_vm_ext.rs, crates/moveos/src/vm/tx_argument_resolver.rs, crates/statedb/src/lib.rs
Add hybrid Object and global storage example.
https://github.com/rooch-network/moveos/blob/object_move/crates/framework/tests/cases/object/basic.move
```move
module test::m {
use mos_std::tx_context::{Self, TxContext};
use mos_std::object::{Self, UID};
use std::debug;
struct S has store, key { id: UID }
struct Cup<phantom T: store> has store, key { id: UID }
public entry fun mint_s(ctx: &mut TxContext) {
let id = object::new(ctx);
debug::print(&id);
object::transfer(S { id }, tx_context::sender(ctx))
}
public entry fun move_s_to_global(sender: signer, s: S) {
move_to(&sender, s);
}
public entry fun mint_cup<T: store>(ctx: &mut TxContext) {
let id = object::new(ctx);
debug::print(&id);
object::transfer(Cup<T> { id }, tx_context::sender(ctx))
}
public entry fun …
```
=> [framework] A draft implemention of Object Move

moveos/moveos-stdlib/rooch-framework/Move.toml, moveos/moveos-stdlib/rooch-framework/sources/account.move, moveos/moveos-stdlib/rooch-framework/sources/block.move, moveos/moveos-stdlib/rooch-framework/sources/chain_id.move, moveos/moveos-stdlib/rooch-framework/sources/core_addresses.move, moveos/moveos-stdlib/rooch-framework/sources/genesis.move, moveos/moveos-stdlib/rooch-framework/sources/governance.move, moveos/moveos-stdlib/rooch-framework/sources/timestamp.move, moveos/moveos-stdlib/rooch-framework/sources/transaction_validator.move
This PR is part of https://github.com/rooch-network/rooch/issues/16
implementation including:
- Account controlled by the private key
- Account controlled by ResourceAccount
- A global wall clock that stores the current Unix time in milliseconds
- A Draft implementation of block, transaction_validator and genesis module etc.
Among them, there are a few points that need to be explained
- SignerCapability can only be stored in other structs, and cannot be droped.
- The resource account can only by controlled by SignerCapability, there has no private key can control the resource account
1, support rotate authentication key and manager rotate capability
2, complete transaction_validator and genesis module 
3, event register and emit
=> implement of basic account

crates/rooch-integration-test-runner/src/lib.rs, moveos/moveos-cli/src/lib.rs, moveos/moveos-statedb/src/lib.rs, moveos/moveos-stdlib/moveos-stdlib/sources/account_storage.move, moveos/moveos-stdlib/moveos-stdlib/sources/object.move, moveos/moveos-stdlib/moveos-stdlib/sources/raw_table.move, moveos/moveos-stdlib/moveos-stdlib/sources/table.move, moveos/moveos-stdlib/moveos-stdlib/sources/tx_context.move, moveos/moveos-stdlib/moveos-stdlib/sources/type_table.move, moveos/moveos-stdlib/tests/cases/account/basic.move, moveos/moveos-stdlib/tests/cases/object/basic.exp, moveos/moveos-stdlib/tests/cases/object/basic.move, moveos/moveos-types/src/object.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/tests/mod.rs
Part of #21 , Continue #48 
1. Use the NamedTableID to ensure the resource and module table id are determined. 
2. Fix some bugs, and enable the account/basic test.
=> [object] Fix named table id bug and enable more test

.github/workflows/rust.yml, moveos/moveos-cli/Cargo.toml, moveos/moveos-cli/src/commands/mod.rs, moveos/moveos-cli/src/commands/unit_test.rs, moveos/moveos-cli/src/lib.rs, moveos/moveos-stdlib/moveos-stdlib/sources/table.move
1. rooch move test support MoveOS runtime
2. github workflow add unit-test for moveos-stdlib and rooch-framework
resolve #55 and #61 .
=> rooch move test support MoveOS runtime

crates/rooch-types/src/address.rs, crates/rooch/src/commands/account/create.rs, moveos/moveos-stdlib/moveos-stdlib/sources/account_storage.move, moveos/moveos-stdlib/moveos-stdlib/sources/object_storage.move, moveos/moveos-stdlib/moveos-stdlib/sources/storage_context.move, moveos/moveos-stdlib/moveos-stdlib/sources/table.move, moveos/moveos-stdlib/moveos-stdlib/sources/tx_context.move, moveos/moveos-stdlib/rooch-framework/sources/account.move, moveos/moveos-stdlib/tests/cases/account/basic.exp, moveos/moveos-stdlib/tests/cases/account/basic.move
1. Keep RoochAddress's `serialize` & `deserialize` same as Move AccountAddress.
2. Fix ObjectStorage `contains` bug, and write a unit test for object_stroage.
resolve #107
=> [types&framework] Fix address serialize bug and object_storage bug

.github/workflows/check_build_test.yml, .github/workflows/cleanup.yml, .github/workflows/rust.yml, crates/rooch-client/Cargo.toml, crates/rooch-client/src/lib.rs, crates/rooch-integration-test-runner/src/lib.rs, crates/rooch-server/Cargo.toml, crates/rooch-server/src/actor/executor.rs, crates/rooch-server/src/actor/messages.rs, crates/rooch-server/src/proxy/mod.rs, crates/rooch-server/src/service/mod.rs, crates/rooch-types/src/transaction/ethereum.rs, crates/rooch-types/src/transaction/mod.rs, crates/rooch-types/src/transaction/rooch.rs, crates/rooch/src/commands/account/create.rs, crates/rooch/src/commands/move_cli/commands/publish.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, crates/testsuite/tests/integration.rs, moveos/moveos-types/src/transaction.rs, moveos/moveos/src/lib.rs, moveos/moveos/src/moveos.rs
1. Rename MoveTransaction to MoveAction.
2. Rename SimpleTransaction to MoveOSTransaction.
3. Use RoochTransaction to replace MoveOSTransaction in cli.
4. Define Transaction execute output: TransactionOutput.
5. Define Transaction validate mock function.
Part of #72
=> [types] use RoochTransaction in cli and refactor MoveOSTransaction

crates/rooch-client/src/lib.rs, crates/rooch-types/Cargo.toml, crates/rooch-types/src/cli.rs, crates/rooch/Cargo.toml, crates/rooch/src/commands/account/mod.rs, crates/rooch/src/commands/init.rs, crates/rooch/src/commands/move_cli/commands/new.rs, crates/rooch/src/commands/move_cli/commands/publish.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, crates/rooch/src/commands/move_cli/commands/run_view_function.rs, crates/rooch/src/commands/move_cli/mod.rs, crates/rooch/src/commands/object.rs, crates/rooch/src/commands/resource.rs, crates/rooch/src/commands/server.rs, crates/rooch/src/lib.rs, crates/rooch/src/main.rs
Unify output types of each commands.
To fix: 
The output of transaction is not pretty enough like this:
```
"{\n  \"code\": \"Ok\",\n  \"message\": null,\n  \"data\": {\n    \"state_root\": \"0xe30674dab1f57e29849b74d470c76d21ce41871e13974677f8e8f8ec87e1ba28\",\n    \"status\": \"Executed\"\n  }\n}"
```
Try to figure out why and fix it.
=> Refactor CLI output types

crates/rooch-server/src/actor/executor.rs, crates/rooch-types/src/transaction/ethereum.rs, crates/rooch-types/src/transaction/mod.rs, crates/rooch-types/src/transaction/rooch.rs, moveos/moveos-stdlib/rooch-framework/sources/account.move, moveos/moveos-stdlib/rooch-framework/sources/authenticator.move, moveos/moveos-types/src/transaction.rs, moveos/moveos/src/moveos.rs
resolve #72 
The transaction validates flow:
Multi-chain transaction -> AuthenticatableTransaction -> Validate transaction in MoveOS -> Get the AuthenticatorResult -> Construct MoveOSTransaciton -> Execute transaction
TODO:
1. Write a document to describe the validate move function ( part of #45 )
2. Refactor the validate function call, and make it an extension to MoveOS.
3. Implement the validate in Move.
=> [transaction-validate] Refactor transaction validate and transaction construct flow

Cargo.toml, crates/rooch/Cargo.toml, crates/rooch/src/commands/move_cli/commands/build.rs, crates/rooch/src/commands/move_cli/commands/new.rs, crates/rooch/src/extended_checks/build.rs, crates/rooch/src/extended_checks/metadata.rs, crates/rooch/src/extended_checks/mod.rs, crates/rooch/src/lib.rs, examples/private_generics/Move.toml, examples/private_generics/sources/private_generics.move
According to the content of this issue, https://github.com/move-language/move/issues/1043, the `#[private_generics(T1, T2)]` function attribute feature has been implemented in the Rooch project, which checks that `T1` and `T2` are defined as types in the current module.
resolve #64 
Here is an example code:
```move
module rooch_examples::Data {
struct Box<T: store> has key, store, drop {
value: T
}
struct Data1 has key, store, drop, copy {
v: u64,
}
struct Data2 has key, store, drop, copy {
v: u64,
}
#[private_generics(T3, T2)]
public fun create_box<T1: store, T2, T3>(value: T1): Box<T1> {
Box<T1> { value: value }
}
public fun box_value<T: copy+store>(box: &Box<T>): T {
*&box.value
}
public fun run() {
let data = Data1{ v: 123 };
let box_val = create_box<Data1, Data2, Box<u32>>(data);
let …
```
=> Private generics attribute and other extended checks

crates/rooch-key/Cargo.toml, crates/rooch-key/src/keystore.rs, crates/rooch-types/proptest-regressions/transaction/authenticator.txt, crates/rooch-types/src/account.rs, crates/rooch-types/src/address.rs, crates/rooch-types/src/coin_id.rs, crates/rooch-types/src/transaction/authenticator.rs
part of #160
To fix:
Encountering problem when impl Arbitrary trait for FileBasedKeystore struct.
```
pub struct FileBasedKeystore {
keys: BTreeMap<RoochAddress, RoochKeyPair>,
path: Option<PathBuf>,
}
```
When using ` btree_map(any::<RoochAddress>(), any::<RoochKeyPair>(), 1..100)` to generate a Strategy, it shows "the trait `Arbitrary` is not implemented for `RoochAddress`" and "the trait `Arbitrary` is not implemented for `RoochKeyPair`" but they are actually implemented.
=> Introduce fuzzing proptest for test struct serialize and deserialize

moveos/moveos-stdlib/moveos-stdlib/sources/type_info.move, moveos/moveos-stdlib/moveos-stdlib/sources/type_info.spec.move
In issue https://github.com/rooch-network/rooch/issues/181, the reported problem is: `error: no function named spec_is_struct found`.
Because in Rooch's code, the function `build_config.compile_package_no_exit(&package_path, &mut stderr())` is used to compile the Move Package, while the code of moveos_verifier uses `build_model(package_path.as_path(), additional_named_address, None)`. The difference between these two functions is that the first one does not compile code in `spec`, while the second one does, so the `spec` code will report that the function cannot be found.
So I added a new file named `type_info.spec.move`, and its contents are as follows:
```move
spec moveos_std::type_info {
spec native fun spec_is_struct<T>(): bool;
spec type_of<T>(): TypeInfo {
// Move Prover natively …
```
=> Add the type_info.spec.move file to solve the problem of the missing spec_is_struct function.

Cargo.toml, crates/rooch-server/Cargo.toml, crates/rooch-server/src/api/eth_api.rs, crates/rooch-server/src/jsonrpc_types/bytes.rs, crates/rooch-server/src/jsonrpc_types/eth/call_request.rs, crates/rooch-server/src/jsonrpc_types/eth/fee_history.rs, crates/rooch-server/src/jsonrpc_types/eth/mod.rs, crates/rooch-server/src/jsonrpc_types/eth/transaction_access_list.rs, crates/rooch-server/src/jsonrpc_types/mod.rs, crates/rooch-server/src/server/eth_server.rs
I have mocked some APIs required by MetaMask, now we can configure the rooch server RPC address to MetaMask and initiate transactions.
Ref https://github.com/rooch-network/rooch/issues/108
=> [rooch-server] mock eth compatible rpc

crates/rooch-client/src/lib.rs, crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-integration-test-runner/src/lib.rs, crates/rooch-server/Cargo.toml, crates/rooch-server/src/api/rooch_api.rs, crates/rooch-server/src/jsonrpc_types/move_types.rs, crates/rooch-server/src/server/rooch_server.rs, crates/rooch-server/src/service/mod.rs, crates/rooch/src/commands/mod.rs, crates/rooch/src/commands/state.rs, crates/rooch/src/lib.rs, crates/testsuite/features/cmd.feature, moveos/moveos-store/Cargo.toml, moveos/moveos-store/src/state_store/mod.rs, moveos/moveos-store/src/state_store/state_view.rs, moveos/moveos-types/src/access_path.rs, moveos/moveos-types/src/lib.rs, moveos/moveos-types/src/object.rs, moveos/moveos-types/src/state.rs, moveos/moveos/src/lib.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/tx_argument_resolver.rs
Implement AccessPath and State API
resolve #58 #12 
1. /object/$object_id1[,$object_id2]*
2. /resource/$account_address/$resource_type1[,$resource_type2]*
3. /module/$account_address/$module_name1[,$module_name2]*
4. /table/$table_handle/$key1[,$key2]*
```rust
/// Get the states by access_path
#[method(name = "rooch_getStates")]
async fn get_states(&self, access_path: AccessPath) -> RpcResult<Vec<Option<StateView>>>;
/// Get the annotated states by access_path
/// The annotated states include the decoded move value of the state
#[method(name = "rooch_getAnnotatedStates")]
async fn get_annotated_states(
&self,
access_path: AccessPath,
) -> RpcResult<Vec<Option<AnnotatedStateView>>>;
```
```
rooch state --access-path /resource/0x40ad744b6a3cd57d800e595b0aa9bf29ae0d2c1dadc78860a2c57df3cea5da9 …
```
=> [rpc] AccessPath and State API

examples/private_generics/sources/private_generics.move, moveos/moveos-stdlib/moveos-stdlib/sources/bcd.move, moveos/moveos-stdlib/moveos-stdlib/sources/type_table.move, moveos/moveos-verifier/src/metadata.rs
resolve https://github.com/rooch-network/rooch/issues/204
1. If a function decorated with `#[private_generics(T)]` is called with a generic parameter type that is not allowed, print the code where the `CallGeneric` instruction is located, instead of the called function.
2. In `moveos-stdlib`, some `#[private_generics(T)`] have `T` that is not defined in the current function.
=> Fix error message printing when checking private_generics.

moveos/moveos-verifier/Cargo.toml, moveos/moveos-verifier/src/lib.rs, moveos/moveos-verifier/src/metadata.rs, moveos/moveos-verifier/src/verifier.rs, moveos/moveos/Cargo.toml, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/move_vm_ext.rs
According to issue https://github.com/rooch-network/rooch/issues/202.
When MoveOS executes functions and scripts, the verifier checks the parameters and return values of the functions before execution, in the same way as it checks the entry function during compile time.
=> Check function parameters before executing the function and script.

moveos/moveos-verifier/src/metadata.rs, moveos/moveos/src/moveos.rs
1. verify_entry_function should be before the `resolve_args`.
2. Add 0x1::ascii::String to the allowed parameter types in the entry function.
Pre PR #152
resolve #202
=> Fix in the entry function verifier.

crates/rooch-client/src/lib.rs, crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-server/src/api/rooch_api.rs, crates/rooch-server/src/jsonrpc_types/function_return_value_view.rs, crates/rooch-server/src/jsonrpc_types/mod.rs, crates/rooch-server/src/jsonrpc_types/transaction_argument_view.rs, crates/rooch-server/src/server/rooch_server.rs, crates/rooch-server/src/service/mod.rs, crates/rooch/src/commands/move_cli/commands/publish.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, crates/rooch/src/commands/move_cli/commands/run_view_function.rs, crates/testsuite/features/cmd.feature, crates/testsuite/tests/integration.rs, examples/complex_struct/README.md, examples/kv_store/Move.toml, examples/kv_store/README.md, examples/kv_store/sources/kv_store.move, moveos/moveos-stdlib/tests/cases/table/basic.exp, moveos/moveos-stdlib/tests/cases/table/basic.move, moveos/moveos-types/src/access_path.rs, moveos/moveos-types/src/function_return_value.rs, moveos/moveos-types/src/lib.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/tests/mod.rs, moveos/moveos/src/vm/move_vm_ext.rs
1. Refactor execute_view_function return value, follow #221 
2. Table AccessPath key supports hex and original string. `/table/$table_handle/0xabc,key1`
3. Write a KVStore example for the table test case.
TODO:
1. @pause125  How to pass the `b"key1"` argument in the `cmd.feature` tests.
=> [rpc] Refactor the execute_view_function return value and support string key in Table AccessPath

crates/rooch-types/Cargo.toml, crates/rooch-types/src/transaction/mod.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/mod.rs, moveos/moveos/src/vm/vm_status_explainer.rs
When there is an error in MoveVM verification or execution function, return a customized error message which includes the module and function name.
resolve https://github.com/rooch-network/rooch/issues/227.
=> Return a customized error message when there is an error during function verification or execution.

crates/rooch-client/src/lib.rs, crates/rooch-client/src/wallet_context.rs, crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-integration-test-runner/src/lib.rs, crates/rooch-proposer/src/actor/messages.rs, crates/rooch-proposer/src/proxy/mod.rs, crates/rooch-server/src/api/rooch_api.rs, crates/rooch-server/src/jsonrpc_types/execute_tx_response.rs, crates/rooch-server/src/jsonrpc_types/mod.rs, crates/rooch-server/src/server/rooch_server.rs, crates/rooch-server/src/service/mod.rs, crates/rooch-types/src/transaction/ethereum.rs, crates/rooch-types/src/transaction/mod.rs, crates/rooch-types/src/transaction/rooch.rs, crates/rooch/src/commands/account/commands/create.rs, crates/rooch/src/commands/move_cli/commands/publish.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs, moveos/moveos-types/src/transaction.rs, moveos/moveos-types/src/tx_context.rs, moveos/moveos-verifier/src/verifier.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/move_vm_ext.rs, moveos/moveos/src/vm/tx_argument_resolver.rs
1. Refactor MoveOS, MoveVMExt, and SessionExt, to prepare #209
* Open One Session for One TxContext
* Extract the transaction finalizer logic, ensuring the failed transaction changes should be discarded, but the finalizer's changes must be kept.
3. Rename TransactionInfo to TransactionExecutionInfo.
#232 has a bug. Verifying the module before publishing raises an error because it tries to load the function from the session. @WGB5445
=> [moveos] Refactor MoveOS VM and Session

moveos/moveos-verifier/src/metadata.rs, moveos/moveos-verifier/src/verifier.rs
Return more complete error messages when executing `verify_entry_function` and `verify_init_function`.
`verify_entry_function` returns the `PartialVMError` error type, and `verify_init_function` returns the `VMError` error type.
resolve https://github.com/rooch-network/rooch/issues/243.
=> Return more complete error messages in verify_init_function and verify_entry_function.

README.md, docs/pr-requirements.md
This PR includes code formatting in markdown docs with code highlighting and addition of `rooch init` and fix linking for `./coding-conventions.md`.
=> [docs] fix markdown docs.

moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/mod.rs, moveos/moveos/src/vm/moveos_vm.rs
1. Rename `MoveVmExt` to `MoveOSVM`, `SessionExt` to `MoveOSSesson`.
2. Rename some `table_changeset` variable to `state_changeset`.
3. Add documents describe to MoveOSSession.
=> [MoveOS] MoveOS refactor's rename tasks

moveos/moveos-verifier/Cargo.toml, moveos/moveos-verifier/src/metadata.rs, moveos/moveos-verifier/src/verifier.rs, moveos/moveos/src/vm/moveos_vm.rs
When processing a module publishing request, check whether the generic functions called with `#[private_generics(T)]` are satisfied with the requirements.
resolve https://github.com/rooch-network/rooch/issues/235.
=> When processing a module publishing request, check the private_generics attribute.

docs/design/storage_abstraction.md, docs/design/storage_abstraction.zh-CN.md
There are several issues in the storage abstraction documents.
1. &mut T for mutable references.
2. #[private_generics(T)] for public fun contains.
3. #[private_generics(V)] for V: key as constrains.
=> [docs] fix storage abstraction docs.

.github/actions/rust-setup/action.yaml, .github/workflows/check_build_test.yml
After discussion, we have temporarily removed the CI rust cache. We will observe the effects in the future.
=> remove ci cache

moveos/moveos-stdlib/moveos-stdlib/sources/table.move, moveos/moveos-stdlib/moveos-stdlib/sources/type_table.move, moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs
There are two failed cases:
- `table::test_destroy_nonempty_table`: it should aborts when destroy a non-empty table however not.
- `table::test_nested_table_destroy`: destroy the parent table of a nested table, the child table should not be accessable how not.
Please help review the test cases. @jolestar
=> add unit tests for moveos_stdlib::table and  moveos_stdlib::type_table

crates/rooch-framework/doc/account.md, crates/rooch-framework/doc/address_mapping.md, crates/rooch-framework/doc/transaction_validator.md, crates/rooch-framework/sources/account.move, crates/rooch-framework/sources/address_mapping.move, crates/rooch-framework/sources/transaction_validator.move, crates/rooch-framework/src/bindings/transaction_validator.rs, crates/rooch-genesis/src/lib.rs, crates/rooch-integration-test-runner/tests/cases/private_generics_indirect_call.exp, crates/rooch-integration-test-runner/tests/cases/private_generics_indirect_call.move, crates/rooch-integration-test-runner/tests/cases/publish_cmd.exp, crates/rooch-integration-test-runner/tests/cases/publish_cmd.move, moveos/moveos-stdlib/moveos-stdlib/doc/storage_context.md, moveos/moveos-stdlib/moveos-stdlib/sources/storage_context.move, moveos/moveos-types/src/move_any.rs, moveos/moveos-types/src/move_string.rs, moveos/moveos-types/src/storage_context.rs, moveos/moveos-types/src/tx_context.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/moveos_vm.rs, moveos/moveos/src/vm/tx_argument_resolver.rs
Resolve #302 
1. [rooch-framework] transaction_validator add pre_execute, rename finalize to post_execute
2. [moveos] Refactor MoveOS: execute pre_execute_function before transaction execute
3. [moveos] Remove TxContext from the tx argument resolver
4. [integration-test] fix integration test
TODO:
1. #323
2. Finish the transaction flow document #126 
3. How to test the ethereum signature and address from cli? @wow-sven @yubing744
=> [MoveOS] Execute `pre_execute` function before transaction execute 

moveos/moveos/src/moveos_test_runner.rs
On Linux systems, the directory for temporary files is /tmp, while on macOS, the directory is /var. Both of these paths need to be replaced with fixed paths in the error messages generated by private_generics, just like mentioned in issue https://github.com/rooch-network/rooch/issues/331.
resolve https://github.com/rooch-network/rooch/issues/331.
=> Handle the path of temporary files on macOS.

crates/rooch-framework-tests/tests/cases/table/test_destroy.exp, crates/rooch-framework-tests/tests/cases/table/test_destroy.move, crates/rooch-framework/doc/authenticator.md, moveos/moveos-stdlib/moveos-stdlib/doc/object.md, moveos/moveos-stdlib/moveos-stdlib/doc/object_storage.md, moveos/moveos-stdlib/moveos-stdlib/doc/raw_table.md, moveos/moveos-stdlib/moveos-stdlib/doc/storage_context.md, moveos/moveos-stdlib/moveos-stdlib/doc/table.md, moveos/moveos-stdlib/moveos-stdlib/doc/type_table.md, moveos/moveos-stdlib/moveos-stdlib/sources/object_storage.move, moveos/moveos-stdlib/moveos-stdlib/sources/raw_table.move, moveos/moveos-stdlib/moveos-stdlib/sources/table.move, moveos/moveos-stdlib/moveos-stdlib/sources/type_table.move, moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs
Part of #342 
1. Provide destory_empty in table,type_table,object_storage module
2. There is a bug in the native implementation of `destory_empty`. I give a test example.
The bug will be resolved in the future PR, based on Table's `length` solution.
=> [MoveosStdlib] Public the `destory_empty` function in table,type_table,object_storage module

crates/rooch-framework-tests/tests/cases/entry_function/entry_function_invalid_struct.exp, crates/rooch-framework-tests/tests/cases/entry_function/entry_function_valid_reference.exp, crates/rooch-framework-tests/tests/cases/entry_function/entry_function_with_return_value.exp, crates/rooch-framework-tests/tests/cases/object/object_cap.exp, crates/rooch-integration-test-runner/tests/cases/private_generics_indirect_call.exp, moveos/moveos-verifier/src/metadata.rs, moveos/moveos/src/moveos_test_runner.rs
1. Fix the issue of illegal invocation of private_generics in the module without throwing an error. @feliciss 
2. In the testing framework, do not print 'EXECUTED' when there is a compilation error.
=> Fix the issue of not throwing an error during compilation of the private_generics module.

crates/rooch/src/commands/init.rs
=> [cli] return a type of string instead of empty to avoid null value

Cargo.toml, crates/rooch-framework-tests/tests/cases/entry_function/entry_function_invalid_struct.exp, crates/rooch-framework-tests/tests/cases/entry_function/entry_function_valid_reference.exp, crates/rooch-framework-tests/tests/cases/entry_function/entry_function_with_return_value.exp, crates/rooch-framework-tests/tests/cases/object/object_cap.exp, crates/rooch-integration-test-runner/Cargo.toml, crates/rooch-integration-test-runner/src/lib.rs, crates/rooch-integration-test-runner/tests/cases/private_generics_indirect_call.exp, crates/rooch/Cargo.toml, crates/rooch/src/commands/move_cli/commands/integration_test.rs, moveos/moveos-verifier/src/metadata.rs, moveos/moveos/src/moveos_test_runner.rs
The issue of not checking `private_generics` when executing the command `rooch move integration-test -p private_generics/ --named-addresses rooch_examples=0x1234` in the `examples/private_generics` directory has been resolved.
However, there are still some remaining issues:
1. The `datatest_stable::runner_with_opts` invocation is bypassed, and the test cases are executed directly. This means that some additional options, such as `rooch move test --list` to view the current test projects, will not be executed (but it does not affect the testing process).
2. Because the `integration-test` depends on a complete Move package, and it is itself a separate Move file, it is not possible to compile them together. Instead, the dependent Move package is compiled first, followed by the compilation of …
=> Check if private_generics is used correctly in the integration-test.

crates/rooch-framework-tests/tests/cases/entry_function/entry_function_valid_reference.exp, crates/rooch-framework-tests/tests/cases/entry_function/entry_function_valid_struct.exp, crates/rooch-integration-test-runner/src/lib.rs, moveos/moveos-stdlib/move-stdlib/doc/error.md, moveos/moveos-verifier/src/metadata.rs
resolve https://github.com/rooch-network/rooch/issues/323.
=> Remove TxContext from the check in the entry function.

crates/rooch-framework/doc/README.md, crates/rooch-framework/doc_template/README.md, crates/rooch-framework/doc_template/overview.md, moveos/moveos-stdlib-builder/src/lib.rs, moveos/moveos-stdlib/move-stdlib/doc/README.md, moveos/moveos-stdlib/move-stdlib/doc_template/README.md, moveos/moveos-stdlib/move-stdlib/doc_template/overview.md, moveos/moveos-stdlib/moveos-stdlib/doc/README.md, moveos/moveos-stdlib/moveos-stdlib/doc_template/README.md, moveos/moveos-stdlib/moveos-stdlib/doc_template/overview.md
Rename the template overview.md to README.md for a better view of the document on GitHub.
=> [FrameworkDoc] Rename the overview.md to README.md

.github/workflows/check_build_test.yml
This way, docs related changes should always be passed.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks
=> use paths-ignore instead

crates/rooch/Cargo.toml, crates/rooch/src/commands/move_cli/commands/unit_test.rs, examples/private_generics/sources/private_generics.move, moveos/moveos-verifier/Cargo.toml, moveos/moveos-verifier/src/build.rs
When executing the command `rooch move test`, check the functions decorated with the `#[test]` attribute to ensure they comply with the rules for calling `private_generics`.
resolve https://github.com/rooch-network/rooch/issues/335.
=> Compile and check private_generics during the execution of rooch move test

crates/rooch-integration-test-runner/src/lib.rs, crates/rooch/src/commands/move_cli/commands/build.rs, crates/rooch/src/commands/move_cli/commands/publish.rs, moveos/moveos-stdlib-builder/src/lib.rs, moveos/moveos-verifier/src/build.rs
When executing "rooch move build -d", the private_generics are compiled and checked. Now, add a check for dev_mode.
resolve https://github.com/rooch-network/rooch/issues/441.
=> Fix issues with rooch move build in development mode.

crates/rooch-types/src/address.rs, crates/rooch-types/src/transaction/rooch.rs
resolves #438 
Tests should generate and pass all BTC address versions.
This is to ensure the assumed addresses are correctly mapped for all Bitcoin address versions.
=> [gh-438] add btc address supports for random() case.

crates/rooch/src/commands/move_cli/commands/publish.rs
=> [gh-472] add helper function if modules are empty.

crates/rooch/src/cli_types.rs
Fix the crash when parsing empty vector in `rooch move run` args. Now, you can use the `vector<type>:` format to pass an empty vector:
```
rooch move run --function 0x1::rooch::counter --args "vector<u8>:" --sender-account default
```
=> Support empty vector in `rooch move run` args

examples/blog/README.md, examples/blog/README_CN.md, examples/blog/dddml/blog.yaml, examples/blog/sources/article_aggregate.move, examples/blog/sources/article_create_logic.move, examples/blog/sources/article_delete_logic.move, examples/blog/sources/blog.move, examples/blog/sources/blog_add_article_logic.move, examples/blog/sources/blog_aggregate.move, examples/blog/sources/blog_remove_article_logic.move
原来的 CLI 对于类型为 vector<T> 的参数不支持传入空的 vector。在原来的 README 中，测试应用碰到这个情况时先随意传入了一个元素，让 vector 不为空，避免出错。这个地方做了修改。
上一个版本改进后的示例应用还有一些“用户需求”可能没有满足。
比如说，不支持不同的账户（用户）在同一个博客中创作文章（Getting Started 文章示例的 simple blog 也存在同样问题）。
在本次更新的示例中，我们演示了如何解决这些问题。
---
The previous CLI did not support passing an empty vector for arguments of type vector<T>. In the previous README, when testing applications that encountered this situation, an arbitrary element was passed in so that the vector would not be empty, to avoid the error. This has been changed.
There are still some "user requirements" that may not have been met in the previous version of the improved example application.
For example, there was no support for different accounts (users) to create articles in the same blog (the same problem existed in the "simple …
=> Update blog example

docs/website/pages/docs/developer/_meta.en-US.json, docs/website/pages/docs/developer/_meta.zh-CN.json, docs/website/pages/docs/developer/rooch-cli.en-US.mdx, docs/website/pages/docs/developer/rooch-cli.zh-CN.mdx
Examples https://github.com/rooch-network/rooch/issues/491
=> init cli doc

docs/website/pages/docs/developer/installation.en-US.mdx, docs/website/pages/docs/developer/installation.zh-CN.mdx
fixed typo error on installation page
=> Update installation.en-US.mdx and installation.zh-CN.mdx

Cargo.toml, crates/rooch/src/commands/move_cli/commands/integration_test.rs, crates/rooch/src/commands/move_cli/mod.rs, examples/counter/integration-tests/counter.exp, examples/counter/integration-tests/counter.move, examples/counter/sources/counter.move, moveos/moveos/src/moveos_test_model_builder.rs
Refactor the integration-test to allow it to import moveos_stdlib and other third-party Move Packages.
resolve https://github.com/rooch-network/rooch/issues/452.
=> Refactor the rooch move integration-test

crates/rooch/src/commands/move_cli/commands/integration_test.rs, examples/counter/sources/counter.move
Add the `#[test_only]` attribute to integration test functions to prevent them from being compiled into the Move Package.
=> Add test_only attribute to integration test functions.

crates/rooch-types/src/error.rs, crates/rooch/src/commands/env/commands/add.rs, crates/rooch/src/commands/env/commands/list.rs, crates/rooch/src/commands/env/commands/mod.rs, crates/rooch/src/commands/env/commands/remove.rs, crates/rooch/src/commands/env/commands/switch.rs, crates/rooch/src/commands/env/mod.rs, crates/rooch/src/commands/mod.rs, crates/rooch/src/lib.rs
This PR resolves #507 
It adds support for multiple environments in the Rooch CLI, the below features were implemented
- Add new env
- List all envs
- Switch active env
- Remove env
=> Multi environment support

crates/rooch-types/src/error.rs, crates/rooch/src/commands/account/commands/mod.rs, crates/rooch/src/commands/account/commands/switch.rs, crates/rooch/src/commands/account/mod.rs
Resolves #508 
Example usage:
```sh
rooch account switch --address <address>
```
Example output:
```txt
Active account successfully switched to <address>
```
=> add `rooch account switch` command

crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-framework/sources/transaction_validator.move, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/api/rooch_api.rs, crates/rooch-rpc-api/src/jsonrpc_types/function_return_value_view.rs, crates/rooch-rpc-client/src/lib.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/mod.rs, crates/rooch-types/Cargo.toml, crates/rooch-types/src/framework/account_authentication.rs, crates/rooch-types/src/framework/address_mapping.rs, crates/rooch-types/src/framework/auth_validator.rs, crates/rooch-types/src/framework/bitcoin_validator.rs, crates/rooch-types/src/framework/empty.rs, crates/rooch-types/src/framework/ethereum_validator.rs, crates/rooch-types/src/framework/native_validator.rs, crates/rooch-types/src/framework/nostr_validator.rs, crates/rooch-types/src/framework/session_key.rs, crates/rooch-types/src/framework/transaction_validator.rs, crates/rooch/src/commands/move_cli/commands/run_view_function.rs, crates/testsuite/features/cmd.feature, moveos/moveos-types/Cargo.toml, moveos/moveos-types/src/function_return_value.rs, moveos/moveos-types/src/module_binding.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/moveos_vm.rs, sdk/typescript/src/client/rooch-client.ts
Prepare for #644 
1. Define `FunctionResult`, and return the `VMStatus` and `Vec<FunctionReturnValue>` to the caller.
2. The RPC `execute_view_function` response changed from `Vec<AnnotatedFunctionReturnValue>` to `AnnotatedFunctionResultView`. This change will break the RPC, and some documents need to be updated. @geometryolife 
```bash
rooch move view --function 0x2763f0616014847fc57b78fe267d0999f4277770ddf521507005059839ac0946::counter::value
```
```json
{
"vm_status": "Executed",
"return_values": [
{
"value": {
"type_tag": "u64",
"value": "0x0000000000000000"
},
"move_value": "0"
}
]
}
```
Now, the caller can handle the function abort code.
=> [VM] Refactor view_function result, return the VMStatus to caller

crates/rooch-executor/Cargo.toml, crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-framework-tests/src/tests/transaction_validator_tests.rs, crates/rooch-types/src/framework/auth_validator.rs, crates/rooch-types/src/framework/transaction_validator.rs, moveos/moveos-types/src/function_return_value.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/vm_status_explainer.rs
follow #646 
resolve #644 
1. Return VMStatus from VM execute_view_function to validate function. We need to define some embed Result struct, eg: `Result<Result<T>, VMStatus>`.
2. Improve the session key test, to check the move abort code.
cc @feliciss
=> [MoveOS & Executor] Refactor validator to let caller got VMStatus

crates/rooch-rpc-server/src/server/eth_server.rs
Change the `eth_chainId` API's `chainId` hex to lowercase.
- Closes #690 
cc @feliciss
=> [RPC] Fix eth_chainId response

crates/rooch-genesis/build.rs, docs/website/pages/docs/reference/rpc.en-US.mdx, docs/website/pages/docs/reference/rpc.zh-CN.mdx
1. Fix moveos-stdlib genesis build directory.
2. Fix RPC links.
- Closes #714 again
=> [gh-714] fix build directory.

crates/rooch-framework/doc/account.md, crates/rooch-framework/doc/account_authentication.md, crates/rooch-framework/doc/address_mapping.md, crates/rooch-framework/doc/auth_validator.md, crates/rooch-framework/doc/auth_validator_registry.md, crates/rooch-framework/doc/bitcoin_address.md, crates/rooch-framework/doc/bitcoin_validator.md, crates/rooch-framework/doc/builtin_validators.md, crates/rooch-framework/doc/chain_id.md, crates/rooch-framework/doc/coin.md, crates/rooch-framework/doc/core_addresses.md, crates/rooch-framework/doc/decoding.md, crates/rooch-framework/doc/ecdsa_k1.md, crates/rooch-framework/doc/ecdsa_k1_recoverable.md, crates/rooch-framework/doc/ed25519.md, crates/rooch-framework/doc/encoding.md, crates/rooch-framework/doc/ethereum_address.md, crates/rooch-framework/doc/ethereum_validator.md, crates/rooch-framework/doc/gas_coin.md, crates/rooch-framework/doc/genesis.md, crates/rooch-framework/doc/hash.md, crates/rooch-framework/doc/multi_ed25519_validator.md, crates/rooch-framework/doc/native_validator.md, crates/rooch-framework/doc/nostr_validator.md, crates/rooch-framework/doc/schnorr.md, crates/rooch-framework/doc/session_key.md, crates/rooch-framework/doc/transaction_validator.md, moveos/moveos-stdlib-builder/src/lib.rs
The document reference link is incorrect, and I removed it temporarily, We should fix it in the future #737 .
The path from `crates/rooch-framework/doc/address_mapping.md` to `moveos/moveos-stdlib/move-stdlib/doc/option.md` is `../../../moveos/moveos-stdlib/move-stdlib/doc/option.md`, not `../../moveos/moveos-stdlib/move-stdlib/doc/option.md`
=> [stdlib] remove the incorrect reference links from move docs

crates/rooch-framework/doc/coin.md, crates/rooch-framework/doc/gas_coin.md, crates/rooch-framework/sources/coin.move, crates/rooch-framework/sources/gas_coin.move, crates/rooch-framework/sources/tests/coin_test.move, crates/rooch-framework/sources/tests/gas_coin_test.move
part of #13  
Refactor coin module. follow #738
1. Remove capability from the coin module, simply the token logic.
2. Change the `initialize` function to `register_extend`.
3. Add `key` ability to `CoinType`, prevent call like `coin::zero<u64>()`.
4. Add `store` ability requirement to `transfer`,`withdraw`,`deposit`. A CoinType should have `key` and `store` abilities if it is public. Otherwise, it is a private coin, The users only can operate the coin through the methods defined by the CoinType module.
TODO give some coin examples #741
=> [Framework]Refactor coin module 

docker/Dockerfile
apt-get  install the dependency for librocksdb-sys-7e3c2fe0997fa0a5
- Closes #750
=> fix librocksdb-sys build failed

crates/rooch/src/commands/move_cli/commands/unit_test.rs, crates/rooch/src/commands/move_cli/mod.rs
Hi, I'm new in Rooch.
I'm interested in this project and I'm reading docs and some codes.
I want to contribute and learn. Thanks.
added `config_options` field into Test.
updated `execute` method to handle account args like `build ` command.
- Closes #575
=> fix(cli): update execute method of Test to handle account args

crates/rooch/src/commands/move_cli/mod.rs
Set `rooch move errmap` error_prefix default to `Error`. Follow #664 , Ref #663
=> [CLI] set error_prefix to Error

crates/rooch-executor/src/actor/executor.rs, crates/rooch-genesis/src/lib.rs, crates/rooch-integration-test-runner/src/lib.rs, crates/rooch-types/src/framework/mod.rs, moveos/moveos-types/src/move_simple_map.rs, moveos/moveos-types/src/tx_context.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/moveos_vm.rs, moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs
1. Refactor MoveOS and Session to handle pre_execute and post_execute errors.
2. Keep `TxValidateResult` when respawn session.
- Closes #607
=> Txcontext respawn

crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/api/rooch_api.rs, crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs, crates/rooch-rpc-api/src/jsonrpc_types/transaction_view.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/aggregate_service.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch-sequencer/src/actor/sequencer.rs, crates/rooch-sequencer/src/messages.rs, crates/rooch-sequencer/src/proxy/mod.rs, crates/rooch-store/src/lib.rs, crates/rooch-store/src/meta_store/mod.rs, crates/rooch-store/src/transaction_store/mod.rs, crates/rooch-types/src/transaction/mod.rs
Summary:
1. Unify and rename for RPC and store
2. Remove RPC `GetEvents by EventFilter`. The current scenario of querying events can be satisfied by `getEventsByEventHandle`. `GetEvents by EventFilter` will be enabled after the Indexer is supported.
=> unify and rename for RPC and store

moveos/moveos-commons/moveos-common/src/utils.rs
resolve https://github.com/rooch-network/rooch/issues/804
=> Fixed cargo build failed on Windows due to unresolved check_open_fds_limit

crates/rooch-framework-tests/src/tests/transaction_validator_tests.rs, crates/rooch-framework/doc/chain_id.md, crates/rooch-framework/doc/session_key.md, crates/rooch-framework/doc/timestamp.md, crates/rooch-framework/sources/chain_id.move, crates/rooch-framework/sources/session_key.move, crates/rooch-framework/sources/tests/session_key_test.move, crates/rooch-framework/sources/timestamp.move, crates/rooch-types/src/framework/session_key.rs, crates/rooch-types/src/framework/timestamp.rs, crates/rooch/src/commands/session_key/commands/create.rs, sdk/typescript/src/account/account.ts, sdk/typescript/src/account/interface.ts, sdk/typescript/test/e2e/sdk.test.ts
1. Implement session key expired logic based on timestamp.
2. Remove the `expiration_time` field and add the `create_time` field for `SessionKey`. 
3. Provide a method that lets the developer fast-forward the timestamp on the dev chain for testing.
4. Add a test case for the session key.
- Closes #802
=> [Framework] Implement session key expired logic based on timestamp

Cargo.lock, crates/rooch-framework-tests/src/tests/transaction_validator_tests.rs, crates/rooch-integration-test-runner/Cargo.toml, crates/rooch-integration-test-runner/src/lib.rs, moveos/moveos-stdlib/moveos-stdlib/doc/type_info.md, moveos/moveos-stdlib/moveos-stdlib/sources/type_info.move, moveos/moveos/src/moveos_test_runner.rs
resolve https://github.com/rooch-network/rooch/issues/724
The temporary files for the three libraries `(move-stdlib, moveos-stdlib, rooch-framework)` that were compiled-time dependencies have been eliminated. `(65 temporary files)`
```rust
for module in stdlib_modules
.iter()
.filter(|module| !adapter.compiled_state.is_precompiled_dep(&module.self_id()))
.collect::<Vec<_>>()
{
adapter
.compiled_state
.add_and_generate_interface_file(module.clone());
}
```
However, there are still one or two temporary files generated by the "publish" command in the .move file. Therefore, the next step is to compile these one or two temporary files into `FullyCompiledPrograms` and merge them with the previously compiled three library dependencies, thus completely eliminating the temporary files.
=> Use FullyCompiledProgram instead of temporary files.

crates/rooch-rpc-server/src/service/aggregate_service.rs, crates/rooch-types/src/framework/coin.rs
Resolve https://github.com/rooch-network/rooch/issues/819 and part of https://github.com/rooch-network/rooch/issues/827
Handle `expect` and `unwrap` for RPC to ensure no panic occurs, and avoid the RPC returning nothing.
=> handle expect and unwrap for RPC to ensure no panic

Cargo.lock, moveos/moveos/Cargo.toml, moveos/moveos/src/moveos.rs
Keep the original error status when execution failed.
And print stack trace when execution panic.
- Closes #842
=> fix VM status and print stack trace

crates/rooch-framework/doc/gas_coin.md, crates/rooch-framework/sources/gas_coin.move, crates/rooch-rpc-client/src/lib.rs, crates/rooch-rpc-server/src/lib.rs, crates/rooch-rpc-server/src/server/eth_server.rs, crates/rooch-rpc-server/src/service/aggregate_service.rs, crates/rooch-types/src/framework/gas_coin.rs, crates/rooch-types/src/framework/mod.rs, crates/rooch/src/commands/mod.rs, crates/rooch/src/commands/rpc/commands/mod.rs, crates/rooch/src/commands/rpc/commands/request.rs, crates/rooch/src/commands/rpc/mod.rs, crates/rooch/src/lib.rs, crates/testsuite/features/cmd.feature, crates/testsuite/tests/integration.rs
1. Implement `eth_getBalance` API, and return GasCoin as balance. If the account does not exist, return zero("0x0").
2. Add `store` to GasCoin, allow public transfer GasCoin.
3. Add `rooch rpc request` command for rpc test.
4. Improve integration test for supporting escape string in the arguments.
- Closes #765
=> [rpc] Implement `eth_getBalance`

crates/rooch-rpc-server/src/lib.rs, crates/rooch-rpc-server/src/service/aggregate_service.rs, crates/rooch-rpc-server/src/service/mod.rs, crates/rooch-rpc-server/src/service/rpc_logger.rs
Fix `block_on` bug and Add RpcLogger for debugging
- Closes #826 #872
```bash
cat eth_getBalance.txt
```
```json
{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x75cc549e78df95afd6c2b782cdcdd15f5115220c"],"id":67}
```
```bash
ab -n 1000 -c 10 -T application/json -p eth_getBalance.txt http://127.0.0.1:50051/
```
=> [Fix] Fix block_on bug and add RpcLogger

crates/rooch-framework/doc/gas_coin.md, crates/rooch-framework/sources/gas_coin.move, crates/rooch-framework/sources/transaction_validator.move, crates/rooch-rpc-server/src/server/eth_server.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch-types/src/framework/gas_coin.rs, crates/testsuite/features/cmd.feature
1. GasCoin decimals to 18.
2. If an account does not exist, return a default balance.
=> [ETH&GasCoin] Fix some MetaMask compatibility issue

crates/rooch-framework/doc/README.md, crates/rooch-framework/doc/address_mapping.md, crates/rooch-framework/doc/bitcoin_address.md, crates/rooch-framework/doc/ethereum_address.md, crates/rooch-framework/doc/genesis.md, crates/rooch-framework/doc/multichain_address.md, crates/rooch-framework/doc/transaction_validator.md, crates/rooch-framework/doc/transfer.md, crates/rooch-framework/sources/address_mapping.move, crates/rooch-framework/sources/address_type/bitcoin_address.move, crates/rooch-framework/sources/address_type/ethereum_address.move, crates/rooch-framework/sources/address_type/multichain_address.move, crates/rooch-framework/sources/genesis.move, crates/rooch-framework/sources/tests/address_maping_test.move, crates/rooch-framework/sources/tests/transfer_test.move, crates/rooch-framework/sources/transaction_validator.move, crates/rooch-framework/sources/transfer.move, crates/rooch-types/src/framework/ethereum_light_client.rs, crates/rooch-types/src/framework/gas_coin.rs, crates/rooch-types/src/framework/mod.rs, crates/rooch-types/src/framework/transfer.rs, crates/rooch-types/src/transaction/ethereum.rs
1. Migrate `MultiChainAddress` to `multichain_address.move`
2. Implement `transfer::transfer_coin_to_multichain_address`
3. Auto convert ETH transfer transaction to GasCoin transfer, support transfer GasCoin in MetaMask.
- Closes #879
=> [Framework] Support transfer coin to multichain address

dashboard/src/views/feature/SessionKeyList.tsx, sdk/typescript/test/e2e/sdk.test.ts, sdk/typescript/test/e2e/servers/rooch-server.ts
Fixed the issue where the session key list was created and the last active time was displayed incorrectly
https://github.com/rooch-network/rooch/issues/896
=> feat: fixbug for session key list create_time not show correct

dashboard/src/@core/components/session/SessionGuard.tsx, dashboard/src/@core/layouts/components/shared-components/UserDropdown.tsx, dashboard/src/context/session/SessionContext.tsx, dashboard/src/context/session/types.ts, dashboard/src/store/session/index.ts, dashboard/src/views/feature/SessionKeyList.tsx, sdk/typescript/src/utils/error.test.ts, sdk/typescript/src/utils/error.ts
1. Optimize Session Key operation error prompts
2. Fixed cached Session Key conflict when switching networks
https://github.com/rooch-network/rooch/issues/734
=> feat: opt session key error tips

crates/rooch-config/src/lib.rs, crates/rooch-config/src/server_config.rs, crates/rooch-key/Cargo.toml, crates/rooch-key/src/keystore.rs, crates/rooch-rpc-client/src/wallet_context.rs, crates/rooch-rpc-server/Cargo.toml, crates/rooch-rpc-server/src/lib.rs, crates/rooch-types/Cargo.toml, crates/rooch-types/src/crypto.rs, crates/rooch-types/src/error.rs, crates/rooch/src/commands/account/commands/balance.rs, crates/rooch/src/commands/account/commands/create.rs, crates/rooch/src/commands/account/commands/import.rs, crates/rooch/src/commands/account/commands/list.rs, crates/rooch/src/commands/account/commands/nullify.rs, crates/rooch/src/commands/account/commands/switch.rs, crates/rooch/src/commands/account/commands/update.rs, crates/rooch/src/commands/env/commands/add.rs, crates/rooch/src/commands/env/commands/list.rs, crates/rooch/src/commands/env/commands/remove.rs, crates/rooch/src/commands/env/commands/switch.rs, crates/rooch/src/commands/init.rs, crates/rooch/src/commands/move_cli/commands/new.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, crates/rooch/src/commands/server/commands/start.rs, crates/rooch/src/commands/session_key/commands/create.rs, crates/testsuite/tests/integration.rs
resolve https://github.com/rooch-network/rooch/issues/800
Summary
1. Init server config when `Rooch init`, and generate rooch key pair in keystore, both for sequencer, proposer, and relayer
Notice
Due to dependencies (Keystore is in WalletContext), the server loads key pairs from the command line by default and then passes them to the RPC Server. KeyPair does not have a clone attribute. The ServerOpt attribute is newly added to encapsulate and extend KeyPairs and other configurations.
There will be an impact on the SDK.
Todo
Wait the password option to decrypt private key for commands
=> Refactor the keypair management of sequencer, proposer, and relayer

crates/rooch-framework-tests/tests/cases/table/test_destroy.exp, crates/rooch-framework-tests/tests/cases/table/test_destroy.move, crates/rooch-framework/src/natives/gas_parameter/table_extension.rs, moveos/moveos-stdlib/moveos-stdlib/doc/raw_table.md, moveos/moveos-stdlib/moveos-stdlib/doc/table.md, moveos/moveos-stdlib/moveos-stdlib/sources/raw_table.move, moveos/moveos-stdlib/moveos-stdlib/sources/table.move, moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs, moveos/moveos-store/src/lib.rs, moveos/moveos-store/src/state_store/statedb.rs, moveos/moveos-types/src/object.rs, moveos/moveos-types/src/state.rs, moveos/moveos-types/src/state_resolver.rs, moveos/moveos/src/gas/parameter.rs, moveos/moveos/src/vm/data_cache.rs, moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs
1. Destroy the table if the value of table has the drop ability. Close #899 
2. Add interface of table::length and table::is_empty, support destroy empty table. Close #342
3. Fix bug when table::destroy non-empty tables. Close #320
=> Optimize moveos_stdlib::table 

crates/rooch-key/src/keystore.rs, crates/rooch-rpc-client/src/client_config.rs, crates/rooch-rpc-client/src/wallet_context.rs, crates/rooch/src/cli_types.rs, crates/rooch/src/commands/account/commands/create.rs, crates/rooch/src/commands/account/commands/import.rs, crates/rooch/src/commands/account/commands/list.rs, crates/rooch/src/commands/account/commands/nullify.rs, crates/rooch/src/commands/account/commands/switch.rs, crates/rooch/src/commands/account/commands/update.rs, crates/rooch/src/commands/init.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, crates/rooch/src/commands/server/commands/start.rs, crates/rooch/src/commands/session_key/commands/create.rs
resolve https://github.com/rooch-network/rooch/issues/906
Summary
1. Remove the keystore from the client config, leaving only the keystore path in the client config
2. Load keystore in Wallet Context, keystore is used as an attribute of WalletContext
3. Make the account account create to a local operation; do not execute the transaction
=> refactor wallet context and fixup account cli

crates/rooch-framework-tests/tests/cases/object/basic.exp, crates/rooch-framework-tests/tests/cases/object/basic.move, crates/rooch-framework-tests/tests/cases/object/object_cap.exp, crates/rooch-framework-tests/tests/cases/object/object_cap.move, crates/rooch-framework-tests/tests/cases/table/basic.exp, crates/rooch-framework-tests/tests/cases/table/basic.move, crates/rooch-framework-tests/tests/cases/table/test_destroy.exp, crates/rooch-framework-tests/tests/cases/table/test_destroy.move, examples/basic_object/sources/something.move, examples/blog/sources/article.move, examples/complex_struct/sources/complex_struct.move, examples/module_init/sources/box.move, examples/simple_blog/sources/article.move, moveos/moveos-stdlib/moveos-stdlib/doc/context.md, moveos/moveos-stdlib/moveos-stdlib/doc/object.md, moveos/moveos-stdlib/moveos-stdlib/sources/context.move, moveos/moveos-stdlib/moveos-stdlib/sources/object.move
Follow refactor of #918 
1. Make `object::new` to friend.
2. Provide `context::new_object` and `context::new_object_with_owner`.
=> [MoveosStd] wrap object::new with context::new_object

crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/api/rooch_api.rs, crates/rooch-rpc-client/src/lib.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/aggregate_service.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch-sequencer/src/actor/sequencer.rs, crates/rooch-sequencer/src/messages.rs, crates/rooch-sequencer/src/proxy/mod.rs, crates/rooch-store/src/lib.rs, crates/rooch-store/src/transaction_store/mod.rs, crates/rooch/src/commands/transaction/commands/get_transactions_by_hash.rs, crates/rooch/src/commands/transaction/mod.rs, crates/testsuite/features/cmd.feature, sdk/typescript/src/provider/json-rpc-provider.ts, sdk/typescript/test/e2e/sdk.test.ts
resolve https://github.com/rooch-network/rooch/issues/844
Summary
1. Support reverse search tx order by tx hash
2. Make the output of get_transactions_by_hash and get_transactions_by_order are consistent, contains transaction, sequence info and execution info at the same time
3. Refactor tx rpc for traversing the SMT Tree be optimized into a multi get query to improve query performance
4. Make `Sequencer Order` start with 0, which is semantically consistent with the contract’s `sequence_number`, RPC’s cursor and other parameters.
=> Support reverse search tx order by tx hash and refactor tx RPC to improve query performance

.github/workflows/check_build_test.yml, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/api/rooch_api.rs, crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs, crates/rooch-rpc-api/src/jsonrpc_types/transaction_view.rs, crates/rooch-rpc-client/src/rooch_client.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/aggregate_service.rs, crates/rooch/build.rs, crates/rooch/src/commands/transaction/commands/get_transactions_by_hash.rs, crates/rooch/src/commands/transaction/commands/get_transactions_by_order.rs, dashboard/src/store/scan/transaction/index.ts, sdk/typescript/src/provider/json-rpc-provider.ts, sdk/typescript/tools/generator/template/name_mapping.json
1. Rename TransactionResult to TransactionWithInfo
2. Rename TransactionResultPageView to TransactionWithInfoPageView
TODO:
1. ExecuteTransactionResponseView should rename to ?
2. The ListView needs to be refactored in a new PR. #965
=> [Rpc] rename TransactionResult to TransactionWithInfo

.github/workflows/check_build_test.yml, crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch/.gitignore, sdk/typescript/tools/generator/template/name_mapping.json
Make event RPC page view no nullable.
Part of #966 and #970 
=> [RPC] Make event rpc page view no nullable

crates/rooch-executor/src/actor/executor.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs, crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs, moveos/moveos-store/src/event_store/mod.rs, moveos/moveos-types/src/event.rs, moveos/moveos-types/src/event_filter.rs
resolve https://github.com/rooch-network/rooch/issues/969
Summary
1. refactor event RPC,  and remove `sender `, `tx_hash` and `timestamp`, to make a pure event
2. rename `parsed_event_data` to `encoded_event_data`, and unify with other Annotated state
Todo
1. How to raise an error inner Iterator::filter_map to avoid panic?
=> refactor event RPC to make a pure event

.github/workflows/deploy_examples.yml, .github/workflows/docker_build.yml, scripts/check_dev_deploy_status.sh
recovery dev addr  with MNEMONIC_PHRASE
=> recovery dev addr and mannual deploy examples

crates/rooch-framework/doc/account.md, crates/rooch-framework/doc/transaction_validator.md, crates/rooch-framework/sources/account.move, crates/rooch-framework/sources/transaction_validator.move
Transaction validator temporarily accepts future sequence_number for devnet experience.
Because the devnet will be reset frequently, the sequence number will be reset to 0
However, the sequence number(nonce) in MetaMask will not be reset, so the transaction will be rejected. 
case: #994
=> [Framework] Transaction validator accept future sequence_number.

crates/rooch-framework/sources/transaction_validator.move, examples/gas_free/Move.toml, examples/gas_free/sources/gas_free.move, moveos/moveos-stdlib/moveos-stdlib/doc/tx_result.md, moveos/moveos-stdlib/moveos-stdlib/sources/tx_result.move, moveos/moveos-types/src/moveos_std/tx_result.rs, moveos/moveos-verifier/src/metadata.rs, moveos/moveos-verifier/src/verifier.rs, moveos/moveos/src/moveos.rs
This is part of https://github.com/rooch-network/rooch/issues/839
Check the Gas Free function during the compilation of the Move module.
TODO:
1. Verify the correctness of the Gas Free function information in the module's metadata during module publishing.
2. Deduct gas fees by reading and executing the Gas Fee function information from the metadata.
=> Check the Gas Free function during the compilation of the Move module.

Cargo.lock, crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs, crates/rooch-types/src/framework/account_authentication.rs, crates/rooch-types/src/framework/account_coin_store.rs, crates/rooch-types/src/framework/address_mapping.rs, crates/rooch-types/src/framework/coin.rs, crates/rooch-types/src/framework/coin_store.rs, crates/rooch-types/src/framework/session_key.rs, moveos/moveos-types/Cargo.toml, moveos/moveos-types/src/moveos_std/object_ref.rs, moveos/moveos-types/src/moveos_std/tx_meta.rs, moveos/moveos-types/src/state.rs
Refactor and Make the MoveState & MoveStructState traits clearer.
1. MoveStructState is MoveState.
2. Remove the repeat function from MoveStructState.
3. Provide a layout match function for MoveState.
4. Provide to/from functions for MoveState and MoveRuntime Value. 
=> [types] Refactor MoveState & MoveStructState API

crates/rooch-executor/src/actor/executor.rs, crates/rooch-framework-tests/src/tests/ethereum_validator_tests.rs, crates/rooch-framework-tests/src/tests/transaction_validator_tests.rs, crates/rooch-rpc-server/src/server/eth_server.rs, crates/rooch-types/src/framework/address_mapping.rs, crates/rooch-types/src/transaction/ethereum.rs, crates/rooch-types/src/transaction/mod.rs
1. Construct Move tx for Ethereum validator without signing from key store.
2. Construct Ethereum address from Rooch address from key store with first 20 bytes.
- Closes #945
=> [gh-945] fix integration tests for ethereum.

.github/workflows/docker_build.yml, scripts/check_dev_deploy_status.sh
=> fix devnet workflow

.github/workflows/check_build_test.yml
After the rooch dashboard cmd is deleted, modify the test flow and add build tests for the dashboard.
Avoid When the sdk is modified, the dashboard can run in dev mode, but deployment errors may occur
=> add dashboard build test

crates/rooch-framework-tests/src/tests/ethereum_light_client_test.rs, crates/rooch-framework-tests/tests/cases/timestamp/timestamp_test.exp, crates/rooch-framework-tests/tests/cases/timestamp/timestamp_test.move, crates/rooch-framework/doc/timestamp.md, crates/rooch-framework/sources/account.move, crates/rooch-framework/sources/ethereum_light_client.move, crates/rooch-framework/sources/timestamp.move, crates/rooch-framework/sources/transaction_validator.move, crates/rooch-framework/tests/timestamp_test.move, crates/rooch-types/src/framework/timestamp.rs, crates/rooch/src/commands/rpc/commands/request.rs, crates/testsuite/features/cmd.feature, examples/kv_store/sources/kv_store.move
Refactor timestamp
1. Rename `CurrentTimeMicroseconds` to `Timestamp`. 
2. Make Timestamp to singleton Object.
3. Change the timestamp value from microseconds to milliseconds.
Part of #1066 
TODO:
1. provide a shortcut access path for the singleton object: /object/0x3::timestamp::Timestamp.
2. Update documents #825
=> [Framework] Refactor Timestamp to object

docker/Dockerfile
resolve https://github.com/rooch-network/rooch/issues/1124
=> Fixup docker build failed due to missing sqlite lib

crates/rooch-integration-test-runner/src/lib.rs, moveos/moveos/src/vm/moveos_vm.rs
1. Use `context::publish_modules_entry` to publish modules in integration tests.
2. Skip module init functions when module is upgrading in `MoveAction::ModuleBundle` mode.
related issue: #1126
=> Skip module init when upgrading module through MoveAction::ModuleBundle

crates/rooch-framework/doc/coin_store.md, crates/rooch-framework/sources/account_coin_store.move, crates/rooch-framework/sources/coin_store.move, crates/rooch-framework/sources/tests/coin_store_test.move
Follow #1138 
1. Abort error on the `coin_store::transfer` function. We do not allow direct transfers a CoinStore to the account.
2. Optimize CoinStore event, add `Create`, `Remove`, and `Fraze` events.
Part of #1055
=> [Framework] Resolve CoinStore transfer issue

crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/testsuite/features/cmd.feature, moveos/moveos-store/src/event_store/mod.rs
1. Unify event cursor logic and treat cursor None as -1. Address the comment in #1108.
2. Implement get events without Annotated function.
=> [rpc] The event RPC treat cursor None as -1

crates/rooch-rpc-api/src/api/eth_api.rs, crates/rooch-rpc-server/src/server/eth_server.rs
Add eth_getCode method to the eth rpc server. for now, It just returns "0x"
- Closes #1092
=> add `getCode` eth rpc server method

Cargo.lock, crates/rooch-framework/src/natives/gas_parameter/json.rs, crates/rooch-framework/src/natives/gas_parameter/mod.rs, crates/rooch-framework/src/natives/mod.rs, moveos/moveos-stdlib/Cargo.toml, moveos/moveos-stdlib/moveos-stdlib/doc/README.md, moveos/moveos-stdlib/moveos-stdlib/doc/json.md, moveos/moveos-stdlib/moveos-stdlib/sources/json.move, moveos/moveos-stdlib/src/natives/mod.rs, moveos/moveos-stdlib/src/natives/moveos_stdlib/json.rs, moveos/moveos-stdlib/src/natives/moveos_stdlib/mod.rs
Add `json::from_json<T>(str: vector<u8>)` to decode json str to move struct.
- Closes #991
=> Parse json to move struct

Cargo.lock, Cargo.toml, crates/rooch-framework-tests/src/tests/mod.rs, crates/rooch-framework-tests/src/tests/ord_test.rs, crates/rooch-framework/Cargo.toml, crates/rooch-framework/doc/README.md, crates/rooch-framework/doc/bitcoin_types.md, crates/rooch-framework/doc/ord.md, crates/rooch-framework/sources/bitcoin_types.move, crates/rooch-framework/sources/ord.move, crates/rooch-framework/src/natives/gas_parameter/mod.rs, crates/rooch-framework/src/natives/gas_parameter/ord.rs, crates/rooch-framework/src/natives/mod.rs, crates/rooch-framework/src/natives/rooch_framework/bitcoin/mod.rs, crates/rooch-framework/src/natives/rooch_framework/bitcoin/ord/envelope.rs, crates/rooch-framework/src/natives/rooch_framework/bitcoin/ord/inscription.rs, crates/rooch-framework/src/natives/rooch_framework/bitcoin/ord/inscription_id.rs, crates/rooch-framework/src/natives/rooch_framework/bitcoin/ord/media.rs, crates/rooch-framework/src/natives/rooch_framework/bitcoin/ord/mod.rs, crates/rooch-framework/src/natives/rooch_framework/bitcoin/ord/test.rs, crates/rooch-framework/src/natives/rooch_framework/mod.rs, crates/rooch-types/src/framework/bitcoin_types.rs, crates/rooch-types/src/framework/mod.rs, crates/rooch-types/src/framework/ord.rs, moveos/moveos-types/src/move_std/option.rs, moveos/moveos-types/src/state.rs
Add a native function to parse Inscription.
Part of #423 #993
=> [Bitcoin] Implement bitcoin Inscription parse in Move

Cargo.lock, crates/rooch/Cargo.toml, crates/rooch/src/main.rs, moveos/moveos-stdlib/moveos-stdlib/doc/json.md, moveos/moveos-stdlib/moveos-stdlib/sources/json.move, moveos/moveos-stdlib/src/natives/moveos_stdlib/json.rs, sdk/typescript/test/e2e/sdk.test.ts
1. `json::from_json` support string type.
2. Implement `json::to_map` for uncertain field json object parse.
=> [moveos_std] Implement json::to_map

crates/rooch-framework-tests/src/tests/ord_test.rs, crates/rooch-framework/doc/README.md, crates/rooch-framework/doc/brc20.md, crates/rooch-framework/doc/genesis.md, crates/rooch-framework/doc/ord.md, crates/rooch-framework/sources/brc20.move, crates/rooch-framework/sources/genesis.move, crates/rooch-framework/sources/ord.move, crates/rooch-indexer/src/store/sqlite_store.rs, crates/rooch-relayer/src/actor/bitcoin_relayer.rs, crates/rooch-types/src/framework/brc20.rs, crates/rooch-types/src/framework/mod.rs, crates/rooch-types/src/framework/ord.rs, moveos/moveos-stdlib/moveos-stdlib/doc/README.md, moveos/moveos-stdlib/moveos-stdlib/doc/json.md, moveos/moveos-stdlib/moveos-stdlib/doc/simple_map.md, moveos/moveos-stdlib/moveos-stdlib/doc/string_utils.md, moveos/moveos-stdlib/moveos-stdlib/sources/json.move, moveos/moveos-stdlib/moveos-stdlib/sources/simple_map.move, moveos/moveos-stdlib/moveos-stdlib/sources/string_utils.move, moveos/moveos-stdlib/src/natives/moveos_stdlib/json.rs
1. [moveos_std] Implement string_utils for parse number from string.
2. [moveos_std] Support `json::from_json_option` and `json::to_map` do not abort when invalid json.
part of #993 #997 
TODO:
1. get sender and receiver and record brc20 balance
=> [Bitcoin] Implement brc20 progress

kube/runner/Dockerfile, kube/runner/runner.yaml
fix action runner docker start failed 
ref: https://github.com/actions/actions-runner-controller/issues/2143#issuecomment-137923367
=> use iptables-legacy instead, to fix the docker problem

crates/rooch-framework-tests/src/tests/bitcoin_light_client_test.rs, crates/rooch-types/src/bitcoin/ord.rs, frameworks/bitcoin-move/doc/brc20.md, frameworks/bitcoin-move/doc/ord.md, frameworks/bitcoin-move/sources/brc20.move, frameworks/bitcoin-move/sources/ord.move, frameworks/bitcoin-move/src/natives/ord/inscription.rs, frameworks/bitcoin-move/src/natives/ord/inscription_id.rs, moveos/moveos-types/src/move_std/string.rs
1. Use empty `vector<u8>` to replace `Option<vector<u8>>` in Inscription.
2. Parse Inscription fields: `content_type`,`metaprotocol`,`parent` and `pointer`.
3. Add Inscription Object test.
- Closes #1241
=> [bitcoin-move] Ord Inscription refactor

crates/rooch-framework-tests/tests/cases/data_struct/data_struct_incorrect_field.exp, crates/rooch-framework-tests/tests/cases/data_struct/data_struct_incorrect_field.move, frameworks/bitcoin-move/doc/brc20.md, frameworks/bitcoin-move/doc/ord.md, frameworks/bitcoin-move/doc/utxo.md, frameworks/bitcoin-move/sources/brc20.move, frameworks/bitcoin-move/sources/light_client.move, frameworks/bitcoin-move/sources/ord.move, frameworks/bitcoin-move/sources/utxo.move, moveos/moveos-stdlib/moveos-stdlib/doc/simple_map.md, moveos/moveos-stdlib/moveos-stdlib/doc/simple_multimap.md, moveos/moveos-stdlib/moveos-stdlib/doc/tx_context.md, moveos/moveos-stdlib/moveos-stdlib/sources/json.move, moveos/moveos-stdlib/moveos-stdlib/sources/object.move, moveos/moveos-stdlib/moveos-stdlib/sources/simple_map.move, moveos/moveos-stdlib/moveos-stdlib/sources/simple_multimap.move, moveos/moveos-stdlib/moveos-stdlib/sources/table.move, moveos/moveos-stdlib/moveos-stdlib/sources/tx_context.move, moveos/moveos-stdlib/moveos-stdlib/sources/type_table.move
1. Remove the `copy` and `drop` abilities from `SimpleMap` and `SimpleMultiMap`.
2. Support no copy and drop struct as value
=> [moveos_std] Refactor simple_map and simple_multimap, Support no copy and drop struct as value

crates/rooch-framework-tests/src/tests/brc20_test.rs, crates/rooch-framework-tests/src/tests/ord_test.rs, crates/rooch-types/src/bitcoin/brc20.rs, crates/rooch-types/src/bitcoin/ord.rs, frameworks/bitcoin-move/doc/brc20.md, frameworks/bitcoin-move/doc/genesis.md, frameworks/bitcoin-move/doc/ord.md, frameworks/bitcoin-move/doc/utxo.md, frameworks/bitcoin-move/sources/brc20.move, frameworks/bitcoin-move/sources/genesis.move, frameworks/bitcoin-move/sources/light_client.move, frameworks/bitcoin-move/sources/ord.move, frameworks/bitcoin-move/sources/utxo.move, moveos/moveos-stdlib/moveos-stdlib/doc/context.md, moveos/moveos-stdlib/moveos-stdlib/doc/simple_map.md, moveos/moveos-stdlib/moveos-stdlib/doc/simple_multimap.md, moveos/moveos-stdlib/moveos-stdlib/doc/string_utils.md, moveos/moveos-stdlib/moveos-stdlib/sources/context.move, moveos/moveos-stdlib/moveos-stdlib/sources/simple_map.move, moveos/moveos-stdlib/moveos-stdlib/sources/simple_multimap.move, moveos/moveos-stdlib/moveos-stdlib/sources/string_utils.move
1. [moveos_std] string_utils::to_lower_case and to_upper_case
1. [moveos_std] context::take_object_extend return original owner
1. [moveos_std] simple_map and simple_multimap add is_empty
1. [bitcoin] brc20 utxo transfer
follow #1197 
part of #993 
TODO:
1. Trigger the event if brc20 op is invalid and remove the debug log.
2. Record the brc20 op execution result.
=> [bitcoin] Brc20 utxo trace

crates/rooch-framework-tests/tests/cases/private_generics/mismatches_function_definition.exp, moveos/moveos-verifier/src/metadata.rs, moveos/moveos-verifier/src/verifier.rs
1. During compilation, ensure that the type information in private_generics is complete and accurate.
2. During module deployment, check if the information in the current module's metadata is correct; otherwise, halt the deployment.
=> Security enhancement for private_generics.

crates/rooch-framework-tests/src/tests/transaction_validator_tests.rs, crates/rooch-key/src/keystore/account_keystore.rs, crates/rooch-key/src/keystore/base_keystore.rs, crates/rooch-key/src/keystore/file_keystore.rs, crates/rooch-key/src/keystore/memory_keystore.rs, crates/rooch-key/src/keystore/mod.rs, crates/rooch-key/src/keystore/types.rs, crates/rooch-rpc-server/src/server/btc_server.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-types/src/address.rs, crates/rooch-types/src/framework/session_key.rs, crates/rooch-types/src/multichain_id.rs, crates/rooch/src/commands/account/commands/list.rs, crates/rooch/src/commands/session_key/commands/create.rs, moveos/moveos-types/src/move_std/ascii.rs
1. Record local address mapping to keystore.
2. `account list` command prints multichain_address and only session key address.
3. Refactor `MultiChainAddress` to_string format: `eth:0xa...bc`,`bitcoin:1p..abc`
part of #622 and #1258
=> [cli] Support local address mapping

crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/actor/reader_executor.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-framework-tests/src/binding_test.rs, crates/rooch-framework-tests/src/tests/bitcoin_light_client_test.rs, crates/rooch-indexer/src/actor/indexer.rs, crates/rooch-indexer/src/actor/mod.rs, crates/rooch-indexer/src/actor/reader_indexer.rs, crates/rooch-indexer/src/proxy/mod.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/jsonrpc_types/btc/utxo.rs, crates/rooch-rpc-api/src/jsonrpc_types/execute_tx_response.rs, crates/rooch-rpc-server/src/lib.rs, crates/rooch-rpc-server/src/service/aggregate_service.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch-types/src/bitcoin/utxo.rs, moveos/moveos-store/src/state_store/statedb.rs, moveos/moveos-types/src/transaction.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/moveos_vm.rs, moveos/smt/src/lib.rs
Follow up https://github.com/rooch-network/rooch/pull/1281
1. The read-write lock of moveos in Executor is removed, and the Reader Executor state is refreshed through Writer Executor message passing.
2. If the transaction is to upgrade the module, the Reader Executor needs to reset the loader cache in movevm
3. There is a case when rooch bitcoin relayer synchronizes the bitcoin node data and processes the `process_block` in the contract, this process takes some time, and the object id in the Global state is deleted, but the object id in the Indexer is not deleted yet. At this time, utxo is empty.
=> Pass writer executor state to reader executor and verify

crates/rooch-key/src/keystore/types.rs, crates/rooch/src/commands/account/commands/list.rs, sdk/typescript/rooch-sdk/src/account/account.ts, sdk/typescript/rooch-sdk/src/account/interface.ts, sdk/typescript/rooch-sdk/src/types/rooch.ts, sdk/typescript/rooch-sdk/src/utils/encode.test.ts, sdk/typescript/rooch-sdk/src/utils/encode.ts, sdk/typescript/rooch-sdk/src/utils/tx.test.ts, sdk/typescript/rooch-sdk/src/utils/tx.ts, sdk/typescript/rooch-sdk/test/e2e/cli/rooch-cli.ts, sdk/typescript/rooch-sdk/test/e2e/debug.test.ts, sdk/typescript/rooch-sdk/test/e2e/sdk.test.ts, sdk/typescript/rooch-sdk/test/e2e/servers/rooch-server.ts
rooch-sdk callData supports Object, ObjectID and Raw types.
https://github.com/rooch-network/rooch/issues/1288
=> Feature owen sdk support object type

.github/workflows/docker_build.yml
secrets replacement in GitHub actions happens before execution. It's ok to use '<da_option>' to pass json string which needs value in secrets
=> fix(workflow): fix da options

crates/rooch-benchmarks/benches/bench_tx_write.rs
after fix link error, the execution process working as expect:
```
RUST_LOG=error cargo bench --bench bench_tx_write
Compiling rooch-benchmarks v0.1.0 (/Users/templex/rooch/bodhi/rooch/crates/rooch-benchmarks)
Finished bench [optimized + debuginfo] target(s) in 13.62s
Running benches/bench_tx_write.rs (/Users/templex/rooch/bodhi/rooch/target/release/deps/bench_tx_write-624c3ac78421ba7f)
INCLUDING DEPENDENCY MoveStdlib
INCLUDING DEPENDENCY MoveosStdlib
INCLUDING DEPENDENCY RoochFramework
BUILDING simple_blog
execute_tx              time:   [5.5210 ms 6.0733 ms 6.3923 ms]
change: [-12.752% -2.5564% +8.6448%] (p = 0.66 > 0.05)
No change in performance detected.
```
the avg TPS is about ~150 in tx_write_bench
=> ci: fix link error in bench

Cargo.lock, crates/rooch-benchmarks/Cargo.toml, crates/rooch-benchmarks/benches/bench_tx_write.rs, crates/rooch-benchmarks/src/tx.rs
no significant improvement found:
```
RUST_LOG=error PUREMEM=/Volumes/RAMDisk/rtmp cargo bench --bench bench_tx_write
...
execute_tx              time:   [5.1027 ms 5.6767 ms 5.9972 ms]
change: [-13.073% -0.8050% +12.977%] (p = 0.91 > 0.05)
No change in performance detected.
```
- Closes #1395
=> ci: add pure mem filesystem for bench

Cargo.lock, Cargo.toml, crates/rooch-framework-tests/tests/cases/language/reference_test.exp, crates/rooch-framework-tests/tests/cases/language/reference_test.move, crates/rooch-framework-tests/tests/cases/object/borrow_two_reference.exp, crates/rooch-framework-tests/tests/cases/object/borrow_two_reference.move, crates/rooch-framework-tests/tests/cases/object/reference.exp, crates/rooch-framework-tests/tests/cases/object/reference.move, crates/rooch-types/Cargo.toml, crates/rooch-types/src/multichain_id.rs, moveos/moveos-stdlib/moveos-stdlib/doc/object.md, moveos/moveos-stdlib/moveos-stdlib/sources/object.move, moveos/moveos-stdlib/src/natives/moveos_stdlib/object.rs, moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs, moveos/moveos-types/src/moveos_std/object_id.rs, moveos/moveos-types/src/state.rs
Check the Object reference count runtime
1. Count the Object reference count and forbid two references from the same object.
2. Refactor the `to_runtime_value` and `from_runtime_value` trait
TODO:
1. Increment the reference count when passing Object reference from the arguments.
=> Check the Object reference count runtime

crates/rooch-framework/sources/coin.move, examples/btc_holder_coin/Move.toml, examples/btc_holder_coin/README.md, examples/btc_holder_coin/sources/holder_coin.move, frameworks/bitcoin-move/sources/utxo.move
This example demonstrates how to use the `atomic binding` feature to issue a new token to the holder of BTC.
Follow #1449 Part of #1429
=> [Example] Implement a BTC holder coin example

kube/runner/runner.yaml
It turns out the reason was the runner disk size, now fixed.
=> fix the check build test workflow

moveos/moveos-stdlib/moveos-stdlib/sources/object.move, moveos/moveos-stdlib/moveos-stdlib/tests/bag_tests.move, moveos/moveos-stdlib/src/natives/moveos_stdlib/object.rs, moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs
When calling `object::borrow_field`, if object_id or table key is not exists, aborts with code `ErrorNotFound`; if expected value type is not matched, aborts with `ErrorTypeMismatch`.
FIX related testcases.
=> Distinguish between not found and type mismatch for object field borrowing.

crates/rooch-indexer/src/actor/indexer.rs, crates/rooch-indexer/src/tests/test_indexer.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs, crates/rooch-types/src/test_utils.rs, crates/testsuite/features/cmd.feature, examples/basic_object/sources/child_object.move, moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs, moveos/moveos-store/src/state_store/statedb.rs, moveos/moveos-store/src/tests/test_state_store.rs, moveos/moveos-types/src/state.rs, moveos/moveos/src/vm/data_cache.rs
Follow #1466 
The indexer supports the child object and puts all children in the global states table.
TODO:
1. Refactor the ChangeSet to fix the child object dynamic field bug.
2. Rename global_states table to object_states table, and table_states table to field_states table.
=> [indexer] Indexer support child object

moveos/moveos-verifier/src/metadata.rs
For security reasons, we let the get_metadata_from_compiled_module() never return None.
=> get_metadata_from_compiled_module() never return None

crates/rooch-executor/src/actor/executor.rs, crates/rooch-indexer/src/types.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-sequencer/src/actor/sequencer.rs, crates/rooch-store/src/transaction_store/mod.rs, crates/rooch-types/src/transaction/ledger_transaction.rs, crates/rooch-types/src/transaction/rooch.rs
1. saving redundant calculation
1. change struct of RoochTransaction, the result of serilization changed
2. mut tx
1. outside cache with limit @jolestar
=> feat(tx): cache data_hash for RoochTransaction

Cargo.toml
Switched Link Time Optimization (LTO) from 'true' to 'thin' to optimize the speed of the build while retaining the benefits of LTO. A new `bench` profile has been added to aid in performance testing and benchmarking activities
=> chore: Optimize Link Time Optimization (LTO) and add benchmarking profile

crates/rooch-relayer/src/actor/bitcoin_relayer.rs, crates/rooch-types/src/into_address.rs, frameworks/bitcoin-move/sources/light_client.move, frameworks/bitcoin-move/sources/ord.move
1. Allow transfer and inscribe at the same transaction.
2. Confirm batch inscribe logic is correct handling.
There are three modes for Inscribe: SameSat, SeparateOutputs, SharedOutput
SameSat and SharedOutput mode have only one output.
When SeparateOutputs is used, the number of output and inscription is consistent.
=> [Bitcoin] Refine inscribe inscriptions flow

crates/rooch-benchmarks/benches/bench_tx_query.rs, crates/rooch-benchmarks/benches/bench_tx_sequence.rs, crates/rooch-benchmarks/src/tx.rs, crates/rooch-test-transaction-builder/src/lib.rs, scripts/pr.sh
for origin one, the --benches arguments cannot cover rooch-benchmarks may caused by
```
[lib]
bench = false
```
setting in rooch-benchmarks/Cargo.toml
I add the checking manually and fix clippy warnings
=> ci(bench): add bench code files into ci lint checking

crates/rooch-benchmarks/benches/bench_utils.rs
This commit refines the benchmarks for 'bcs serialized size' by making the benchmark function take function values as inputs. This is done by redefining the benchmark function to take a vector of function containers as parameter, which allows different evaluation functions to be passed in as arguments. It provides a more flexible way to perform benchmarks and measure different aspects of the encoding and serializing processes:
```
bcs_serialized_size/serialized_size
time:   [5.4677 ns 5.4749 ns 5.4862 ns]
change: [-0.9429% -0.4567% +0.0422%] (p = 0.11 > 0.05)
No change in performance detected.
Found 2 outliers among 10 measurements (20.00%)
2 (20.00%) high mild
bcs_serialized_size/encode_size
time:   [33.733 ns 33.749 ns 33.763 ns]
change: [-1.1451% -1.0485% -0.9064%] (p = 0.00 < 0.05) …
```
=> ci(bench): refine bcs serialized size bench by passing function as put values

frameworks/moveos-stdlib/doc/address.md, frameworks/moveos-stdlib/doc/big_vector.md, frameworks/moveos-stdlib/sources/address.move, frameworks/moveos-stdlib/sources/big_vector.move, frameworks/rooch-framework/sources/tests/transfer_test.move
=> chore: fix some typos in comments

moveos/moveos-store/src/state_store/mod.rs, moveos/moveos-store/src/tests/test_store.rs, moveos/raw-store/src/lib.rs, moveos/raw-store/src/rocks/mod.rs, moveos/raw-store/src/traits.rs, moveos/smt/src/jellyfish_merkle/tree_cache/tree_cache_test.rs, moveos/smt/src/smt_object.rs
Refactor smt node store directly using raw store API, eliminate unnecessary `bcs::to_bytes.`
The SMTObject can not eliminate, because the `State` is `Vec<u8> + TypeTag`.
=> [statedb] Refactor smt raw store

examples/bitcoin_plants/Move.toml, examples/bitcoin_plants/sources/plants.move, frameworks/bitcoin-move/doc/ord.md, frameworks/bitcoin-move/doc/utxo.md, frameworks/bitcoin-move/sources/ord.move, frameworks/bitcoin-move/sources/utxo.move
1. Add permanent_area for `bitcoin_move::ord::Inscription`
2. Add an incomplete example `bitcoin_plants`(#1214 ) which use the permanent area.
=> Add permanent area for Inscription.

docs/website/pages/build/getting-started/installation.en-US.mdx, docs/website/pages/build/getting-started/installation.zh-CN.mdx, docs/website/pages/learn/core-concepts/move-contracts/built-in-library.en-US.mdx, docs/website/pages/learn/core-concepts/move-contracts/built-in-library.zh-CN.mdx
1.fix links
2. I met the problem `note: ld.lld: error: unable to find library -lsqlite3` when I run `cargo build`. 
So I add the `libsqlite3-dev` to dependencies.
=> docs: fix links in Rooch's built-in library page and add dependencies at Installation page

crates/rooch-rpc-client/src/wallet_context.rs, crates/rooch/src/cli_types.rs, crates/rooch/src/commands/account/commands/nullify.rs, crates/rooch/src/commands/move_cli/commands/framework_upgrade.rs, crates/rooch/src/commands/move_cli/commands/publish.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, crates/rooch/src/commands/session_key/commands/create.rs, moveos/moveos-types/src/gas_config.rs
Example:
```
rooch move run --help
...
--max-gas-amount <MAX_GAS_AMOUNT>
Custom the transaction's gas limit. [default: 1_000_000_000] [alias: "gas-limit"]
...
```
Usage:
`rooch move run --function 0xa::quick_start_counter::increase --sender-account default --gas-limit 2000000000`
or
`rooch move run --function 0xa::quick_start_counter::increase --sender-account default --max-gas-amount 2000000000`
Support:
`rooch move run`
`rooch move publish`
`rooch move framework-upgrade`
`rooch session-key create`
issue: #1257
=> [CLI] Add --gas-limit option

docs/website/theme.config.tsx
Uupdate Rooch website SEO settings
=> feat: update Rooch website SEO settings

crates/rooch-rpc-server/src/service/rpc_service.rs
```
rooch move view --function 0x3::noexist_module::noexist_function
Module does not exist error: noexist_module
```
#1004
=> [bug] Check the module is exist before execute the view function

moveos/moveos-verifier/src/metadata.rs
Closes [https://github.com/rooch-network/rooch/issues/1495](https://github.com/rooch-network/rooch/issues/1495)
=> Fix the random test failed problem.

Cargo.lock, crates/rooch-indexer/src/indexer_reader.rs, crates/rooch-indexer/src/models/states.rs, crates/rooch-indexer/src/tests/test_indexer.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/api/rooch_api.rs, crates/rooch-rpc-api/src/jsonrpc_types/btc/ord.rs, crates/rooch-rpc-api/src/jsonrpc_types/btc/utxo.rs, crates/rooch-rpc-api/src/jsonrpc_types/rpc_options.rs, crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-types/src/indexer/state.rs, crates/testsuite/features/cmd.feature, moveos/moveos-types/Cargo.toml, moveos/moveos-types/src/moveos_std/display.rs, moveos/moveos-types/src/moveos_std/object.rs
1. Unify `QueryOptions` parameter for `query_object_states`, `query_transactions`, `query_events`, `query_field_states`. This may break clients which called these apis.
2. `query_object_states` support return display fields of objects.
@wow-sven
=> Show display fields of object states from indexer

crates/rooch-indexer/migrations/2023-10-31-085226_transactions/up.sql, crates/rooch-indexer/src/models/transactions.rs, crates/rooch-indexer/src/schema.rs, crates/rooch-indexer/src/types.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-pipeline-processor/src/actor/processor.rs, crates/rooch-rpc-api/src/jsonrpc_types/execute_tx_response.rs, crates/rooch-sequencer/src/actor/sequencer.rs, crates/rooch-types/src/crypto.rs, crates/rooch-types/src/error.rs, crates/rooch-types/src/test_utils.rs, crates/rooch-types/src/transaction/mod.rs, crates/testsuite/features/cmd.feature, frameworks/bitcoin-move/doc/bitcoin.md, frameworks/bitcoin-move/sources/bitcoin.move, frameworks/rooch-framework/doc/README.md, frameworks/rooch-framework/doc/timestamp.md, frameworks/rooch-framework/doc/transaction.md, frameworks/rooch-framework/doc/transaction_validator.md, frameworks/rooch-framework/sources/timestamp.move, frameworks/rooch-framework/sources/transaction.move, frameworks/rooch-framework/sources/transaction_validator.move
1. Add `tx_timestamp` to `TransactionSequenceInfo`.
2. Add `TransactionSequenceInfo` to `TxContext`.
3. Update the timestamp in `pre_execute`.
4. Refactor `TransactionSequenceInfo`, change `tx_signature` to `Vec<u8>`.
5. Refactor `crypto.rs,` define `SignatureScheme,` and replace ` BuiltinAuthValidator.`
- Closes #1507
=> [sequencer] Add sequencer timestamp to TransactinoInfo and update timestamp

Cargo.lock, Cargo.toml, frameworks/moveos-stdlib/Cargo.toml, frameworks/moveos-stdlib/doc/evm.md, frameworks/moveos-stdlib/sources/evm.move, frameworks/moveos-stdlib/src/natives/moveos_stdlib/evm.rs, frameworks/rooch-framework/src/natives/gas_parameter/evm.rs
=> [moveos_std] Complete evm precompiled functions

crates/rooch-key/src/key_derive.rs, crates/rooch-key/src/keystore/memory_keystore.rs
Use the BIP86 as the private key derivation path purpose. follow #1674
=> [keystore] Use the BIP86 as the private key derivation path purpose

.github/workflows/deploy_testnet.yml
Under https://docs.github.com/en/rest/releases/releases#create-a-release there is
```
prerelease boolean
true to identify the release as a prerelease. false to identify the release as a full release.
Default: false
```
=> deploy both release and prerelease to testnet seed

frameworks/moveos-stdlib/doc/module_store.md, frameworks/moveos-stdlib/sources/module_store.move
Part of #704 
Add Upgrade policy of package, and support freezeing package.
=> Support freeze package upgrading

crates/rooch-benchmarks/benches/bench_tx_sequence.rs, crates/rooch-benchmarks/benches/bench_tx_validate.rs, crates/rooch-benchmarks/src/tx.rs, crates/rooch-benchmarks/src/tx_exec.rs, crates/rooch-framework-tests/src/binding_test.rs, crates/rooch-test-transaction-builder/src/lib.rs, crates/rooch-types/src/transaction/authenticator.rs, crates/rooch-types/src/transaction/rooch.rs, moveos/moveos-types/src/state_resolver.rs
1. Add some methods to simplify the RoochTransaction build from RoochTransactionData.
2. Fix and refactor the bench
=> [bench] Fix and refactor the bench

Cargo.lock, Cargo.toml
This PR will bump OpenDAL to 0.47.0, removing some old dependences in our tree.
=> chore: Bump OpenDAL to 0.47.0

infra/rooch-portal/package.json, infra/rooch-portal/src/pages/transactions/components/transactions-table.tsx, infra/rooch-portal/vite.config.ts, package.json, pnpm-lock.yaml
Resolve #1790 
Fix the `undefined buffer` bug
=> chore: fix #1790

crates/rooch/src/commands/account/mod.rs, crates/rooch/src/commands/move_cli/commands/build.rs, crates/rooch/src/commands/move_cli/commands/coverage.rs, crates/rooch/src/commands/move_cli/commands/disassemble.rs, crates/rooch/src/commands/move_cli/commands/docgen.rs, crates/rooch/src/commands/move_cli/commands/errmap.rs, crates/rooch/src/commands/move_cli/commands/explain.rs, crates/rooch/src/commands/move_cli/commands/info.rs, crates/rooch/src/commands/move_cli/commands/integration_test.rs, crates/rooch/src/commands/move_cli/commands/mod.rs, crates/rooch/src/commands/move_cli/commands/new.rs, crates/rooch/src/commands/move_cli/commands/prove.rs, crates/rooch/src/commands/move_cli/commands/unit_test.rs, crates/rooch/src/commands/move_cli/mod.rs
-  #1803
```
{
"Result": "Success"
}
```
Just enable "success" in the JSON output.
=> [CLI] `rooch move` success json output

crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs, crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs, crates/rooch-rpc-api/src/jsonrpc_types/transaction_view.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-types/src/transaction/ledger_transaction.rs
=> RPC: Output bitcoin address for transaction and object

crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs, crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs, crates/rooch-rpc-api/src/jsonrpc_types/str_view.rs, crates/rooch/src/commands/rpc/commands/request.rs, crates/testsuite/features/cmd.feature, moveos/moveos-types/src/moveos_std/object.rs
Beautify `rooch rpc request` cli output in default. And output json format with `--json` option. For now, only method `rooch_getObjectStates` and `rooch_queryObjectStates` output are beautified.
Part of #1803
TODO:
=> Beautify `rooch rpc request` cli output, and support `json` mode.

crates/testsuite/features/cmd.feature, frameworks/bitcoin-move/doc/README.md, frameworks/bitcoin-move/doc/bitcoin.md, frameworks/bitcoin-move/doc/genesis.md, frameworks/bitcoin-move/doc/pending_block.md, frameworks/bitcoin-move/doc/types.md, frameworks/bitcoin-move/sources/bitcoin.move, frameworks/bitcoin-move/sources/genesis.move, frameworks/bitcoin-move/sources/pending_block.move, frameworks/bitcoin-move/sources/types.move
Introduce pending block and handle reorg.
part of #1685 
TODO
1. Refactor the relayer and confirm the L1 tx in the new transaction.
2. Add more tests to reorg.
=> [bitcoin] Introduce pending block and handle reorg

crates/rooch-benchmarks/src/tx_exec.rs, crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-framework-tests/src/binding_test.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-pipeline-processor/src/actor/messages.rs, crates/rooch-pipeline-processor/src/actor/processor.rs, crates/rooch-pipeline-processor/src/proxy/mod.rs, crates/rooch-relayer/src/actor/relayer.rs, crates/rooch-rpc-api/src/jsonrpc_types/transaction_view.rs, crates/rooch-types/src/bitcoin/mod.rs, crates/rooch-types/src/bitcoin/pending_block.rs, crates/rooch-types/src/framework/auth_validator.rs, crates/rooch-types/src/indexer/transaction.rs, crates/rooch-types/src/transaction/ledger_transaction.rs, crates/rooch-types/src/transaction/mod.rs, frameworks/bitcoin-move/doc/pending_block.md, frameworks/bitcoin-move/sources/bitcoin.move, frameworks/bitcoin-move/sources/pending_block.move
Part of #1797, follow #1901
TODO
1. Load ready l1 tx from the contract and resolve reorg.
2. Add more tests for reorg.
=> [bitcoin] Define l1_tx type and split l1_tx execution from l1_block

docs/website/components/blog/postHeader.tsx, docs/website/components/layout/footer.tsx, docs/website/pages/blog/let-us-move.en-US.mdx, docs/website/pages/blog/let-us-move.zh-CN.mdx
- [show Footer on specific url](https://github.com/rooch-network/rooch/pull/1968/commits/6f3821b13ce5914bd7170425fe3fbad6e49c514d)
- [update meta property and blog](https://github.com/rooch-network/rooch/pull/1968/commits/b03c3a534191306fb14d03602e6d7da6bbfc9253)
=> [Website] Enhancement

Cargo.lock, crates/rooch-benchmarks/Cargo.toml, crates/rooch-benchmarks/README.md, crates/rooch-benchmarks/config/bench_tx.toml, crates/rooch-benchmarks/src/config.rs, crates/rooch-benchmarks/src/tx.rs, crates/rooch-benchmarks/src/tx_exec.rs, crates/rooch-framework-tests/src/binding_test.rs, crates/rooch-framework-tests/src/tests/bitcoin_test.rs, frameworks/bitcoin-move/sources/pending_block.move
1. Fix the Bitcoin reorg condition bug
2. Auto prepare Bitcoin block and add BtcTx bench
part of #1173 
cc @yourmoonlight
=> Fix the Bitcoin reorg bug and Add BtcTx bench

Cargo.lock, crates/rooch-indexer/src/indexer_reader.rs, crates/rooch-indexer/src/lib.rs, crates/rooch-indexer/src/models/transactions.rs, crates/rooch-indexer/src/store/sqlite_store.rs, crates/rooch-indexer/src/tests/mod.rs, crates/rooch-indexer/src/tests/test_concurrence.rs, crates/rooch-indexer/src/tests/test_indexer.rs
1. Using `WAL` mode instead of a default `rollback journal` for Sqlite, to provide more concurrency as readers do not block writers and a writer does not block readers.
2. Enable `busy_timeout` config to avoid "database is locked"
3. Add concurrent read and write test cases
- Closes #1966
=> [Sqlite] Optimize Sqlite concurrent read and write mode and tune key database configs

crates/rooch-config/src/lib.rs, crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-framework-tests/src/binding_test.rs, crates/rooch-pipeline-processor/src/actor/messages.rs, crates/rooch-pipeline-processor/src/actor/processor.rs, crates/rooch-pipeline-processor/src/proxy/mod.rs, crates/rooch-relayer/src/actor/relayer.rs, crates/rooch-rpc-server/src/lib.rs, crates/rooch-types/src/framework/auth_validator.rs, crates/testsuite/features/cmd.feature, crates/testsuite/features/reorg_test.feature, crates/testsuite/tests/integration.rs, frameworks/bitcoin-move/sources/pending_block.move, frameworks/moveos-stdlib/doc/tx_context.md, frameworks/moveos-stdlib/sources/tx_context.move, frameworks/rooch-framework/sources/transaction_validator.move, moveos/moveos-types/src/moveos_std/tx_context.rs, moveos/moveos/src/moveos.rs, moveos/moveos/src/vm/moveos_vm.rs
1. Define the SystemCallTx: the tx sender is 0x0.
2. Execute l1_block and l1_tx with 0x0.
3. SystemCallTx does not execute the `pre_execute` and `post_execute` functions.
4. The SystemCallTx still meters the gas usage but does not charge a gas fee.
5. If the SystemCallTx failed, just panic(TODO record a system status, and make the system unviable.)
- Closes #1998 
TODO:
1. Should we deprecate `pre_execute_functions` and `post_execute_functions` in the MoveOSTransaction?
=> [vm]Use system address to execute L1 block and L1 tx

.github/actions/rust-setup/action.yaml, Cargo.lock, Cargo.toml, crates/rooch-indexer/src/lib.rs, crates/rooch-indexer/src/utils.rs, crates/rooch-key/src/keystore/base_keystore.rs, crates/rooch-open-rpc-macros/src/lib.rs, crates/rooch-open-rpc/src/lib.rs, moveos/moveos-types/src/moveos_std/display.rs, moveos/moveos-verifier/src/metadata.rs, moveos/moveos-verifier/src/verifier.rs, moveos/raw-store/src/rocks/mod.rs, moveos/smt/src/jellyfish_merkle/nibble_path/mod.rs, rust-toolchain.toml
SQLite does not support concurrent multiple writers. Whether it is the default journal_mode = DELETE or journal_mode = WAL, only one writer can write successfully simultaneously. The `busy timeout` support allows the writer to wait for other writers to release the lock when "database locked".
1. Adjust the `busy timeout` initialization timing, also adjust the busy timeout from 5s -> 10s and pool_size from 64 -> 16 to avoid `database is locked`
2. Upgrade the sqlite ORM lib `diesel` from 2.1.0 -> 2.2.1
3. Meanwhile, upgrade rust toolchain from 1.77.2 to 1.78.0
=> [Sqlite] Adjust busy timeout to avoid database locked

moveos/moveos-config/src/store_config.rs, moveos/raw-store/src/rocks/mod.rs
1. The configurations for block_cache_size and block_size have been updated in 'store_config.rs' for better memory management.
2. certain features related to 'blob' files are now enabled in 'rocks/mod.rs'.
- Closes #2039
=> feat(rocksdb): enable blobDB of

crates/rooch/src/commands/statedb/README.md
update the README for statedb genesis cmd to include sage details, prerequisites and reformat commands
Detailed explanation:
The README of statedb in the rooch command has been significantly updated. This includes the prerequisite for genesis-* commands, including detailed steps to set block height and prepare utxo source file. The instructions are now more detailed and provide examples. The display of commands have been reformatted for clarity. Additionally, extraneous information such as the config section has been removed.
=> docs(statedb): update the README for statedb genesis cmd

crates/rooch/src/commands/statedb/commands/genesis_ord.rs
The changes refactor the genesis_ord module by eliminating the use of a temporary directory and related functions. Instead, the logic is refactored to derive information directly, reducing complexity and potential file system overhead. This change simplifies the code structure and improves performance.
=> refactor(genesis ord): derive ord's object_id directly

Cargo.lock, Cargo.toml, crates/rooch-common/Cargo.toml, crates/rooch-common/README.md, crates/rooch-common/src/lib.rs, crates/rooch-common/src/utils/humanize.rs, crates/rooch-common/src/utils/mod.rs, crates/rooch/Cargo.toml, crates/rooch/src/commands/statedb/commands/genesis_ord.rs
This commit introduces a new 'rooch-common' crate to the workspace and that contains utility functions for the project. It includes a function for converting byte sizes to human-readable formats, which has been incorporated into the ORD update code. This will allow for clearer log messages describing the size of the batches processed.
=> feat(common): add new 'rooch-common' crate with utility functions

Cargo.lock, Cargo.toml, crates/rooch-common/Cargo.toml, crates/rooch-common/src/fs/file_cache.rs, crates/rooch-common/src/fs/mod.rs, crates/rooch/src/commands/statedb/commands/genesis_ord.rs
1.  introduces a new module, "fs", and within that module, a new "file_cache.rs" file that creates a FileCacheManager. This manager handles file caching using the std and libc libraries.
2. involves the reworking of file management in genesis_ord.rs through the integration of FileCacheManager. This new approach allows for improved file handling, including the tracking of bytes read to enable the optimization of cache dropping.
=> feat(common): add file cache manager

crates/rooch-common/src/fs/file_cache.rs
Implemented conditional logic in the FileCacheManager module where certain methods are only applicable when the target OS is Linux. Methods like `new()` and `drop_cache_range()` are now specifically designated for Linux, while others are designated otherwise. This ensures correct functioning across diverse OS.
- Closes #2075
=> fix(common): add Linux-specific file caching logic

crates/rooch/src/commands/statedb/commands/genesis_utxo.rs
The code for generating UTXO updates has been enhanced by introducing better and more robust error handling mechanisms. This update also improves the way it handles the generation of bitcoin and rooch addresses, simplifying the logic and reducing code redundancy. These changes are aimed at preventing unexpected crashes and providing clearer error messages if an issue occurs.
example:
```json
UTXOData { txid: "41a3e9ee1910a2d40dd217bbc9fd3638c40d13c8fdda8a0aa9d49a2b4a199422", vout: 2, value: 5376, script: "036c6565662c206f6e7464656b2c2067656e6965742e2e2e202020202020202020", script_type: "p2pk", address: "" }
```
=> fix(statedb-cmd): improve error handling in genesis_utxo.rs

crates/rooch/src/commands/statedb/commands/genesis_ord.rs, crates/rooch/src/commands/statedb/commands/genesis_utxo.rs
FileCacheManager has been integrated into the genesis_utxo.rs and genesis_ord.rs files. In the process of importing data, this allows for a detailed control over the memory cache, potentially enhancing performance. The respective bytes read calculations have also been optimized.
TODO: read file ahead
=> chore: refine file cache management in genesis data import

crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/api/rooch_api.rs, crates/rooch-rpc-api/src/jsonrpc_types/mod.rs, crates/rooch-rpc-api/src/jsonrpc_types/module_abi_view.rs, crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/testsuite/features/cmd.feature
1. add new RPC API `getModuleABI`
2. The ABIs of [moveos_std::display](https://github.com/rooch-network/rooch/blob/main/frameworks/moveos-stdlib/sources/display.move) as example, `rooch rpc request --method rooch_getModuleABI --params '["0x2", "display"]'`
```json
{
"address": "0x0000000000000000000000000000000000000000000000000000000000000002",
"name": "display",
"friends": [],
"functions": [
{
"name": "borrow_mut_value",
"is_entry": false,
"type_params": [
{
"constraints": []
}
],
"params": [
"&mut 0x2::object::Object<0x2::display::Display<T0>>",
"&0x1::string::String"
],
"return": [
"&mut 0x1::string::String"
]
},
{
"name": "borrow_value",
"is_entry": false,
"type_params": [
{
"constraints": []
}
],
"params": [
"&0x2::object::Object<0x2::display::Display<T0>>",
"&0x1::string::String" …
```
=> Provide API to query move module ABI

crates/rooch-key/src/keystore/account_keystore.rs, crates/rooch-key/src/keystore/base_keystore.rs, crates/rooch-key/src/keystore/file_keystore.rs, crates/rooch-key/src/keystore/memory_keystore.rs, crates/rooch-key/src/keystore/mod.rs, crates/rooch/src/commands/account/commands/create.rs
Update address data in mnemonic.
See discussion in #2022 for details.
- Closes #2022
=> [gh-2022] update address data in mnemonic data.

crates/rooch-rpc-client/src/rooch_client.rs, crates/rooch/src/commands/session_key/commands/list.rs, crates/rooch/src/commands/session_key/commands/mod.rs, crates/rooch/src/commands/session_key/mod.rs, crates/testsuite/features/cmd.feature, frameworks/rooch-framework/doc/session_key.md, frameworks/rooch-framework/sources/session_key.move
```
rooch session-key list -h
List all session keys by address
Usage: rooch session-key list [OPTIONS]
Options:
-a, --address <ADDRESS>        The account's address to list session keys, if absent, show the default active account [default: default]
--password <PASSWORD>      The key store password
--config-dir <CONFIG_DIR>  rooch config path
-h, --help                     Print help
```
=> [cli] rooch session-key list

docs/website/pages/build/getting-started/installation.en-US.mdx, docs/website/pages/build/getting-started/installation.zh-CN.mdx
solve issue #2148 , need to install `protobuf-compiler` before compiling rooch on ubuntu.
- Closes #2148
=> docs: update prerequirements for compiling rooch in docs

docs/website/pages/build/getting-started/installation.en-US.mdx, docs/website/pages/build/getting-started/installation.zh-CN.mdx
jemalloc needs cmake to compile
The following errors will occur if you do not have cmake installed.
```bash
running: cd "/code/rooch/target/debug/build/tikv-jemalloc-sys-69f431b389e09613/out/build" && "make" "-j" "16"
--- stderr
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tikv-jemalloc-sys-0.5.4+5.3.0-patched/build.rs:347:19:
failed to execute command: No such file or directory (os error 2)
```
=> docs: jemalloc needs cmake to compile

docker/DockerfileDebug, scripts/deploy_rooch.sh
updated DockerfileDebug by adding make to the list of installed packages to fix building jemalloc issue, and bumped up the RUST_VERSION environment variable to use a more current version(as same as toolchain we're using).
=> fix(docker): fix build issue caused by uninstalled tool in DockerfileDebug

scripts/bitcoin/README.md
The command for running env script seems missing "*.sh".
=> Minor Update Typo in  scripts/bitcoin/README.md

crates/rooch/src/commands/statedb/commands/genesis_ord.rs
address has been derived in inscription source for p2pk script:
The 'is_p2pk' field and corresponding logic in genesis_ord.rs have been removed. This change simplifies the solution and doesn't affect the functionality, as 'address' is directly converted into 'bitcoin_address' using BitcoinAddress::from_str method now.
=> refactor(genesis_ord): remove 'is_p2pk' field and related logic

examples/blog/README.md, examples/blog/README_CN.md
I think it should be `jq` for command line json processor in the docs, not `jp`
=> docs: update examples/blog docs

crates/rooch-types/src/bitcoin/ord.rs, crates/rooch/src/commands/statedb/commands/genesis_ord.rs
1. remove table_vec in InscriptionStore
2. combine inscription_obj_id:Inscription and sequence_number:inscription_id into signle UpdateSet of InscriptonStore
https://github.com/rooch-network/rooch/issues/1798
=> fix(genesis_ord: implement sequence_number:inscription_id as InscriptionStore's dynamic field

crates/rooch/src/cli_types.rs, crates/rooch/src/commands/account/commands/list.rs
- Add line break after entering password
before:
after:
=> [cli]Line break output after password output

crates/rooch/src/commands/statedb/commands/export.rs, crates/rooch/src/commands/statedb/commands/genesis_ord.rs, crates/rooch/src/commands/statedb/commands/genesis_utxo.rs, crates/rooch/src/commands/statedb/commands/mod.rs
```
Error: CSV error: found record with 1 fields, but the previous record has 2 fields
```
The issue was fixed by exporting `(FieldKey, ObjectState)`.
1. general init_job() used, simplifies both of the initialization of genesis jobs and export tasks
2. utilize instant time instead of system time for recording time cost
=> fix(statedb): fix export genesis error caused by object struct changes

crates/rooch-types/src/address.rs
Fix server panic when bitcoin address is empty, #2247
Still need to figure out why there's an empty bitcoin address.
=> fix server panic when bitcoin address is empty

crates/rooch/src/commands/statedb/README.md, crates/rooch/src/commands/statedb/commands/export.rs, crates/rooch/src/commands/statedb/commands/genesis.rs, crates/rooch/src/commands/statedb/commands/genesis_utxo.rs, crates/rooch/src/commands/statedb/commands/import.rs, crates/rooch/src/commands/statedb/commands/mod.rs, crates/rooch/src/commands/statedb/mod.rs
1. Refactor finish_task into finish_job for clarity and reusability in multiple contexts. Renamed GenesisOrdCommand to GenesisCommand and moved it to the genesis module to better reflect its purpose and usage.
2. Update the buffer size of mpsc sync_channel from 2 to 1 to improve synchronization efficiency. This change ensures faster message passing and reduced memory usage, contributing to better overall performance.
3. update releated readme
=> chore: refine statedb/genesis cmd

crates/rooch/src/commands/move_cli/commands/publish.rs, crates/testsuite/features/bitseed.feature, crates/testsuite/features/cmd.feature
move publish output will be like:
```shell
Publish modules to address: rooch1r9jts4m7nwprtmm0jw29849npajq6w2eu0tukvlft6shld9awzqqu5xrs6(0x1964b8577e9b8235ef6f939453d4b30f640d3959e3d7cb33e95ea17fb4bd7080)
Execution info:
status: Executed
gas used: 1990641
tx hash: 0x5172464817ffbdc5cd53efff42f1406ac18c71470e27481041c9653ea83f4fc4
state root: 0xdc64059cad1a91dd8d0966d3bf5cba03f0ac70a13bf2e47e2f934a8d98f7690d
event root: 0x8c7f0afee95e0ccf202d0094e9d9b94ca855f6e72f41a10c550dcee71dc85152
New modules:
None
Updated modules:
0x1964b8577e9b8235ef6f939453d4b30f640d3959e3d7cb33e95ea17fb4bd7080::display
```
- Closes #2238
=> Improvement the move publish output

crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/jsonrpc_types/btc/utxo.rs
```
"seals": {
"0x36e363be4405cb74d36764b7534b13e94a633d839109f12e1116f96847c5b0b9::seal::MySeal": [
"0x1135f85a7e50f391cd490dbd89a546a970baea3c298317e97d5005b99163f70e",
"0x52589f4281a61f323744215f0b2f3a10286303b1256ee6e4c94b0bb0941356b9"
],
"0x36e363be4405cb74d36764b7534b13e94a633d839109f12e1116f96847c5b0b9::seal::LockSeal": [
"0xde600111085cf6e47b2ab113deac18ab506b6107ac65ba0ce506df3c6b6a1399"
]
}
```
- Closes https://github.com/rooch-network/rooch/issues/1943
=> [rpc] UTXOView seals output as a map

crates/rooch-framework-tests/src/tests/bitcoin_test.rs, crates/rooch-framework-tests/src/tests/ord_test.rs, crates/rooch-framework-tests/tests/cases/coin_store/coin_store.move, crates/rooch-integration-test-runner/src/lib.rs, crates/rooch-types/src/bitcoin/mod.rs, docs/website/pages/build/bitcoin/programming_with_block_and_tx.en-US.mdx, docs/website/pages/build/bitcoin/programming_with_block_and_tx.zh-CN.mdx, frameworks/rooch-framework/doc/transaction_fee.md, frameworks/rooch-framework/doc/transaction_validator.md, frameworks/rooch-framework/sources/transaction_fee.move, frameworks/rooch-framework/sources/transaction_validator.move, moveos/moveos-object-runtime/src/runtime.rs, moveos/moveos/src/moveos.rs, scripts/pr.sh
Deduct the gas fee in the pre_execute function and refund in the post_execute function.
resolve #1137
TODO: #2287
=> [framework] Fix transaction fee deduct bug

examples/btc_blind_box/sources/blind_box.move
I think the function name should be `open_sale` instead of `opne_sale`
=> correct a function name in blind_box.move

crates/rooch/src/commands/statedb/commands/genesis.rs, crates/rooch/src/commands/statedb/commands/mod.rs
1. report unbount inscription when mapping outpoint:inscirptions
2. use tempdir when test
=> fix(statedb/genesis): use tempdir in testing

docs/website/pages/build/reference/sdk/typescript-sdk.en-US.mdx, docs/website/pages/build/reference/sdk/typescript-sdk.zh-CN.mdx
简体中文下SDK跳转链接出错。
改为英文. 可以正常显示，为了样式统一并且便于用户理解，建议一起删掉
=> 🔨 typescript-sdk zh-CN link error

Cargo.lock, Cargo.toml, crates/rooch/Cargo.toml, crates/rooch/build.rs, crates/rooch/src/commands/mod.rs, crates/rooch/src/commands/statedb/commands/mod.rs, crates/rooch/src/commands/version.rs, crates/rooch/src/lib.rs
1. Fix #2242 , use the latest git commit hash.
2. use vergen-git2 to generate more version info.
3. Add `rooch version` command to output more version info.
```bash
rooch version
```
```text
Date (build): 2024-07-29
Timestamp (build): 2024-07-29T07:43:15.057110152Z
Debug (cargo): true
Dependencies (cargo): anyhow 1.0.86,async-trait 0.1.81,bcs 0.1.6,bcs-ext 1.13.6,bitcoin 0.31.2,bitcoin-move 0.6.4,chrono 0.4.38,clap 4.5.11,codespan-reporting 0.11.1,csv 1.3.0,datatest-stable 0.1.1,dirs 5.0.1,fastcrypto 0.1.8,framework-builder 0.6.4,framework-release 0.6.4,framework-types 0.6.4,hex 0.4.3,itertools 0.13.0,jemallocator 0.5.4,log 0.4.22,move-binary-format 0.0.3,move-bytecode-utils 0.1.0,move-bytecode-verifier 0.1.0,move-cli 0.1.0,move-command-line-common 0.1.0,move-compiler …
```
=> [cli] Add version command to cli for more version info

infra/rooch-portal/src/components/custom-pagination.tsx
CustomPagination Adding a default herf will cause the page to make meaningless jumps as well as add # hash to the url, greatly affecting the user experience.
https://github.com/user-attachments/assets/ec519bcc-0a69-446c-9603-2fd873faf56f
https://github.com/user-attachments/assets/b85b51f5-05f3-4c2e-9324-1c817d7c420c
Affects components:
- BitcoinAssetsOrdi
- AssetsCoin
- AssetsNft
- UtxoView
The default herf=# in the test impact component is meaningless and affects the experience, if you need to jump links you can customize the herf separately in the prop.
=> 🔨 Remove Pagination's default property herf

Cargo.lock, Cargo.toml, crates/rooch-types/src/address.rs, frameworks/rooch-framework/Cargo.toml, frameworks/rooch-framework/doc/bitcoin_address.md, frameworks/rooch-framework/sources/address_type/bitcoin_address.move, frameworks/rooch-framework/src/natives/gas_parameter/bitcoin_address.rs, frameworks/rooch-framework/src/natives/rooch_framework/bitcoin_address.rs
Support multisig address and refactor current address verification with public key.
- Use MuSig2: https://conduition.io/code/musig2-crate/;
- Crate: https://docs.rs/musig2/latest/musig2/;
- Compatible with BIP-327 and BIP-340: https://github.com/bitcoin/bips/blob/master/bip-0327.mediawiki, https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki.
- Closes #2295
=> [gh-2295] support bitcoin multisig address 

infra/rooch-portal/src/pages/transactions/list.tsx
fix issues: https://github.com/rooch-network/rooch/issues/2248
1. Transactions with too many page numbers will lead to abnormal display, both pc and mobile will be abnormal, greatly affecting the user experience.
2. When there is no page number, the default display will also show the ellipsis.
3. Previous will be displayed on the first page.
- Hide Previous button if it is the first page, hide Next button if it is the last page.
- Fix page number display, if there are too many page numbers, use ...... Omit the middle part
- User can modify the number of pages displayed on a single page directly
- The current strategy is defalut liimt to 10000000 to get all data, we need to provide new query api to support querying all data of transactions, and add HasPrevious data in result.
=> 🔨Issues #2248 fix transaction pages

crates/rooch-types/src/rooch_key.rs
When use  `rooch account import --secretkey` import account , use hex decode to secret_key.
- Closes #2327
=> parse hex secret_key

frameworks/moveos-stdlib/doc/simple_map.md, frameworks/moveos-stdlib/sources/simple_map.move, frameworks/rooch-nursery/sources/bitseed.move, frameworks/rooch-nursery/sources/inscribe_factory.move
I added `copy` and `drop` abilities to SimpleMap in #2197, But it can not upgrade the framework.
This PR rollback changes, we need to figure out:
1. Why did the compatibility checks not find this issue when building the framework?
2. How to add `ability` to container types like SimpleMap.
=> [framework] Remove copy and drop ability from SimpleMap

docker/Dockerfile, docker/DockerfileDebug
1.1.1f-1ubuntu2.22 is not found.
Upgraded libssl1.1 from 1.1.1f-1ubuntu2.22 to 1.1.1f-1ubuntu2.23 in Dockerfile and DockerfileDebug. This ensures the latest security patches and fixes are included in the build environment.
=> fix(docker): Update OpenSSL to version 1.1.1f-1ubuntu2.23

crates/rooch-rpc-api/src/jsonrpc_types/event_view.rs, crates/rooch-rpc-api/src/jsonrpc_types/execute_tx_response.rs, crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs, crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs, crates/rooch-rpc-api/src/jsonrpc_types/str_view.rs, crates/rooch/src/commands/move_cli/commands/publish.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, crates/rooch/src/commands/rpc/commands/request.rs, crates/testsuite/features/bitcoin.feature, crates/testsuite/features/bitseed.feature, crates/testsuite/features/cmd.feature
1. Add object changes in `move publish` CLI output. Related: #2270, #2238. Now `move publish` output is like the following:
```
Publish modules to address: rooch17xuf07d62j99qlf5lz2gxljt0puz9a8mef0srst942n5nw80zhssl0l08v(0xf1b897f9ba548a507d34f894837e4b787822f4fbca5f01c165aaa749b8ef15e1)
Execution info:
status: Executed
gas used: 1108806
tx hash: 0x81f587d2073a1a65da9df8a74b6f28d8e2d7ad02a90a85041417c386cd568f59
state root: 0x8ba6b3611c9b63400c6314012480fd1383e5eda51b12dfbaf69cf48bd52af283
event root: 0x90b31cd6a66d009d4edaea5429822de6e454cab48f56352b9931bc25accf5ed9
New modules:
None
Updated modules:
0xf1b897f9ba548a507d34f894837e4b787822f4fbca5f01c165aaa749b8ef15e1::display
New objects:
None
Modified objects:
objectId: 0x0ab37084cb15b8a863253b0c5c555c877a6e5185e93c16b7ec2156b278f18fd1 …
```
=> pretty move run and move publish output

Cargo.lock, crates/rooch/Cargo.toml, crates/rooch/src/commands/statedb/README.md, crates/rooch/src/commands/statedb/commands/genesis.rs, crates/rooch/src/commands/statedb/commands/genesis_verify.rs, crates/rooch/src/commands/statedb/commands/mod.rs, crates/rooch/src/commands/statedb/mod.rs
Introduce `GenesisVerifyCommand` to enable verification of BTC ordinals and UTXO for genesis. This feature includes new CLI options, file processing structures, and concurrent execution for efficiency. Additionally, update `Cargo.toml` to add necessary dependencies and adjust existing genesis-related command implementations.
- Closes #2336
=> feat(statedb): add GenesisVerifyCommand and associated capability

crates/rooch-indexer/src/indexer_reader.rs, crates/rooch-indexer/src/lib.rs
part of #2366
1. Optimize cache_size from default 2MB to 64 MB per connection
2. Enable memory-mapped I/O for query, set mmap size to 256MB per database
3. Adjust indexer reader connections from 16 to 32 per database.
=> [Indexer] Optimize indexer query cache and pool core config

crates/rooch-genesis/src/lib.rs
Only check genesis state_root when the server start, because the GenesisPackage hash is changed in #2297
=> [genesis] Only check genesis state_root when server start

crates/rooch/src/commands/indexer/commands/rebuild.rs, crates/rooch/src/commands/statedb/commands/export.rs, crates/rooch/src/commands/statedb/commands/genesis.rs, crates/rooch/src/commands/statedb/commands/genesis_utxo.rs, crates/rooch/src/commands/statedb/commands/import.rs
1. Export ExportID for root
2. Export UXTO & Inscription Store object
3. Export top-level fields of UTXO & Inscription Store(both of them only have top-level fields)
For fast recovery data, refactor later
=> fix(statedb-export): fix export indexer cmd

docs/website/pages/build/tutorial/move-examples.en-US.mdx, docs/website/pages/build/tutorial/move-examples.zh-CN.mdx
两行命令 `rooch move` 都写反啦
- Closes #issue2376
=> docs : fix pages' command mistakes

crates/rooch-executor/src/actor/executor.rs, crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-integration-test-runner/src/lib.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-pipeline-processor/src/actor/processor.rs, crates/rooch-rpc-api/src/api/rooch_api.rs, crates/rooch-rpc-api/src/jsonrpc_types/execute_tx_response.rs, crates/rooch-rpc-client/src/rooch_client.rs, crates/rooch-rpc-client/src/wallet_context.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch-types/src/error.rs, crates/rooch-types/src/transaction/rooch.rs, crates/rooch/src/commands/move_cli/commands/publish.rs, moveos/moveos-types/src/transaction.rs, moveos/moveos/src/moveos.rs
**When publishing the module, perform a dry run. If an error occurs, stop and report the following error:**
Transaction dry run failed: "VMError with status ABORTED with sub status 6789 at location Module ModuleId { address: 285529d7fd13ffcda9d89cd250b4025ba9226c0e2e57f5ca3d739cb236dc259d, name: Identifier(\"counter\") } and message 0x285529d7fd13ffcda9d89cd250b4025ba9226c0e2e57f5ca3d739cb236dc259d::counter::f5 at offset 1 at code offset 1 in function definition 4"
CallStack trace:
0 0x285529d7fd13ffcda9d89cd250b4025ba9226c0e2e57f5ca3d739cb236dc259d::counter::f4.0
1 0x285529d7fd13ffcda9d89cd250b4025ba9226c0e2e57f5ca3d739cb236dc259d::counter::f3.0
2 0x285529d7fd13ffcda9d89cd250b4025ba9226c0e2e57f5ca3d739cb236dc259d::counter::f2.0
3 …
=> Implementation of transaction dry run

moveos/moveos-types/src/move_std/string.rs
=> fix: Display vector byte if movestring can't format to utf8

crates/rooch-common/src/fs/file_cache.rs, crates/rooch-indexer/src/indexer_reader.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/jsonrpc_types/event_view.rs, crates/rooch-rpc-api/src/jsonrpc_types/rpc_options.rs, crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch-types/src/indexer/event.rs, crates/rooch-types/src/indexer/state.rs, crates/rooch/src/commands/object.rs, crates/rooch/src/commands/statedb/commands/genesis_utxo.rs
1. Support query event by event type and sender, and the query can use sqlite index
2. Migrate `filter_out` from ObjectStateFilterView::ObjectTypeWithOwner to QueryOptions, eliminate the restriction of forcing filter_out to be passed in ObjectStateFilterView::ObjectTypeWithOwner
TODO:
QueryOptions uses camelCase for serialization, and some parameters use snake_case for parameter passing. Should we unify them?
- Closes #2404
=> [Indexer] Support query event by event type and sender

frameworks/rooch-nursery/doc/result.md, frameworks/rooch-nursery/doc/tick_info.md, frameworks/rooch-nursery/sources/inscribe_factory.move, frameworks/rooch-nursery/sources/result.move, frameworks/rooch-nursery/sources/tick_info.move, frameworks/rooch-nursery/tests/result_tests.move
Follow #2197, refactor `Result<T>` to `Result<T, E>`, and allow any type as the error type.
cc @yubing744
=> [framework] Refactor result, make the error as generics

crates/rooch/src/commands/statedb/commands/genesis_verify.rs
Enhanced the GenesisVerifyCommand to handle specific UTXO and inscription cases by adding new path options. Introduced `UTXOCases` and `OrdCases` structs to manage these cases and updated verification functions to use these case lists.
=> chore: add verification for specific UTXO and inscription cases in genesis-verify process

crates/rooch-rpc-api/src/jsonrpc_types/account_sign_view.rs, crates/rooch-rpc-api/src/jsonrpc_types/mod.rs, crates/rooch/src/commands/account/commands/mod.rs, crates/rooch/src/commands/account/commands/sign.rs, crates/rooch/src/commands/account/mod.rs
Add rooch account sign command
=> Add rooch account sign command

crates/rooch/src/commands/statedb/commands/export.rs, crates/rooch/src/commands/statedb/commands/genesis_verify.rs, crates/rooch/src/commands/statedb/commands/mod.rs
original way is getting FieldKey, ObjectState from Iter generated by Object's StateRoot.
In this PR, generate data from source files directly just like what we've done in statedb/genesis. 
Result:
230G(output for indexer)
+100x faster: 
1. Oringal: 55hours+ (never finished yet, ~600s/1M fields, 180M utxo+ 78M inscription+78M inscription_id)
2. Present:  1757s
Test:
I've checked output written by these way approach, all matched for data set.
=> feat(statedb/export): export indexer from source file directly

Cargo.lock, crates/rooch-benchmarks/Cargo.toml, crates/rooch-benchmarks/benches/bench_indexer.rs, crates/rooch-benchmarks/benches/bench_smt.rs, crates/rooch-benchmarks/benches/bench_tx_sequence.rs, crates/rooch-benchmarks/benches/bench_tx_validate.rs, crates/rooch-benchmarks/src/indexer.rs, crates/rooch-benchmarks/src/lib.rs, crates/rooch-benchmarks/src/tx_exec.rs, crates/rooch-framework-tests/src/binding_test.rs, crates/rooch-indexer/src/tests/test_indexer.rs, crates/rooch-types/src/test_utils.rs, moveos/moveos-types/src/test_utils.rs
Finish #2366
1.  Implements indexer benchmark.
2. Fixup benchmarks dependency on tokio runtime.
- Closes #2366
=> [Benchmark] Implements indexer benchmark

crates/rooch-framework-tests/src/tests/bitcoin_multisign_validator_tests.rs, crates/rooch-framework-tests/src/tests/mod.rs, crates/rooch-genesis/src/lib.rs, crates/rooch-types/src/framework/auth_payload.rs, crates/rooch-types/src/framework/auth_validator.rs, crates/rooch-types/src/framework/bitcoin_validator.rs, crates/rooch-types/src/framework/mod.rs, crates/rooch-types/src/nursery/bitcoin_multisign_validator.rs, crates/rooch-types/src/nursery/mod.rs, crates/rooch-types/src/transaction/authenticator.rs, frameworks/rooch-framework/doc/auth_payload.md, frameworks/rooch-framework/doc/builtin_validators.md, frameworks/rooch-framework/doc/transaction_validator.md, frameworks/rooch-framework/sources/auth_validator/auth_payload.move, frameworks/rooch-framework/sources/auth_validator/builtin_validators.move, frameworks/rooch-framework/sources/transaction_validator.move, frameworks/rooch-nursery/doc/README.md, frameworks/rooch-nursery/doc/bitcoin_multisign_validator.md, frameworks/rooch-nursery/doc/genesis.md, frameworks/rooch-nursery/doc/multisign_account.md, frameworks/rooch-nursery/doc/multisign_wallet.md, frameworks/rooch-nursery/sources/bitcoin_multisign_validator.move, frameworks/rooch-nursery/sources/genesis.move, frameworks/rooch-nursery/sources/multisign_account.move, frameworks/rooch-nursery/sources/multisign_wallet.move, frameworks/rooch-nursery/tests/multisign_account_test.move
1. Remove the length in the message prefix and directly use the bcs serialize. The bcs length serialize is the same as bitcoin var int.
2. Implement the Bitcoin multisign validator and enable the multisign address to execute tx on Rooch.
TODO:
1. Migrate the Bitcoin multisign validator to `bitcoin-move`.
2. CLI support send multisign tx( build tx, sign tx, submit tx).
=> [framework] Refactor the auth payload encoding and implement bitcoin multisign validator

crates/rooch/src/commands/statedb/commands/genesis_verify.rs, crates/rooch/src/commands/statedb/commands/inscription.rs
Added source data logging in mismatch state outputs to improve debugging and traceability. Updated function signatures and call sites to support the new parameter, ensuring detailed logging of expected versus actual states with additional context.
=> refactor(statedb/genesis-verify): Enhance state mismatch debugging

.github/ISSUE_TEMPLATE/00-bug.yml, .github/ISSUE_TEMPLATE/10-proposal.yml, .github/ISSUE_TEMPLATE/config.yml
Created new issue templates for "Bugs" and "Proposals" to standardize issue reporting. These templates include guided fields to help users provide detailed and useful information for accurate problem-solving and proposal evaluation. A config file for issue templates was also added.
=> workflow(issue): add GitHub issue templates for bugs and proposals

crates/rooch/src/commands/statedb/commands/genesis_verify.rs
This helps to precisely identify discrepancies in various components like utxo_store, address_mapping, and inscription_store during the genesis data verification process.
=> chore: adjust log messages to specify 'metadata.size' for clarity in mismatch reports

crates/rooch/src/commands/db/commands/mod.rs, crates/rooch/src/commands/db/commands/rollback.rs, crates/rooch/src/commands/db/mod.rs, moveos/moveos-store/src/lib.rs, moveos/moveos-store/src/transaction_store/mod.rs
Add a command to rollback state to a specific tx order.
If the Bitcoin network reorg > 3 blocks, we need to roll back the L2 txs.
=> [CLI] add a command to rollback state to a specific tx order

crates/rooch/src/commands/statedb/commands/export.rs, crates/rooch/src/commands/statedb/commands/genesis_verify.rs, crates/rooch/src/commands/statedb/commands/mod.rs
Make ord related path options optional in genesis_verify command for checking UTXO only.
=> feat(statedb/genesis-verify): make ord path options optional in genesis_verify

Cargo.lock, crates/rooch-rpc-client/Cargo.toml, crates/rooch-rpc-client/src/rooch_client.rs, crates/rooch/src/commands/transaction/commands/build.rs, crates/rooch/src/commands/transaction/commands/mod.rs, crates/rooch/src/commands/transaction/mod.rs, crates/testsuite/features/cmd.feature
Add `build` subcommand for `rooch tx` and `rooch transaction`.
Example output (if writing to a file):
```zsh
rooch transaction build --function rooch_framework::empty::empty --json --file-location ~/text.txt
Write encoded tx data succeeded in the designated location
cat ~/text.txt                                                                                    
??U?J?LԌj?&?F?^m????3???VW??emptyempty% 
```
Example output (if outputting a hex):
```zsh
rooch transaction build --function rooch_framework::empty::empty --json --output
"0ea3bb55c14aec8e074cd48c6a850526aa46965e176df53fadb433adeeeb56570000000000000000040000000000000000e1f5050000000001000000000000000000000000000000000000000000000000000000000000000305656d70747905656d7074790000"
```
- Closes #2471
=> [gh-2471] add tx build command.

frameworks/moveos-stdlib/doc/event_queue.md, frameworks/moveos-stdlib/sources/event_queue.move
follow #2476 
1. Only create the event queue when the first subscriber subscribes to it to reduce the number of EventQueue objects.
2. Trigger an OffChainEvent when OnChainEvent emits; the developer can merge OnChain and OffChain events.
Leave a break change to #2402
=> [moveos_std] Improve the event queue, trigger OffChainEvent sametime

crates/rooch/src/commands/transaction/commands/mod.rs, crates/rooch/src/commands/transaction/commands/submit.rs, crates/rooch/src/commands/transaction/mod.rs, crates/testsuite/features/cmd.feature
Add `tx submit` command to submit the signed tx to Rooch.
- Closes #2478
=> [gh-2478] add tx submit command.

crates/rooch/src/commands/move_cli/commands/run_function.rs
Add dry run check for `run_function.rs`.
- Closes #2385
=> [gh-2385] add dry run check for run_function.rs.

frameworks/moveos-stdlib/doc/sort.md, frameworks/moveos-stdlib/sources/sort.move, frameworks/moveos-stdlib/tests/sort_tests.move
follow #2495 
[moveos_std] refactor sort to remove copy and drop requirements from the arguments
=> [moveos_std] refactor sort to remove copy and drop requirements from the arguments

crates/rooch-genesis/src/lib.rs, crates/rooch/src/commands/move_cli/commands/framework_upgrade.rs, frameworks/rooch-framework/doc/genesis.md, frameworks/rooch-framework/doc/upgrade.md, frameworks/rooch-framework/sources/genesis.move, frameworks/rooch-framework/sources/upgrade.move
1. resolve #2493 
2. Add `upgrade_v2_entry` function, which has `vector<u8>` argument used to deserialize to stdlib packages.
3. Add `UpgradeCap`. Owner who has `UpgradeCap` object can upgrade the framework. part of #2463 
- Closes #2493
=> new framework upgrade function and `UpgradeCap`

crates/rooch-benchmarks/src/tx_exec.rs, crates/rooch-framework-tests/README.md, crates/rooch-framework-tests/src/binding_test.rs, crates/rooch-framework-tests/src/bitcoin_block_tester.rs, crates/rooch-framework-tests/src/main.rs, crates/rooch-framework-tests/src/tests/bitcoin_tester_test.rs, crates/rooch-types/src/bitcoin/ord.rs, crates/rooch-types/src/bitcoin/types.rs
Verify the spend as fee case https://ordiscan.com/inscription/8706753
Print the l1 block execution gas used info in the binding test
Before #2500 (v0.6.9 tag)
execute l1 block total gas used: 114858924818, avg gas used: 18875747
After the insctiption_updater refactor:
execute l1 block total gas used: 121341117932, avg gas used: 19941021
cc @steelgeek091
=> [bitcoin] Improve the block 790964 testcase

crates/rooch/src/commands/statedb/commands/genesis_verify.rs
Adjust export order for `RoochToBitcoinAddressMapping` and `BitcoinUTXOStore`.
UTXO have been verified: they're all OP_RETURN
The total cost of reserve checking of UTXO is too long (40+hours), re-order for checking address mapping firstly
=> chore(genesis_verify): swap object export order in verification

infra/rooch-portal-v2/package.json, infra/rooch-portal-v2/src/sections/assets/components/ordinal-list-card.tsx, pnpm-lock.yaml
[Summary about this PR](fix: portal bitcoin assets compatibility)
=> fix: portal bitcoin assets compatibility

examples/btc_holder_farmer/sources/holder_farmer.move, frameworks/bitcoin-move/doc/README.md, frameworks/bitcoin-move/doc/ord.md, frameworks/bitcoin-move/doc/temp_state.md, frameworks/bitcoin-move/doc/utxo.md, frameworks/bitcoin-move/sources/ord.move, frameworks/bitcoin-move/sources/temp_state.move, frameworks/bitcoin-move/sources/utxo.move
Support TempStateDropEvent for UTXO and Inscription
The application can subscribe to the TempStateDropEvent on-chain event and implement business logic. 
close #2542
=> [bitcoin-move] Support TempStateDropEvent for UTXO and Inscription

examples/orderbook/sources/market.move
=> [example] add orderbook entry function

infra/rooch-portal-v2/next.config.mjs, infra/rooch-portal-v2/src/app/layout.tsx, infra/rooch-portal-v2/src/middleware.ts, infra/rooch-portal-v2/src/theme/color-scheme-script.ts, infra/rooch-portal-v2/src/theme/theme-provider.tsx
Related with #1958 
Add strict CSP rules to the Rooch Portal to prevent potential XSS attacks.
**Disadvantage**: it will cause all pages to be SSR. But this should be acceptable.
Example:
```jsx
<Script src="https://unpkg.com/react@16.7.0/umd/react.production.min.js" />
```
The application will refuse the connection:
> Refused to load the script 'https://unpkg.com/react@16.7.0/umd/react.production.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
Example:
```html
<button onclick="alert('you are hacked')" />
```
The application will refuse to exec:
> Refused to execute inline event handler because it violates the following …
=> [portal] add csp rule

crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs
#2602
```
rooch rpc request --method btc_queryUTXOs --params '[{"object_id":""}, null, null, null]'
{
"data": [],
"next_cursor": null,
"has_next_page": false
}
```
=> [panic] Fix null object id panic

README.md
=> Update README add more info about Bitcoin

crates/rooch-types/src/bitcoin/multisign_account.rs, frameworks/bitcoin-move/sources/multisign_account.move
=> [multisign_account] Add assert to ensure threshold <= public keys len

crates/rooch/src/commands/transaction/commands/sign.rs, crates/rooch/src/utils.rs, crates/testsuite/features/cmd.feature, crates/testsuite/features/multisign.feature, moveos/moveos-types/src/transaction.rs
- Closes #2588 
The readability of the args of the function is not good.
```
rooch tx sign /tmp/6716d5ff7ff8fe42.rtd
Transaction data:
Sender: rooch1xm3k80jyqh9hf5m8vjm4xjcna99xx0vrjyylzts3zmuks379kzusp270zj
Sequence number: 0
Chain id: 4
Max gas amount: 100000000
Action: MoveAction::FunctionCall( function_id: 0x0000000000000000000000000000000000000000000000000000000000000003::gas_coin::faucet_entry,  type_args: [], args: ["0x00e40b5402000000000000000000000000000000000000000000000000000000"])
Transaction hash: 0x6716…5efb
Do you want to sign this transaction? [yes/no] > 
y
Signed transaction is written to "/tmp/6716d5ff7ff8fe42.srt"
You can submit the transaction with `rooch tx submit /tmp/6716d5ff7ff8fe42.srt`
```
```
Partially signed transaction data:
Sender: …
```
=> [cli] Display the transaction info when sign tx

Cargo.lock, Cargo.toml, crates/rooch-oracle/Cargo.toml, crates/rooch-oracle/src/binance.rs, crates/rooch-oracle/src/data_process.rs, crates/rooch-oracle/src/lib.rs, crates/rooch-oracle/src/main.rs, crates/rooch-oracle/src/okx.rs, crates/rooch-oracle/src/pyth.rs, infra/rooch-portal-v2/contract/gas_market/Move.toml, infra/rooch-portal-v2/contract/gas_market/sources/gas_market.move, infra/rooch-portal-v2/contract/gas_market/sources/trusted_oracle.move
=> feat: gas market

crates/rooch/src/commands/indexer/commands/rebuild.rs, crates/rooch/src/commands/statedb/commands/export.rs
1. export dynamic field(sequence_number:inscription_id) of InscriptionStore conditionally
2. jump over dynamic field when rebuild indexer
=> fix(indexer): bypass dynamic field states when rebuild

crates/rooch/src/commands/util/commands/address.rs, crates/rooch/src/commands/util/commands/mod.rs, crates/rooch/src/commands/util/mod.rs
```bash
rooch util address bc1prcajaj9n7e29u4dfp33x3hcf52yqeegspdpcd79pqu4fpr6llx4sugkfjt
```
```json
{
"rooch_address": "rooch1wqwzr0cu3n26lrzznqufpkx22hn6sgqhrw88gnqn7tvenzlhdnps9x2j4l",
"hex_address": "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3",
"bitcoin_main_address": "bc1prcajaj9n7e29u4dfp33x3hcf52yqeegspdpcd79pqu4fpr6llx4sugkfjt",
"bitcoin_test_address": "tb1prcajaj9n7e29u4dfp33x3hcf52yqeegspdpcd79pqu4fpr6llx4stqqxgy",
"bitcoin_regtest_address": "bcrt1prcajaj9n7e29u4dfp33x3hcf52yqeegspdpcd79pqu4fpr6llx4sxe2qa7",
"bitcoin_segtest_address": "tb1prcajaj9n7e29u4dfp33x3hcf52yqeegspdpcd79pqu4fpr6llx4stqqxgy"
}
```
=> [cli] Provide a util address command to resolve and convert address format

crates/rooch/src/commands/bitcoin/sign_tx.rs, crates/testsuite/features/multisign.feature
Print utxo address if network provided; else print script.
```
rooch bitcoin sign-tx -s rooch13jgu06vyaucyfa4ylac7270ayzs7ll303g7yejzsqpvrekm7dpkqa9rlyr /tmp/f41721630dae28d1.psbt -n regtest
Transaction details before signing:
Version: 2
Lock time: 0
Network: regtest
Inputs:
Input 0:
Previous output: 2d4acda35bc3c1a6610d452d08c7e233358fe1ac097c34540a4e7ff78b499dff:0
Sequence: 4294967293
Address: bcrt1pefq58pva5v34jj5hp7pw89nrc8k7w6lfg5776uyh5wjgtyt74rrs8hg6xv
Outputs:
Output 0:
Value: 0.00010000 BTC
Address: bcrt1p9tjl8a76mx9glle4krl35fvlns5ncggpxfsneajdme27gdgxpf2qrakmd0
Output 1:
Value: 6.24989060 BTC
Address: bcrt1pefq58pva5v34jj5hp7pw89nrc8k7w6lfg5776uyh5wjgtyt74rrs8hg6xv
Do you want to sign this transaction? [yes/no] > 
```
```
rooch bitcoin sign-tx -s …
```
=> [cli] Display bitcoin tx detail

crates/rooch/src/commands/move_cli/commands/publish.rs
Disable verify module when publish package, we need to find a more efficient way to verify the modules.
=> [cli] Disable verify module when publish package

crates/rooch-types/src/transaction/rooch.rs, crates/rooch/src/commands/transaction/commands/mod.rs
Add signatories to each file suffix.
`psrt` with multiple signatories, others with one signatory.
- Closes #2589
=> [gh-2589] add signatories as file suffix.

crates/rooch-config/src/lib.rs, crates/rooch-rpc-server/src/axum_router.rs, crates/rooch-rpc-server/src/lib.rs, crates/rooch-rpc-server/src/service/metrics.rs, crates/rooch-rpc-server/src/service/mod.rs, crates/rooch-types/src/lib.rs, crates/rooch-types/src/service_type.rs
1. add socket 
2. service metrics
3. change local service burst size 5000
=> add socket & service metrics

crates/rooch-da/src/chunk.rs, crates/rooch-da/src/segment.rs, crates/rooch-da/src/server/openda/actor/server.rs
Added a data_len field to SegmentV0 for tracking data length. Refactored related methods to handle the data length field, ensuring accurate serialization and deserialization. This improves segment management within the chunk processing.
=> feat(rooch-da): add data length tracking to segments

.github/workflows/deploy_mainnet.yml, crates/rooch-proposer/src/scc/mod.rs, scripts/deploy_rooch_mainnet.sh
1. rm open-da(gcs) for mainnet deploy workflow
2. switch to save last block instead of a map: Replaced BTreeMap with an Option to store only the last block in StateCommitmentChain. Updated methods for adding and retrieving the last block accordingly, streamlining state management.
=> fix(da): rm open-da(gcs) for mainnet deploy workflow

scripts/deploy_rooch_testnet.sh
Temp disable the traffic control.
We should have an option to disable the traffic rate limit fully  @wow-sven
=> [script] disable traffic control

frameworks/moveos-stdlib/sources/event_queue.move
=> [framework]:add exist_new_events fun and subscriber_info fun

frameworks/bitcoin-move/doc/bitcoin.md, frameworks/bitcoin-move/sources/bitcoin.move
[bitcoin] temporarily pauses the ordinals protocol for performance issues.
=> [bitcoin] temporary pause the ordinals protocol

Cargo.lock, crates/rooch-event/src/actor.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-pipeline-processor/src/actor/messages.rs, crates/rooch-pipeline-processor/src/actor/processor.rs, crates/rooch-pipeline-processor/src/proxy/mod.rs, crates/rooch-relayer/src/actor/relayer.rs, crates/rooch-rpc-api/Cargo.toml, crates/rooch-rpc-api/src/api/rooch_api.rs, crates/rooch-rpc-api/src/jsonrpc_types/mod.rs, crates/rooch-rpc-api/src/jsonrpc_types/status.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch-sequencer/src/actor/sequencer.rs, crates/rooch-sequencer/src/messages.rs, crates/rooch-sequencer/src/proxy/mod.rs, crates/rooch-types/src/bitcoin/types.rs, crates/rooch-types/src/service_status.rs, crates/testsuite/features/bitcoin.feature, frameworks/bitcoin-move/doc/pending_block.md, frameworks/bitcoin-move/sources/bitcoin.move, frameworks/bitcoin-move/sources/pending_block.move, moveos/moveos/src/moveos.rs
[bitcoin_move] Improve reorg and pending block logic.
[test] Add reorg failed test case
[rpc] Add `rooch_status` API to get the rpc service, Rooch, and Bitcoin status.
```bash
rooch rpc request --method rooch_status 
```
```json                                                             
{
"service_status": "active",
"rooch_status": {
"sequencer_info": {
"last_order": "224",
"last_accumulator_info": {
"accumulator_root": "0x47cf3562c72f93e360017b08374e2bbb8ba319c824c649946a4dfa4511599347",
"frozen_subtree_roots": [
"0x3795aa636d75ff68d282b9afad889ba9c0efca46fcd9b93e79ea703d65759a4d",
"0x96e1b6e9e0c2bfa2a92bc83db25baf2e1a8789147246898a331f9a9fb4ec31bd",
"0xb81ea651ae858bb6522b25a4d2b1617d6be684114f5cf9e71987a339c858543d",
"0x65a9391a914f641cf723ea9780f04e9682f10e42fe0f129826e6f5e9cc6a34e8" …
```
=> [bitcoin_move] Improve reorg and pending block

crates/rooch-rpc-server/src/service/rpc_service.rs
=> [rpc] limit ids

examples/btc_holder_farmer/sources/holder_farmer.move
=> feat: add utxo timelock weight and update coin name

crates/rooch-rpc-server/src/axum_router.rs, crates/rooch/src/commands/account/commands/balance.rs, crates/rooch/src/commands/move_cli/commands/unit_test.rs, crates/testsuite/features/multisign.feature, crates/testsuite/features/portal.feature, infra/rooch-portal-v2/contract/gas_market/Move.toml, infra/rooch-portal-v2/contract/gas_market/sources/gas_airdrop.move, infra/rooch-portal-v2/contract/gas_market/sources/gas_market.move
Implement gas airdrop and add testsuit to gas market
=> [portal] Implement gas airdrop and add testsuit to gas market

crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, moveos/moveos-types/src/access_path.rs, moveos/moveos-types/src/moveos_std/object.rs
=> [rpc] add limit to object_ids

crates/rooch-faucet/src/faucet.rs, crates/rooch-oracle/src/binance.rs, crates/rooch-oracle/src/data_process.rs, crates/rooch-oracle/src/okx.rs, crates/rooch-oracle/src/pyth.rs, crates/rooch-rpc-api/src/jsonrpc_types/function_return_value_view.rs, crates/rooch-rpc-client/src/wallet_context.rs, crates/rooch-types/src/address.rs, crates/rooch/src/commands/account/commands/create_multisign.rs, crates/rooch/src/commands/account/commands/transfer.rs, crates/rooch/src/commands/mod.rs, crates/rooch/src/commands/move_cli/commands/publish.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, crates/rooch/src/commands/session_key/commands/create.rs, crates/rooch/src/commands/task/commands/checker.rs, crates/rooch/src/commands/task/commands/mod.rs, crates/rooch/src/commands/task/commands/runner.rs, crates/rooch/src/commands/task/commands/schedule.rs, crates/rooch/src/commands/task/mod.rs, crates/rooch/src/commands/transaction/commands/sign.rs, crates/rooch/src/lib.rs, crates/testsuite/features/portal.feature, infra/rooch-portal-v2/contract/gas_market/sources/gas_market.move
This PR introduces several enhancements and new features:
1. Scheduled Task Command: Implements the rooch task schedule command to run scheduled tasks. This includes checking for OnChainEvent and executing transactions to consume these events.
2. Wallet Context Refactor: Refactors the wallet context, focusing on password handling and the sign API to simplify the logic and improve usability.
=> [cli] Add Task Scheduling Command and Refactor Wallet Context API

crates/rooch-oracle/src/data_process.rs
Fix the oracle websocket error handle, break the read loop and retry.
=> [oracle] Fix oracle websocket error handle

crates/rooch-config/src/da_config.rs, crates/rooch-da/README.md, crates/rooch-da/src/actor/server.rs, crates/rooch-types/src/da/batch.rs
1. Introduce a `nop_backend` flag to manage fallback behavior in absence of backend configuration. This allows the system to use a No-Operation backend and skip block state updates accordingly.
2. Improve DA configuration with additional path logic for segments.
3. Add `get_hash` function for batch meta in rooch-types.
4. Update README for clarity on DA process and roles.
=> refactor(rooch-da): add nop_backend flag for fallback handling

crates/rooch-da/src/actor/server.rs, crates/rooch-store/src/da_store/mod.rs, crates/rooch-store/src/tests/test_da_store.rs
Updated the get_submitting_blocks function to accept an optional count parameter for fetching a specific number of blocks. Added corresponding tests to validate the new functionality.
=> feat(rooch-da): Enhance get_submitting_blocks with count limit

crates/rooch/src/commands/server/commands/clean.rs
When the user presses enter without any input, it is equivalent to the user entering `Y`.
=> feat(cli): default option for "server clean" is Y

crates/rooch-store/src/lib.rs
Renamed DA_BLOCK_CURSOR_COLUMN_FAMILY_NAME for clarity and consistency within the codebase. This change should make the column family names more intuitive for future maintenance.
=> refactor(rooch-store): rename DA block cursor constant

crates/rooch-store/src/lib.rs
This reverts commit b3870af384ba45f99f9f7cd7b07f730c6f7abd08.
this commit cause:
Error: Invalid argument: Column families not opened: da_last_block_number
and rocksdb cannot be opened correctly
although it's not a good name but enought to tell developer what is it
=> Revert "refactor(rooch-store): rename DA block cursor constant (#2797)"

crates/rooch/src/commands/db/commands/drop.rs
Introduce '--force' flag to ensure deliberate execution of drop command. Update help description for 're-create' to clarify its purpose.
=> feat(db): add force option to drop command

Cargo.lock, crates/rooch-config/Cargo.toml, crates/rooch-config/src/da_config.rs, crates/rooch-config/src/lib.rs, crates/rooch-da/src/backend/openda/mod.rs
Implement From<OpenDAScheme> for opendal::Scheme conversion. Add tests for retrieve_map_config_value and check_backend_config.
For fixing server starting issue with empty bucket config:
```
[2m2024-10-21T21:00:18.277729Z[0m [31mERROR[0m [2mrooch_rpc_server[0m[2m:[0m ConfigInvalid (permanent) at Builder::build, context: { service: gcs } => The bucket is misconfigured
```
=> feat(rooch-config): add OpenDAScheme conversion and tests

sdk/typescript/rooch-sdk-kit/src/utils/walletUtils.ts
The function `checkWallets` is called multiple times, which creates different wallet instances for the same wallet class. Because of this, even though `registered` is a Set, it still ends up adding multiple duplicate wallets.
https://github.com/rooch-network/rooch/blob/b98ce6fefb1433d861f9d292a900b681f62c3352/sdk/typescript/rooch-sdk-kit/src/wellet/wallets.ts#L6-L8
At the SDK level, each wallet class should have only one instance.
- Closes #2779
=> fix(sdk): duplicate instance

crates/rooch/src/commands/da/README.md, crates/rooch/src/commands/db/README.md
Add detailed usage instructions for revert, rollback, and drop commands in rooch-db README. Improve clarity on tx_order and column family operations, and specify conditions for dangerous operations.
=> docs(rooch-db): enhance documentation with new commands

crates/rooch-da/src/actor/server.rs, crates/rooch-store/src/da_store/mod.rs
Ensure cursor is correctly updated to the last submitted block. This prevents reprocessing already submitted blocks and improves logging for better traceability.
=> fix(rooch-da): correct cursor update in background submitter

crates/rooch-da/src/actor/messages.rs, crates/rooch-da/src/actor/server.rs, crates/rooch-da/src/proxy/mod.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/jsonrpc_types/status.rs, crates/rooch-rpc-server/src/lib.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch-store/src/da_store/mod.rs, crates/rooch-store/src/lib.rs, crates/rooch-store/src/tests/test_da_store.rs, crates/rooch-types/src/da/state.rs
1. feat(rpc): add DA server status to rooch_status RPC
2. feat(rooch-store): refactor append_submitting_block logic
Remove redundancy by eliminating last_block_number parameter from append_submitting_block. Adjust related tests and background submission interval to reflect changes and ensure database consistency checks
=> feat(rpc): add DA server status to rooch_status RPC

crates/rooch-pipeline-processor/src/actor/processor.rs
Reverse the transactions to maintain their order during startup processing. This ensures the correct sequence is preserved, preventing potential issues.
=> fix(rooch-pipeline-processor): reverse txs in processor startup execution

crates/rooch-store/src/da_store/mod.rs, crates/rooch/src/commands/db/README.md
Rename the variable `first_broken` to `first_illegal` for better clarity and precision in `da_store/mod.rs`. Additionally, update `README.md` to include documentation for the new database repair options.
=> chore(docs): add rooch db repair readme

Cargo.lock, Cargo.toml, crates/rooch/Cargo.toml, crates/rooch/src/commands/account/commands/balance.rs, crates/rooch/src/commands/account/commands/list.rs, crates/rooch/src/commands/env/commands/list.rs, crates/rooch/src/commands/session_key/commands/list.rs, crates/rooch/src/commands/session_key/mod.rs
This update improves the `rooch` CLI output formatting using the `tabled` library. It aims to optimize the display of data tables to enhance readability, especially for commands that return long text fields. Additional table views across the CLI can be similarly optimized if provided.
1. **`rooch account list`**: The output for account lists is adjusted so that multiple wallet addresses are consolidated into a readable table format, preventing line wrapping due to overly long addresses.
2. **`rooch account balance`**: Account balances are displayed with clearer column formatting, ensuring balance values align effectively.
3. **`rooch env list`**: The environment list displays each configuration in a structured table format, improving readability.
4. **`session-key list`**: Adds a new …
=> [CLI] Use tabled as cli default output style #

Cargo.lock, Cargo.toml, crates/rooch-benchmarks/Cargo.toml, crates/rooch-benchmarks/benches/bench_utils.rs
new version of anyhow with std backtrace is much slower: https://github.com/dtolnay/anyhow/issues/347
```
cargo bench --bench bench_utils
anyhow_error_bench/anyhow_v1.0.93
time:   [15.040 ns 15.148 ns 15.259 ns]
change: [+1.5448% +2.1215% +2.7219%] (p = 0.00 < 0.05)
Performance has regressed.
anyhow_error_bench/anyhow_v1.0.76
time:   [6.2104 ns 6.2182 ns 6.2278 ns]
change: [-0.4029% -0.1998% +0.0002%] (p = 0.06 > 0.05)
No change in performance detected.
Found 10 outliers among 100 measurements (10.00%)
2 (2.00%) high mild
8 (8.00%) high severe
...
Downgraded anyhow dependency from version 1.0.93 to 1.0.76. Won't break anything but gain better perf.
=>  fix(deps): downgrade anyhow version to 1.0.76

Cargo.lock, Cargo.toml, crates/rooch-da/src/backend/openda/operator.rs
This PR will update Opendal to version 0.50, which introduces newer dependencies and improved performance.
=> deps: Bump OpenDAL to 0.50

kube/promtail/promtail-clusterrole.yaml, kube/promtail/promtail-clusterrolebinding.yaml, kube/promtail/promtail-config.yaml, kube/promtail/promtail-daemonset.yaml, kube/promtail/service-account.yaml
collect all services log from k8s
=> k8s log collect

crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs, moveos/moveos-object-runtime/src/runtime_object_meta.rs
=> remove empty object change

crates/rooch-rpc-server/src/service/rpc_service.rs, crates/testsuite/features/cmd.feature
Fix the sync_states interface returns a StateChangeSetWithTxOrderView with empty changes
https://github.com/rooch-network/rooch/issues/2865
=> Owen/issues 2865/sync states filter out empty changes

crates/rooch-rpc-server/src/lib.rs
Changed the block propose duration from 5 seconds to 600 seconds for balancing cost on L1 and memory usage of buffer.
=> refactor(proposer): adjust block propose duration

crates/rooch-da/src/backend/openda/avail.rs, crates/rooch-da/src/backend/openda/celestia.rs, crates/rooch-da/src/backend/openda/operator.rs
1. increase default max segment size to 8MB
2. increase initial backoff delay from 2000ms to 3000ms.
3. modify exponential backoff multiplier from 2 to 3 to better handle transaction resubmissions.
4. Increased the initial backoff delay from 2000ms to 3000ms and changed the exponential backoff multiplier from 2 to 3 to improve retry mechanism for avail-da
=> chore(openda): adjust several default configs for backends

crates/rooch-config/src/da_config.rs, crates/rooch-da/src/actor/server.rs
Added a new configuration option 'da_init_offset' in `DAConfig` to set the initial block offset for submission. Modified `start_job` function to accommodate this new offset and adjust the block submission cursor accordingly.
=> feat(da-config): add initial block offset configuration

crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs, crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs, crates/rooch-rpc-server/src/service/rpc_service.rs
Limit the number of struct elements in a Move struct. 
related issue: #2906
=> [RPC] Limit the number of struct elements in a Move struct when querying

sdk/typescript/rooch-sdk-kit/src/hooks/client/useCurrentNetwork.ts, sdk/typescript/rooch-sdk-kit/src/provider/clientProvider.tsx, sdk/typescript/rooch-sdk/README.md, sdk/typescript/rooch-sdk/src/client/index.ts, sdk/typescript/rooch-sdk/src/client/networks.ts
- Update `provider` to `client` in rooch-sdk readme
- Change `NetWorkType` to `NetworkType`
=> [rooch-sdk] Update rooch-sdk readme some nits and change NetworkType name

crates/rooch-rpc-server/src/lib.rs
fix server start panic issue:
```
RUST_BACKTRACE=1 rooch server start
...
2024-11-22T21:19:12.659554Z  INFO rooch_rpc_server: acl=Const("*")
thread 'main' panicked at /Users/popcnt/rx/popcnt1/rooch/crates/rooch-rpc-server/src/lib.rs:471:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
0: _rust_begin_unwind
1: core::panicking::panic_fmt
2: core::panicking::panic
3: core::option::unwrap_failed
4: rooch_rpc_server::run_start_server::{{closure}}
5: <rooch::commands::server::commands::start::StartCommand as rooch::cli_types::CommandAction<()>>::execute::{{closure}}
6: rooch::cli_types::CommandAction::execute_serialized::{{closure}}
7: <rooch::commands::server::Server as rooch::cli_types::CommandAction<alloc::string::String>>::execute::{{closure}}
8: rooch::main::{{closure}}
9: …
```
=> fix(rooch-rpc-server): adjust default rate limit configuration

moveos/moveos-store/src/lib.rs
Updated to use non-sync write for transaction execution info because it allows replaying transactions from the Rooch store at startup and provides sequential output writing.
=> refactor(moveos-store): use non-sync write for transaction execution info

Cargo.lock
fix:
```
Notice: Git status is dirty
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
Notice:   File: Cargo.lock
::endgroup
```
in https://github.com/rooch-network/rooch/actions/runs/12041865458/job/33574520713
=> fix(Cargo.lock): bump bitcoin-client version to 0.8.1

frameworks/moveos-stdlib/doc/gas_schedule.md, frameworks/moveos-stdlib/sources/gas_schedule.move, frameworks/rooch-framework/doc/transaction_fee.md, frameworks/rooch-framework/doc/transaction_validator.md, frameworks/rooch-framework/sources/gas_coin.move, frameworks/rooch-framework/sources/transaction_fee.move, frameworks/rooch-framework/sources/transaction_validator.move
1. Distribute the gas fee to the sequencer and contract address.
2. Use gas_schedule::max_gas_amount const in transaction_validator. @steelgeek091 
The benchmark result is regressed because we need to split the gas fee. I can not find a better solution to optimize it.
=> [framework] Gas fee distribute

crates/rooch-benchmarks/README.md, crates/rooch-benchmarks/src/config.rs, crates/rooch-benchmarks/src/tx.rs, crates/rooch-benchmarks/src/tx_exec.rs, crates/rooch-test-transaction-builder/src/lib.rs, examples/large_objects/Move.toml, examples/large_objects/sources/big_vector.move, third_party/move/language/move-vm/types/src/values/values_impl.rs
1. Optimize vector\<u8\> deserialization in RuntimeObject
2. Add a benchmark for large object transferring.
related issue: #2678 
1. Given the following Move struct with 100000 elements, the deserialization time in `RuntimeObject::load` descreased from 4861.5us to 13.7us.
```
struct VecU8 has key, store {
values: vector<u8>
}
```
2. benchmark for `bench_tx_exec/l2_tx_transfer_large_object`:
3. benchmark for `bench_tx_exec/l2_tx_transfer`
=> Optimize vector<u8> deserialization in RuntimeObject

frameworks/bitcoin-move/doc/README.md, frameworks/bitcoin-move/doc/bbn.md, frameworks/bitcoin-move/doc/bbn_updater.md, frameworks/bitcoin-move/doc/bitcoin.md, frameworks/bitcoin-move/sources/bbn.move, frameworks/bitcoin-move/sources/bbn_updater.move, frameworks/bitcoin-move/sources/bitcoin.move
1. An implementation to process Babylon protocol when processing Bitcoin transactions.
2. Init the Babylon cap3 global parameter.
3. Unbunding Babylon stake when UTXO spent
=> [bitcoin_move] process Babylon protocol when processing Bitcoin transactions

crates/rooch-db/src/lib.rs
Fix typo in variable name from 'feild_key' to 'filed_key' in state change iteration.
=> chore(rooch-db): correct typo in iterator variable name

crates/rooch/src/commands/da/README.md, crates/rooch/src/commands/da/commands/unpack.rs
Add a `--verify-order` flag to the unpack command to ensure transactions across all batches have strictly incremental order. Introduced a new method to validate transaction sequences during the unpacking process, enhancing data consistency checks.
=> feat(rooch-da): add transaction order verification in unpack

crates/rooch-config/src/store_config.rs, moveos/moveos-config/src/store_config.rs, moveos/raw-store/src/rocks/mod.rs
Enable RocksDB statistics configuration through a new `enable_statistics` option. This adds flexibility to toggle statistics and sets the stats level conditionally.
=> feat(config): add `enable_statistics` option for RocksDB

crates/rooch/src/commands/da/commands/exec.rs, crates/rooch/src/commands/da/commands/mod.rs, crates/rooch/src/commands/da/commands/unpack.rs
Add functionality to track the maximum chunk ID and determine the starting chunk for transaction processing. This optimizes chunk handling with binary search and improves transaction execution flow.
=> feat(da): track max chunk ID and find begin chunk for speed up re-exec init process

crates/rooch/src/commands/da/commands/dump_tx_order_hash.rs, crates/rooch/src/commands/da/commands/exec.rs, crates/rooch/src/commands/da/commands/get_tx_order_hash.rs, crates/rooch/src/commands/da/commands/mod.rs, crates/rooch/src/commands/da/commands/unpack.rs, crates/rooch/src/commands/da/mod.rs, crates/rooch/src/commands/db/commands/rollback.rs
1. add rollback for catching wrong tx execution
2. implement transaction order hash command for dump tx_order:tx_hash:block
=> feat(rooch-da): add rollback for exec cmd

crates/rooch/src/commands/da/commands/mod.rs
Refactored `find_last_executed` to use a generic utility function `find_last_true`, reducing code complexity. Updated tests to cover edge cases and maintain coverage for the new implementation.
=> refactor(rooch-da): simplify find_last_executed logic

crates/rooch-common/src/utils/mod.rs, crates/rooch-common/src/utils/vec.rs, crates/rooch/src/commands/da/commands/exec.rs, crates/rooch/src/commands/da/commands/index_tx.rs, crates/rooch/src/commands/da/commands/mod.rs, crates/rooch/src/commands/da/mod.rs, crates/rooch/src/commands/db/commands/dump_tx_root.rs, crates/rooch/src/commands/db/commands/mod.rs, crates/rooch/src/commands/db/mod.rs
Introduce `DumpTxRootCommand` to export transaction orders and state roots to an output file. This enhances database debugging and transaction analysis capabilities.
=> feat(db): add command to dump transaction state roots

apps/grow_bitcoin/sources/grow_bitcoin.move
Before executing the batch operation, it is necessary to determine whether there are records or not. If there are no records, skip it.
=> feat: check exist before batch handle

apps/rooch_dex/Move.toml, apps/rooch_dex/sources/route.move, apps/rooch_dex/sources/swap.move, apps/rooch_dex/sources/swap_utils.move
- This PR is based on the implementation of Pancake
- Rooch coin accuracy is u256, but for simplicity and not overflow, the routing entry is limited to u64
=> feat: uni v2 like dex

frameworks/rooch-framework/doc/session_key.md, frameworks/rooch-framework/sources/session_key.move
Limit session key max_inactive_interval to 30 days
=> [framework] Limit session key max_inactive_interval to 30 days

Cargo.lock, crates/rooch/Cargo.toml, crates/rooch/src/commands/db/commands/best_rollback.rs, crates/rooch/src/commands/db/commands/mod.rs, crates/rooch/src/commands/db/mod.rs
Introduce `BestRollbackCommand` to determine the optimal rollback transaction order during a chain reorganization. This implementation interacts with DA and BTC RPC services, providing a robust mechanism to compare block hashes and ensure data consistency.
- Closes #3081
=> feat(rooch-da): add best rollback command for chain reorg

crates/rooch-types/src/indexer/state.rs, crates/rooch/src/commands/object.rs
rooch object --help
```
rooch object --help                               
Usage: rooch object [OPTIONS]
Options:
-i, --object-ids <OBJECT_IDS>...  Object ids. Separate multiple IDs with a space
-t, --object-type <OBJECT_TYPE>   Struct name as `ADDRESS::MODULE_NAME::STRUCT_NAME<TypeParam1?, TypeParam2?>`
-o, --owner <OWNER>               The address of the object's owner
--cursor <CURSOR>             Provide the cursor in the format 'tx_order,state_index' (e.g., '12345,67890')
--limit <LIMIT>               Max number of items returned per page
-d, --descending-order            descending order
--show-display                Render and return display fields
--filter-out                  Is filter not object_type
--password <PASSWORD>         The key store password
--config-dir <CONFIG_DIR> …
```
=> [CLI] Add cursor argument for rooch object command

scripts/deploy_rooch_mainnet.sh, scripts/deploy_rooch_testnet.sh
Added `--rocksdb-row-cache-size` and `--rocksdb-block-cache-size` flags to testnet and mainnet deployment scripts. This improves database performance by configuring cache sizes for RocksDB.
In local testing, an increase in execution speed was observed (after data sizes exceeded 1T)
The extra memory  cost won't much, the total memory usage keeps under 40GB with 16GB cache size for both of row and block cache.
New rocksdb statistics are being collected along with the local execution, and the parameters will be further refined as new evidence becomes available, starting with a relatively coarse cache expansion for this revision.
=> feat(scripts): add RocksDB cache size configuration

crates/rooch/src/commands/db/commands/best_rollback.rs
1. Revise the best rollback logic with enhanced hash comparison and clearer user feedback. Improve structure definitions, parameter handling, and overall usability.
2. Fix infinite loop issue in segment fetching with increment logic.
=> refactor(rooch-db): refine best rollback logic and structure

Cargo.toml
Added a new `optdev` profile in Cargo.toml inheriting from `release`. This profile disables LTO and sets codegen-units to 16 for faster, optimized debug builds.
=> feat(build): add optdev profile for optimized debug builds

.github/workflows/deploy_testnet.yml, crates/rooch-config/src/da_config.rs, scripts/deploy_rooch_testnet.sh
Add Turbo Avail as a new data availability backend with support for `turbo_endpoint` and `turbo_auth_token` in configuration. Updated deployment scripts and workflows to include Avail-specific secrets.
=> ci(deploy): add Turbo Avail DA backend support

Cargo.lock, Cargo.toml, crates/rooch/Cargo.toml, crates/rooch/src/commands/da/commands/exec.rs, crates/rooch/src/commands/da/commands/unpack.rs
1. Added support for tracking and displaying L2 transaction size statistics in the unpack command, including histograms and top-N transaction sizes. Also introduced a `--stats-only` flag to unpack for stats-only processing.
2. fix(rooch-da): handle state root mismatch error in execution
Add explicit error handling for cases where the execution state root does not match RoochNetwork. This ensures more accurate error reporting and avoids unintended behavior during L2 transaction execution.
=> feat(rooch-da): add transaction stats tracking to unpack

infra/rooch-portal-v2/src/sections/inviter/index.tsx, infra/rooch-portal-v2/src/sections/settings/view.tsx, infra/rooch-portal-v2/src/utils/inviter.ts, pnpm-lock.yaml, sdk/typescript/rooch-sdk/test-e2e/case/grow.test.ts, sdk/typescript/rooch-sdk/test-e2e/setup.ts
=> add grow export e2e & inviter address change 2 btc

docs/website/pages/build/getting-started/connect-to-rooch/run-local-testnet.zh-CN.mdx
fix website docs spelling mistake in the line 
> 如果有遇到服务数据冲突的问题，首先执行**清楚**命令，再继续启动服务：
to 
>  如果有遇到服务数据冲突的问题，首先执行**清除**命令，再继续启动服务：
=> fix: fix website docs spelling mistake

Cargo.lock, Cargo.toml, crates/rooch-benchmarks/Cargo.toml, crates/rooch/Cargo.toml, crates/rooch/src/main.rs
1. replace rooch/rust-rocksdb with upstream rocksdb ([fix GETCPU feature](https://github.com/rust-rocksdb/rust-rocksdb/pull/950) has been released in v0.23.0)
2. replace jemalloc with tikv-jemallocator
=> chore(deps): replace rooch-network/rust-rocksdb with upstream rocksdb

crates/rooch-da/src/actor/server.rs
Ensure cursor updates only when necessary to reduce disk I/O and avoid misleading update times. Added a condition to compare the current cursor with the last block number before updating.
=> fix(rooch-da): avoid unnecessary cursor updates

crates/rooch-da/src/actor/server.rs, crates/rooch-da/src/batcher/mod.rs
Refactored BatchMaker to validate transaction order continuity, preventing mismatches between tx_order_start and the last block's tx_order_end. Introduced better error handling during batch creation to avoid database update inconsistencies. Updated tests to confirm correct behavior under the new logic.
- Closes #3196
=> feat(rooch-da): ensure batch continuity and fix tx order error

apps/rooch_dex/sources/liquidity_incentive.move
=> Fix liquidity incentive

crates/rooch/src/commands/da/commands/exec.rs
Enhanced the producer task to gracefully handle shutdown signals by using `tokio::select!`. Added logic to calculate and log the average execution time per transaction for better performance tracking.
=> feat(rooch-da): add shutdown handling in producer task

crates/rooch-da/src/actor/server.rs, crates/rooch-da/src/backend/openda/adapter.rs
Revamped `AdapterSubmitStat` to track submitted segments using a vector instead of the sum, ensuring accurate submission tracking. Adjusted `get_latest_done_chunk_id` to return `Option<u128>` and implemented a fallback for compatibility with older versions. Updated tests accordingly.
=> fix(openda): improve chunk submission tracking and handle optional latest_done_chunk_id compatibility

examples/verity_oracle_example/Move.toml, examples/verity_oracle_example/sources/example.move
=> Oracle update

crates/rooch-benchmarks/benches/bench_tx_exec.rs, crates/rooch-benchmarks/benches/bench_tx_validate.rs, crates/rooch-benchmarks/src/tx.rs, crates/rooch-pipeline-processor/src/actor/processor.rs, crates/rooch-relayer/src/actor/relayer.rs, crates/rooch/src/commands/da/commands/exec.rs
1. Refactored tx_hash caching to improve performance and reduce redundancy
2. memmove of block body is unnecessary
3. L1Block is small, that's the real field we need to share between actors. Clone it but not whole L1BlockWithBody
4.  Increase tx count and measurement time for benchmarking
=> refactor(pipeline): reduce memcopy by avoiding whole L1BlockWithBody clone and optimize tx_hash caching

crates/rooch-da/src/actor/messages.rs, crates/rooch-da/src/actor/server.rs, crates/rooch-da/src/batcher/mod.rs, crates/rooch-da/src/proxy/mod.rs, crates/rooch-pipeline-processor/src/actor/processor.rs
Introduce `RevertTransactionMessage` and associated logic to handle transaction reverts. This includes updates to batch management, actor handling, and DA server proxy to support transaction rollback scenarios.
- Closes #3265 
- Closes #3264
=> feat(rooch-da): add transaction revert handling

crates/rooch/src/commands/da/README.md, crates/rooch/src/commands/da/commands/exec.rs, crates/rooch/src/commands/da/commands/mod.rs, crates/rooch/src/commands/db/commands/get_tx_by_order.rs, crates/rooch/src/commands/db/commands/mod.rs, crates/rooch/src/commands/db/mod.rs
1. Introduce `GetTxByOrderCommand` to fetch a `LedgerTransaction` based on its order. Integrated the new command into the database commands module and CLI.
2. handle null state roots when parsing expected roots file
3. docs improvements
=> feat(rooch-db): add command to fetch transaction by order

Cargo.lock, crates/rooch-sequencer/src/actor/sequencer.rs, crates/rooch/Cargo.toml, crates/rooch/src/commands/da/commands/exec.rs, crates/rooch/src/commands/da/commands/mod.rs, crates/rooch/src/commands/da/commands/pack.rs, crates/rooch/src/commands/da/mod.rs, crates/rooch/src/commands/transaction/commands/mod.rs, crates/rooch/src/commands/transaction/commands/sign_order.rs, crates/rooch/src/commands/transaction/mod.rs, crates/rooch/src/utils.rs
1. feat(rooch-da): add pack command to DA module
Introduce the PackCommand to enable segmenting human-readable LedgerTransaction lists into chunk. Updated related DA module code and fixed some error-handling inconsistencies.
2. feat(rooch): add cmd for signing transaction order
Introduces the `SignOrderCommand` to handle signing transaction orders with sequencer keys. Includes integration into the CLI, command routing, and dependencies on `rooch-sequencer`.
3. other fix/improvement
=> feat(rooch-cmd): add cmds for packing DA batch

crates/rooch-executor/src/actor/executor.rs, crates/rooch-oracle/src/data_process.rs, crates/rooch-proposer/src/scc/mod.rs, crates/rooch-relayer/src/actor/bitcoin_relayer.rs, crates/rooch-relayer/src/actor/ethereum_relayer.rs, crates/rooch-relayer/src/actor/relayer.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-sequencer/src/actor/sequencer.rs, crates/rooch/src/commands/transaction/commands/sign.rs, moveos/moveos-store/src/lib.rs, moveos/moveos/src/moveos.rs
The tx hash printed in the current log is truncated, which is not convenient for troubleshooting. All logs output the complete tx hash.
=> Print full tx hash for trouble shoot

Cargo.lock, crates/rooch-da/src/actor/server.rs, crates/rooch-sequencer/src/actor/sequencer.rs, crates/rooch-types/src/da/batch.rs, crates/rooch-types/src/da/chunk.rs, crates/rooch-types/src/test_utils.rs, crates/rooch-types/src/transaction/ledger_transaction.rs, crates/rooch/Cargo.toml, crates/rooch/src/commands/da/commands/mod.rs, crates/rooch/src/commands/da/commands/pack.rs, crates/rooch/src/commands/db/commands/best_rollback.rs, crates/rooch/src/commands/transaction/commands/sign_order.rs
1. feat(rooch-da): add transaction order verification
Introduce `verify_tx_order` method for fast transaction order validation. Updated methods to include proper error handling with `anyhow::Result` and integrated validation checks when creating and verifying batches.
2. fix(rooch-da): handle errors in `get_tx_list` and improve checks
Refactored `get_tx_list` to return `Result`, ensuring robust error handling. Added transaction ordering verification before signing to enhance consistency and reliability during batch processing.
3. feat(rooch-sequencer): move sign_tx_order to LedgerTransaction
Relocated `sign_tx_order` function from `rooch-sequencer` to `LedgerTransaction` for better modularity and reuse. Updated relevant calls and tests to reflect the change.
=> feat(rooch-da): add transaction order verification when making new batch

Cargo.toml
If the bitcoin auto upgrades to 0.32.5, it will raise error.
```
error[E0276]: impl has stricter requirements than trait
--> /home/jolestar/opensource/src/github.com/rooch-network/rooch/crates/rooch-types/src/framework/auth_payload.rs:107:28
|
107 |     fn consensus_decode<D: BufRead + ?Sized>(
|                            ^^^^^^^ impl has extra requirement `D: bitcoin::bitcoin_io::BufRead`
```
TODO manually upgraded the bitcoin dependency. #2853
=> [deps] Lock the bitcoin version to 0.32.3

frameworks/moveos-stdlib/doc/compare.md, frameworks/moveos-stdlib/sources/compare.move
Fix the compare function for vector<u8> and string type.
=> [moveos_std] fix compare for string and vector<u8> type

crates/rooch/src/commands/db/commands/list_empty.rs, crates/rooch/src/commands/db/commands/mod.rs, crates/rooch/src/commands/db/mod.rs
Introduce ListEmptyCommand to list transactions lacking execution info. Includes options for specifying start order, output file path, and database directory. Helps identify duplicate transactions and analyze unexecuted transaction details.
cmd result:
for tx_order: `[0, 84658122]`, no execution info tx count: 283
=> feat(rooch-db): add ListEmptyCommand to identify unexecuted txs

crates/rooch-genesis/src/lib.rs, crates/rooch-sequencer/src/actor/sequencer.rs, crates/rooch-store/src/lib.rs, crates/rooch/src/commands/da/commands/mod.rs
Add a tx_order_checked flag and helper function to ensure transaction order continuity. This addresses potential inconsistencies caused by pipeline reverts, enhancing data integrity.
=> feat(rooch-sequencer): validate tx order continuity

crates/rooch/src/commands/da/commands/exec.rs, crates/rooch/src/commands/da/commands/mod.rs, crates/rooch/src/commands/da/commands/verify.rs, crates/rooch/src/commands/da/mod.rs
Introduce the `verify` command to validate transaction order in segments. This includes a new execution flow that checks expected vs. actual transaction orders and logs discrepancies.
output ( block: `[0,374435]`)
```
expected_tx_order,actual_tx_order,tx_hash,block_number
84658122,84658124,0x4854d82441239cda0805b963b404a007ecbc6366ce3fd4c37572cdb692624430,373386
84659999,84660000,0x44955c646f81defdcd4db2d038fc52f50949e943b59dc02757587f05e14ef007,373386
84706263,84706267,0xbb3bf39a48f85413e43f09de8a16b90237379f33abd77a8e6ea3c19ca96f2bc0,373392
84706265,84706267,0xbb3bf39a48f85413e43f09de8a16b90237379f33abd77a8e6ea3c19ca96f2bc0,373392
84706266,84706267,0xbb3bf39a48f85413e43f09de8a16b90237379f33abd77a8e6ea3c19ca96f2bc0,373392
```
=> feat(rooch-da): add verify command for segment order validation

scripts/deploy_rooch_mainnet.sh, scripts/deploy_rooch_testnet.sh
Update `rocksdb-row-cache-size` and `rocksdb-block-cache-size` parameters in mainnet and testnet deploy scripts to optimize resource allocation:
1. row-cache hit rate is low, reduce size
2. increase block-cache size gain better performance in real data test
=> ci(deploy-scripts): adjust rocksdb cache size configurations

crates/rooch-executor/src/actor/messages.rs, crates/rooch-executor/src/actor/reader_executor.rs, crates/rooch-executor/src/proxy/mod.rs, crates/rooch-open-rpc-spec/schemas/openrpc.json, crates/rooch-rpc-api/src/api/mod.rs, crates/rooch-rpc-api/src/api/rooch_api.rs, crates/rooch-rpc-server/src/server/rooch_server.rs, crates/rooch-rpc-server/src/service/rpc_service.rs, crates/rooch-store/src/lib.rs, crates/rooch-store/src/state_store/mod.rs, crates/rooch/src/commands/db/commands/changeset.rs, crates/rooch/src/commands/db/commands/mod.rs, crates/rooch/src/commands/db/mod.rs
1. Support changeset cmd to verify data
2. Fixup has next page flag when asc order for tx and change set rpc
3. Verifying data based on rooch_syncStates RPC is too slow, so provide a new change set RPC for verify data
- Closes #3341
=> Verify state change set data

Cargo.lock, crates/rooch-executor/src/actor/executor.rs, crates/rooch-relayer/src/actor/relayer.rs, crates/rooch-types/Cargo.toml, crates/rooch-types/src/bitcoin/mod.rs, crates/rooch-types/src/bitcoin/transaction_validator.rs, crates/rooch-types/src/error.rs, crates/rooch/src/commands/move_cli/commands/run_function.rs, frameworks/bitcoin-move/doc/README.md, frameworks/bitcoin-move/doc/bitcoin.md, frameworks/bitcoin-move/doc/transaction_validator.md, frameworks/bitcoin-move/sources/bitcoin.move, frameworks/bitcoin-move/sources/transaction_validator.move
1. Validate the l1 tx before execution, if it already execute, skip the tx.
2. rooch move run support sequence-number argument 
- Closes #2763 #3318
=> Validate the l1 tx before execution

Cargo.lock, crates/rooch-sequencer/tests/test_sequencer.rs, moveos/moveos-store/src/tests/test_state_store.rs, moveos/raw-store/Cargo.toml, moveos/raw-store/src/lib.rs, moveos/raw-store/src/rocks/mod.rs
1. use HyperClockCache, replace LRU for saving ~5% CPU time
2. rm useless row cache, helpless
3. rm rocksdb stats collection, because the high CPU cost by PerfContext, and we don't need it at this stage. (the I/O releated metrics are reserved)
with rocksdb stats collection:
```
13.86%  rooch                                           [.] TLS init function for rocksdb::perf_context
```
- Closes #1588
=> feat(rocks): introduce HyperClockCache 

frameworks/moveos-stdlib/doc/account.md, frameworks/moveos-stdlib/sources/account.move
1. Provide AccountCap to create a contract account.
2. Deprecated original `create_account` function, the `Object<Account>` should not be held in another struct.
=> [moveos_std] Add AccountCap for contract account

frameworks/moveos-stdlib/doc/decimal_value.md, frameworks/moveos-stdlib/sources/decimal_value.move, frameworks/moveos-stdlib/sources/json.move, frameworks/moveos-stdlib/src/natives/moveos_stdlib/json.rs, moveos/moveos-types/src/addresses.rs, moveos/moveos-types/src/moveos_std/decimal_value.rs
1. Decimal value in json default use number, The value is too big to be represented in float, it will be represented in string
2. `from_json` supports both hex address and `rooch` prefix bech32 address.
=> [moveos_std] Refactor json for address and decimal value

examples/pump_rooch/Move.toml, examples/pump_rooch/sources/bonding_curve.move, examples/pump_rooch/sources/math/fixed_point64.move, examples/pump_rooch/sources/math/legato_math.move, examples/pump_rooch/sources/math/math128.move, examples/pump_rooch/sources/math/math_fixed64.move
- The exponential bonding curve formula is used, where the price increases exponentially with the supply. The rate of growth accelerates as the supply increases.
$$ P = a \times e^{b \times S} $$
- Using FixedPoint64 to handle DecimalValue, if either the integer part or the fractional part exceeds U64Max, an exception will occur. This issue can be avoided by restricting the token's information.
=> [example] pump bonding_curve

frameworks/framework-builder/src/releaser.rs, frameworks/moveos-stdlib/src/natives/moveos_stdlib/move_module.rs, third_party/move/language/move-binary-format/src/compatibility.rs, third_party/move/language/testing-infra/transactional-test-runner/src/vm_test_harness.rs, third_party/move/language/tools/move-cli/src/sandbox/utils/mod.rs
1. expose the `check_struct_and_pub_function_linking` config
2. Set `check_friend_linking` to false.
resolve the bug introduced from #3465 and #3473
=> [move] Fix compat check config and allow friend function break

Cargo.lock, Cargo.toml, crates/rooch-types/src/framework/auth_payload.rs, moveos/moveos-store/src/event_store/mod.rs, moveos/moveos-types/src/state_resolver.rs
1. Return empty result for list rpc if object not exists
2. Unlock the bitcoin version and Bump bitcoin from 0.32.3 to 0.32.5
- Closes #3491 #2853
=> Handle empty result for list rpc and fixup bitcoin bump error

frameworks/bitcoin-move/sources/bitcoin.move
Skip the Bitcoin time in testnet, Because the testnet block time is not accurate
=> [bitcoin-move] Skip the bitcoin time in testnet

sdk/typescript/rooch-sdk-kit/src/components/fauct-modal/views/FaucetView.tsx, sdk/typescript/rooch-sdk/src/client/client.ts, sdk/typescript/rooch-sdk/src/client/types/generated.ts, sdk/typescript/rooch-sdk/src/client/types/params.ts
Fixed https://github.com/rooch-network/rooch/pull/3478. Changing decoded_value to object type causes rooch sdk compilation error.
=> feat: fix decoded_value as object type causes compilation error

sdk/typescript/rooch-sdk/.gitignore, sdk/typescript/rooch-sdk/src/crypto/signatureScheme.ts, sdk/typescript/rooch-sdk/src/keypairs/secp256k1/keypair.test.ts, sdk/typescript/rooch-sdk/src/keypairs/secp256k1/keypair.ts, sdk/typescript/rooch-sdk/src/keypairs/secp256k1/publickey.ts, sdk/typescript/rooch-sdk/vitest.config.js
Add signature signing and verification based on secp256k1 32 bytes public key size.
- Closes #3555
=> sdk/typescript: add schnorr signature support to typescript sdk.

examples/nostr/README.md, examples/nostr/sources/event.move
Clean code and fix typos according to https://github.com/rooch-network/rooch/pull/3590#pullrequestreview-2849013315 for Nostr in Move.
- Closes #3376.
=> [gh-3376] docs: clean code and update readme to fix typos.

crates/rooch/src/commands/account/commands/mod.rs, crates/rooch/src/commands/account/commands/object.rs, crates/rooch/src/commands/account/mod.rs, crates/testsuite/features/cmd.feature
Add `rooch account object` command to show objects of a holding account on rooch network.
- Closes #3632.
=> [gh-3632] commands/account: account object.
