rooch-network/rooch

crates/framework/mos-stdlib/sources/any.move
crates/framework/mos-stdlib/sources/bcd.move
crates/framework/mos-stdlib/sources/copyable_any.move

Add any, copyable_any modules

---

.github/workflows/rust.yml
crates/framework/src/natives/mos_stdlib/type_info.rs

Add github action ci with cargo fmt, clippy, test.
But it is not mandatory to match the requirements to submit the merge。

Add github action ci with cargo fmt, clippy, test

---

Cargo.toml
moveos/moveos-stdlib/Cargo.toml
moveos/moveos-stdlib/moveos-stdlib/sources/any_table.move
moveos/moveos-stdlib/src/natives/mod.rs
moveos/moveos-stdlib/src/natives/moveos_stdlib/any_table/mod.rs
moveos/moveos-stdlib/src/natives/moveos_stdlib/mod.rs

Introduce any_table
A table can store any type of value. 
This is part of #20 
We need this to implement ObjectStore and UserResourceStore( replace #19 )

[moveos] Introduce any_table

---

moveos/moveos-common/src/error/mod.rs

Optimized the ConfigReadError message

---

Cargo.toml
crates/rooch-types/Cargo.toml
crates/rooch-types/src/address.rs
crates/rooch-types/src/coin.rs
crates/rooch-types/src/lib.rs
crates/rooch-types/src/transaction/authenticator.rs
crates/rooch-types/src/transaction/ethereum.rs
crates/rooch-types/src/transaction/mod.rs
crates/rooch-types/src/transaction/rooch.rs
moveos/moveos-types/src/transaction.rs
moveos/moveos-types/src/tx_context.rs
moveos/smt/src/lib.rs

1. Define Address Types. Try to support MultiChainAddress. RoochAddress, EthereumAddress, BitcoinAddress.
2. Define Rooch transaction and Authenticator, and introduce the crypto library.
This is part of #72

[types] Define Address types and Authenticator

---

moveos/moveos-client/src/client.rs
moveos/moveos-client/src/lib.rs

This PR following the issue https://github.com/rooch-network/rooch/issues/41
Implemented the abstract interfaces related to Sequencer and Proposer as mentioned in the issue, but the concrete implementation of the traits is not yet available. The user needs to implement this trait.

Added abstract interface for sequencer.

---

Cargo.toml
crates/rooch-integration-test-runner/src/lib.rs
examples/basic_object_example/Move.toml
examples/basic_object_example/sources/something.move
examples/basic_object_example/sources/something_aggregate.move
examples/basic_object_example/sources/something_do_logic.move
moveos/moveos-cli/src/commands/publish.rs
moveos/moveos/Cargo.toml
moveos/moveos/src/vm/dependency_order.rs
moveos/moveos/src/vm/mod.rs

An error will be reported when deploying multiple contracts, resolve https://github.com/rooch-network/rooch/issues/116
`
VMError with status LINKER_ERROR at location UNDEFINED and message Cannot find ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000123, name: Identifier("something_do_logic") } in data cache
`
Ω

fix dependency order when package publish

---

.github/workflows/check_build_test.yml
crates/rooch-server/src/lib.rs
crates/rooch/src/commands/server.rs
crates/testsuite/tests/integration.rs
scripts/pr.sh

Integration fix

---

crates/rooch-server/src/actor/executor.rs
crates/rooch-types/src/address.rs
crates/rooch-types/src/transaction/authenticator.rs
crates/rooch-types/src/transaction/ethereum.rs
crates/rooch-types/src/transaction/mod.rs
crates/rooch-types/src/transaction/rooch.rs
moveos/moveos-stdlib/moveos-stdlib/sources/bcd.move
moveos/moveos-stdlib/rooch-framework/sources/account.move
moveos/moveos-stdlib/rooch-framework/sources/authenticator.move
moveos/moveos-types/src/transaction.rs
moveos/moveos/Cargo.toml
moveos/moveos/src/moveos.rs

[moveos] Refactor Authenticator and define account:validate function

---

Cargo.toml
crates/rooch-proposer/Cargo.toml
crates/rooch-proposer/src/actor/messages.rs
crates/rooch-proposer/src/actor/mod.rs
crates/rooch-proposer/src/actor/proposer.rs
crates/rooch-proposer/src/lib.rs
crates/rooch-proposer/src/proxy/mod.rs
crates/rooch-proposer/src/scc/mod.rs
crates/rooch-sequencer/src/actor/messages.rs
crates/rooch-sequencer/src/actor/sequencer.rs
crates/rooch-sequencer/src/proxy/mod.rs
crates/rooch-server/src/lib.rs
crates/rooch-server/src/service/mod.rs
crates/rooch-types/src/block.rs
crates/rooch-types/src/lib.rs
crates/rooch-types/src/transaction/mod.rs

resolve #162 
```
submit_tx  --> validate_tx --> 
sequence_tx( =>TransactionSequenceInfo) --> 
execute_tx( => TransactionExecutionInfo) --> 
propose_tx( => Block)
```
TODO rename TransactionInfo to TransactionExecutionInfo

[Proposer] Define Proposer Basic API and Data Struct

---

moveos/moveos-verifier/src/metadata.rs

According to issue https://github.com/rooch-network/rooch/issues/152, the function to check the parameters of the entry function has been implemented.
If the function is an entry function, the following checks will be performed:
- Check the type of the parameters to see if they meet the requirements.
- The function cannot have a return value.
Currently, the type of function parameters can only be one of the following types (more types can be added if necessary):
1. `PrimitiveType`
```rust
pub enum PrimitiveType {
Bool,
U8,
U16,
U32,
U64,
U128,
U256,
Address,
Signer,
Num,
Range,
EventStore,
}
```
2. `Vector<PrimitiveType>`
3. `0x1::string::String`
4. `0x1::object_id::ObjectID`

Implement the parameter and return value checking for the entry function.

---

kube/autoscaler/cluster-autoscaler-autodiscover.yaml
kube/autoscaler/cluster-autoscaler-policy.json
kube/autoscaler/create_autoscaler_policy.sh
kube/runner/deploy_ARC.sh
kube/runner/runner-service-account.yaml
kube/runner/runner.yaml

self host the CI node

---

crates/rooch-client/src/lib.rs
crates/rooch-types/src/transaction/ethereum.rs
crates/rooch/src/commands/move_cli/commands/publish.rs
crates/rooch/src/commands/move_cli/commands/run_function.rs
moveos/moveos-stdlib/moveos-stdlib/sources/tx_context.move
moveos/moveos-stdlib/rooch-framework/sources/transaction_validator.move
moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs

resolve https://github.com/rooch-network/rooch/issues/141

unify txn to tx

---

crates/rooch-client/src/lib.rs
crates/rooch-sequencer/Cargo.toml
crates/rooch-sequencer/src/actor/messages.rs
crates/rooch-sequencer/src/actor/mod.rs
crates/rooch-sequencer/src/actor/sequencer.rs
crates/rooch-sequencer/src/actor/transaction_list.rs
crates/rooch-sequencer/src/lib.rs
crates/rooch-sequencer/src/messages.rs
crates/rooch-sequencer/src/proxy/mod.rs
crates/rooch-sequencer/src/store/mem_storage.rs
crates/rooch-sequencer/src/store/mod.rs
crates/rooch-sequencer/src/store/storage.rs
crates/rooch-server/src/api/rooch_api.rs
crates/rooch-server/src/jsonrpc_types/mod.rs
crates/rooch-server/src/jsonrpc_types/move_types.rs
crates/rooch-server/src/jsonrpc_types/rooch_types.rs
crates/rooch-server/src/lib.rs
crates/rooch-server/src/server/rooch_server.rs
crates/rooch-server/src/service/mod.rs
crates/rooch/Cargo.toml
crates/rooch/src/commands/mod.rs
crates/rooch/src/commands/transaction/commands/get_by_hash.rs
crates/rooch/src/commands/transaction/commands/get_by_index.rs
crates/rooch/src/commands/transaction/commands/mod.rs
crates/rooch/src/commands/transaction/mod.rs
crates/rooch/src/lib.rs
crates/testsuite/features/cmd.feature

1.getTransactionByHash(vec[hash])
2.getTransactionByIndex(start, limit)
TODO:Optimize the executeTransaction Response

[RPC] Transaction RPC#229

---

crates/rooch-client/src/lib.rs
crates/rooch-client/src/wallet_context.rs
crates/rooch-executor/src/actor/messages.rs
crates/rooch-executor/src/proxy/mod.rs
crates/rooch-server/src/api/rooch_api.rs
crates/rooch-server/src/jsonrpc_types/execute_tx_response.rs
crates/rooch-server/src/jsonrpc_types/mod.rs
crates/rooch-server/src/jsonrpc_types/move_types.rs
crates/rooch-server/src/jsonrpc_types/rooch_types.rs
crates/rooch-server/src/jsonrpc_types/table_view.rs
crates/rooch-server/src/server/rooch_server.rs
crates/rooch-server/src/service/mod.rs
crates/rooch/src/commands/account/commands/create.rs
crates/rooch/src/commands/move_cli/commands/publish.rs
crates/rooch/src/commands/move_cli/commands/run_function.rs
crates/rooch/src/commands/move_cli/commands/unit_test.rs
crates/testsuite/features/cmd.feature
moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs
moveos/moveos-store/src/state_store/mod.rs
moveos/moveos-types/src/function_return_value.rs
moveos/moveos-types/src/lib.rs
moveos/moveos-types/src/object.rs
moveos/moveos-types/src/table.rs
moveos/moveos-types/src/transaction.rs
moveos/moveos/src/moveos.rs
moveos/moveos/src/vm/mod.rs
moveos/moveos/src/vm/move_vm_ext.rs

resolve #239 
1. Add TransactionOutput to the response.
2. Define TransactionSequenceInfoView and TransactionExecutionView.
3. Make all enum json to lowercase.
```bash
rooch account create
```
```json
{
"sequence_info": {
"tx_order": "1",
"tx_order_signature": {
"scheme": "0",
"payload": "0x61001bb17db59d37e35723f4b1f00f26507d943288327e80974abf798c9d67aa289c06a2fba87140e06c2a8df4a455dea1d80c8f0231908167137aa698e0f3de43021b1a13924bdd6998f0ebfd625c1e51d523e6699e1375dc007f08b70732a74409"
},
"tx_accumulator_root": "0x28aeb30c651779517c1e2daceba0cc8a58f1ccad7cac7ec812a5149a19ace482"
},
"execution_info": {
"tx_hash": "0x252c1101b882ea89e69cf36aea5ede66f7398f46866f42f064da7fd1e5411f4e",
"state_root": "0x18206726bfbcc0d6746e82c967cb0119c5593e76b0f7a778a454ff560ef7cbcf",
"event_root": …
```

[rpc] Optimize executeTransaction response

---

moveos/moveos-store/src/event_store/mod.rs

resolve https://github.com/rooch-network/rooch/issues/249

fix event query bug which result is null

---

crates/rooch-types/src/transaction/authenticator.rs

[build] fix project build cargo

---

crates/rooch-client/src/lib.rs
crates/rooch-server/src/api/rooch_api.rs
crates/rooch-server/src/jsonrpc_types/rooch_types.rs
crates/rooch-server/src/server/rooch_server.rs
crates/rooch/src/commands/event.rs
moveos/moveos-store/src/event_store/mod.rs

resolve https://github.com/rooch-network/rooch/issues/264
```
curl --location 'http://localhost:50051' \
--header 'Content-Type: application/json' \
--data '{
"id": 101,
"jsonrpc": "2.0",
"method": "rooch_getEventsByEventHandle",
"params": [
"0xb4321fa441b5d9fdefb71f82856a56447451f7b1ba9478747b07e9f26b34c87::something::SomethingCreated", 1, 2
]
}'
```
```
{
"jsonrpc": "2.0",
"result": {
"data": [
{
"event": {
"event_id": {
"event_handle_id": "0xebe6b25007d2d52a8245b21d654b015726ae6f5edff9001ec4a529322885588e",
"event_seq": 1
},
"type_tag": "0xb4321fa441b5d9fdefb71f82856a56447451f7b1ba9478747b07e9f26b34c87::something::SomethingCreated",
"event_data": "0x65fce64c60e5409f628dae9ff89ba3e4b110b54adbc71bf43a44f292af8ab2100100000002000000000000000000000000000000",
"event_index": 3
},
"sender": …
```

implement Page for jsonrpc

---

moveos/moveos-verifier/src/metadata.rs
moveos/moveos-verifier/src/verifier.rs
moveos/moveos/src/vm/moveos_vm.rs

Refactored the verification for the runtime init function and removed the dependency of the validation function on the `Session`.
resolve https://github.com/rooch-network/rooch/issues/244.

Refactored the validation for the runtime init function.

---

.github/actions/rust-setup/action.yaml
.github/workflows/check_build_test.yml

try to fix .github/actions/rust-setup/action.yaml (Line: 19, Col: 28): Unrecognized named-value: 'secrets'
need to bypass branch protections

need to bypass branch protections, fix action yaml secrets error

---

crates/rooch-framework-tests/tests/cases/entry_function/entry_function_invalid_struct.exp
crates/rooch-framework-tests/tests/cases/entry_function/entry_function_invalid_struct.move
crates/rooch-framework-tests/tests/cases/entry_function/entry_function_valid_reference.exp
crates/rooch-framework-tests/tests/cases/entry_function/entry_function_valid_reference.move
crates/rooch-framework-tests/tests/cases/entry_function/entry_function_valid_struct.exp
crates/rooch-framework-tests/tests/cases/entry_function/entry_function_valid_struct.move
crates/rooch-framework-tests/tests/cases/entry_function/entry_function_with_return_value.exp
crates/rooch-framework-tests/tests/cases/entry_function/entry_function_with_return_value.move

[Testing] Test cases for runtime entry function verification.

---

crates/rooch-open-rpc/spec/openrpc.json
crates/rooch-open-rpc/src/lib.rs
crates/rooch-server/src/api/rooch_api.rs
crates/rooch-server/src/jsonrpc_types/execute_tx_response.rs
crates/rooch-server/src/jsonrpc_types/move_types.rs
crates/rooch-server/src/jsonrpc_types/rooch_types.rs
crates/rooch-server/src/server/rooch_server.rs
moveos/moveos-types/src/lib.rs
moveos/moveos-types/src/serde.rs
scripts/generate_json_rpc_spec.sh

add generate_json_rpc_spec.sh
add generate_json_rpc_spec test
If the test fails, it will prompt you to call generate_json_rpc_spec.sh to update openrpc.json

fix 275 comments

---

.github/workflows/check_build_test.yml
crates/rooch/src/commands/move_cli/commands/unit_test.rs
examples/basic_object_example/Move.toml
examples/counter/Move.toml
examples/event_example/Move.toml
examples/kv_store/Move.toml
examples/module_init_example/Move.toml
examples/private_generics/Move.toml
examples/private_generics/sources/private_generics.move

[CI] Auto test the example projects in CI

---

crates/rooch/src/commands/move_cli/commands/new.rs
crates/rooch/src/commands/move_cli/mod.rs

[cli] add rooch move new --address var.

---

crates/rooch-framework/sources/account.move

[Testing] UnitTest for rooch_framework::account  Fixes #195

---

moveos/moveos-stdlib/moveos-stdlib/sources/account_storage.move

The logic here is reversed and should be fixed

Fix account_storage::remove_resource_from_account_storage

---

CONTRIBUTING.md
crates/rooch-framework/sources/authenticator.move
docs/contribute/coding-conventions.md
moveos/moveos-stdlib/moveos-stdlib/sources/account_storage.move
moveos/moveos-stdlib/moveos-stdlib/sources/object.move
moveos/moveos-stdlib/moveos-stdlib/sources/object_storage.move
moveos/moveos-stdlib/moveos-stdlib/sources/storage_context.move

[naming] unify this in function parameters to self, fix and add docs.

---

crates/rooch-framework/sources/account.move
moveos/moveos-stdlib/moveos-stdlib/sources/account_storage.move

[Testing] moveos_stdlib::account_storage

---

crates/rooch-integration-test-runner/tests/cases/private_generics_direct_call.exp
crates/rooch-integration-test-runner/tests/cases/private_generics_direct_call.move
crates/rooch-integration-test-runner/tests/cases/private_generics_indirect_call.exp

[integration-test-runner] refactor and add private_generics tests.

---

Cargo.toml
crates/rooch-open-rpc/spec/openrpc.json
crates/rooch-open-rpc/src/generate_json_rpc_spec.rs

1. [Build] Change release config, make debug false
2. [Documents] Change the json rpc email

[Build] Change release config, make debug false

---

.github/workflows/release_asset.yml

try to make the binary smaller

fix ubuntu release

---

moveos/moveos-verifier/src/verifier.rs

resolve https://github.com/rooch-network/rooch/issues/286.

check entry function at module publish

---

.github/workflows/check_licenses.yml

[ci] add SPDX-License-Identifier license checks.

---

examples/blog_example/README.md
examples/blog_example/README_CN.md
examples/blog_example/dddml/blog.yaml
examples/blog_example/sources/article.move
examples/blog_example/sources/article_add_comment_logic.move
examples/blog_example/sources/article_aggregate.move
examples/blog_example/sources/comment.move

Add instructions for "Implementing Custom Business Logic" in the blog_example README.
And update demo code of `article_add_comment_logic.move`.

Add instructions for "Implementing Custom Business Logic" in blog_example

---

crates/rooch-integration-test-runner/src/lib.rs
crates/rooch-key/src/key_derive.rs
crates/rooch-open-rpc/src/lib.rs
crates/rooch-rpc-api/src/api/eth_api.rs
crates/rooch-rpc-client/src/wallet_context.rs
crates/rooch-types/src/crypto.rs
crates/rooch/src/cli_types.rs
crates/rooch/src/commands/account/mod.rs
crates/rooch/src/commands/move_cli/commands/integration_test.rs
crates/rooch/src/commands/move_cli/commands/run_function.rs
crates/rooch/src/commands/move_cli/mod.rs
crates/testsuite/tests/integration.rs
moveos/moveos-stdlib-builder/src/lib.rs
moveos/moveos-verifier/src/metadata.rs
moveos/moveos-verifier/src/verifier.rs
moveos/moveos/src/moveos_test_runner.rs
moveos/smt/src/tests.rs

This PR changes calling from to_string to to_owned for string literals.
Resolve #409

[refactor] to_string to to_owned str literals.

---

.github/workflows/docker_build.yml
docker/Dockerfile

Docker img

---

crates/rooch-types/Cargo.toml
moveos/moveos-types/Cargo.toml
moveos/moveos-types/src/move_types.rs
moveos/moveos-types/src/transaction.rs

Use proptest to achieve random generation of MoveAction
Related Issue: https://github.com/rooch-network/rooch/issues/140

Feature owen mock move action

---

docs/website/README.md

Fix: typos

---

crates/rooch-rpc-client/src/wallet_context.rs
crates/rooch/src/cli_types.rs
crates/rooch/src/commands/move_cli/commands/run_function.rs
examples/noop_auth_validator/Move.toml
examples/noop_auth_validator/README.md
examples/noop_auth_validator/sources/noop_validator.move

A simple do nothing auth validator
part of #467

[Example] NoOpAuthValidator

---

.github/workflows/check_build_test.yml

the scripts dir should not be ignored

---

crates/rooch/src/commands/move_cli/commands/explain.rs

#resolve https://github.com/rooch-network/rooch/issues/550.

Extract the category from the abort code.

---

crates/rooch-executor/src/actor/executor.rs
crates/rooch-executor/src/actor/messages.rs
crates/rooch-executor/src/proxy/mod.rs
crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/api/rooch_api.rs
crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs
crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-rpc-server/src/service/mod.rs
moveos/moveos-store/src/lib.rs
moveos/moveos-store/src/state_store/statedb.rs
moveos/moveos-types/src/lib.rs
moveos/moveos-types/src/list_access_path.rs
moveos/moveos-types/src/state_resolver.rs
moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs
moveos/smt/src/lib.rs

resolve https://github.com/rooch-network/rooch/issues/543
Two interfaces `listStates` and `listAnnotatedStates` are provided, which support state traversal in the following format:
```
1. /resource/$account_address
2. /module/$account_address
3. /table/$table_handle
```
Example 1
```
curl --location 'http://localhost:50051' \
--header 'Content-Type: application/json' \
--data '{
"id":101, 
"jsonrpc":"2.0", 
"method":"rooch_listStates", 
"params":["/resource/0xb4321fa441b5d9fdefb71f82856a56447451f7b1ba9478747b07e9f26b34c87",null, 5]
}'
```
```
{
"jsonrpc": "2.0",
"result": {
"data": [
{
"value": "0x0600000000000000",
"value_type": "0x3::account::Account"
}
],
"next_cursor": "0x5230303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303 …
```

Support the iterate query for statedb

---

crates/rooch/src/commands/account/commands/create.rs
crates/rooch/src/commands/account/commands/import.rs
crates/rooch/src/commands/init.rs
crates/testsuite/features/cmd.feature

[gh-556] clear schemes for init create and import.

---

.github/CODEOWNERS

[Github] Setting code owners

---

moveos/moveos-store/src/state_store/statedb.rs
moveos/moveos-types/src/move_types.rs
moveos/moveos-types/src/object.rs
moveos/moveos-types/src/state.rs
moveos/smt/src/lib.rs

part of https://github.com/rooch-network/rooch/issues/544

provide statedb dumping

---

crates/rooch-framework-tests/src/binding_test.rs
crates/rooch-key/src/keystore.rs

Extract BaseKeyStore, eliminate the repeated logic of FileBasedKeyStore and InMemoryKeyStore. cc @feliciss

[CLI] Extract KeyStore logic to BaseKeyStore

---

crates/rooch-framework/doc/auth_validator.md
crates/rooch-framework/doc/ecdsa_k1_recoverable_validator.md
crates/rooch-framework/doc/ecdsa_k1_validator.md
crates/rooch-framework/doc/ed25519_validator.md
crates/rooch-framework/doc/schnorr_validator.md
crates/rooch-framework/doc/transaction_validator.md
crates/rooch-framework/sources/auth_validator/auth_validator.move
crates/rooch-framework/sources/auth_validator/ecdsa_k1_recoverable_validator.move
crates/rooch-framework/sources/auth_validator/ecdsa_k1_validator.move
crates/rooch-framework/sources/auth_validator/ed25519_validator.move
crates/rooch-framework/sources/auth_validator/schnorr_validator.move
crates/rooch-framework/sources/transaction_validator.move
examples/noop_auth_validator/sources/noop_validator.move

Just rename the argument for more clarity.

[Framework]Unify the payload argument to authentiactor_payload

---

Cargo.toml
crates/rooch-integration-test-runner/src/lib.rs
crates/rooch/Cargo.toml
crates/rooch/src/commands/move_cli/commands/unit_test.rs
moveos/moveos-stdlib/Cargo.toml
moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs
moveos/moveos-store/src/state_store/statedb.rs
moveos/moveos-types/src/state.rs
moveos/moveos/Cargo.toml
moveos/moveos/src/moveos.rs
moveos/moveos/src/vm/data_cache.rs
moveos/moveos/src/vm/moveos_vm.rs
moveos/moveos/src/vm/unit_tests/data_cache_tests.rs
moveos/moveos/src/vm/unit_tests/mod.rs
moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs

Trying to use `TableData` as MoveosDataCache. resolve #399

Use TableData as MoveosDataCache backend

---

crates/rooch-framework-tests/tests/cases/global_storage_access/move_to.exp
crates/rooch-framework-tests/tests/cases/global_storage_access/move_to.move
crates/rooch-framework-tests/tests/cases/private_generics/outside_module.move
moveos/moveos-stdlib/moveos-stdlib/sources/table.move
moveos/moveos-verifier/src/metadata.rs

This is part of  https://github.com/rooch-network/rooch/issues/248

disable all built-in instruction related to global storage

---

docs/website/pages/docs/developer/rooch-cli.en-US.mdx
docs/website/pages/docs/developer/rooch-cli.zh-CN.mdx

[gh-574] add docs for the rooch account command.

---

sdk/typescript/tools/generator/generator.js
sdk/typescript/tools/generator/mapping.js
sdk/typescript/tools/generator/template/client.ts.ejs
sdk/typescript/tools/generator/template/name_mapping.json
sdk/typescript/tools/generator/template/types.ts.ejs
sdk/typescript/tools/generator/utils.js

1、Automatically generate type annotations
2、Support type alias configuration

Feature owen opt client code gen

---

moveos/moveos-verifier/src/verifier.rs

This is part of https://github.com/rooch-network/rooch/issues/248.

Detecting global storage instructions during module publishing.

---

CONTRIBUTING-zh.md
CONTRIBUTING.md
README.md

refine README.md

---

examples/blog/README.md
examples/blog/README_CN.md

Fixed single quote error in shell scripts.
Optimized other descriptions.

Update blog example READMEs

---

moveos/moveos/src/gas/mod.rs
moveos/moveos/src/gas/table.rs
moveos/moveos/src/lib.rs
moveos/moveos/src/moveos.rs
moveos/moveos/src/vm/moveos_vm.rs
moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs

this is part of https://github.com/rooch-network/rooch/issues/633.
Implemented GasMeter for runtime calls in VM.
TODO:
Analyze and continue implementing CostTable.

Implemented GasMeter for runtime calls in VM.

---

kube/runner/runner.yaml

update runner manifest for GKE

update runner manifest for GKE

---

Cargo.toml
moveos/moveos-stdlib/src/natives/moveos_stdlib/move_module.rs

Verify modules with verifier verifier in native functions.
- Closes #647

Verify module with MoveVM verifier

---

crates/rooch/src/commands/move_cli/commands/publish.rs
crates/testsuite/features/cmd.feature

Publish modules through move entry function as default.
part of #703 

publish modules in move as default

---

moveos/moveos/src/gas/table.rs
moveos/moveos/src/moveos.rs
moveos/moveos/src/vm/moveos_vm.rs
moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs

resolve https://github.com/rooch-network/rooch/issues/633.

Calculate gas consumption after executing transactions in the VM.

---

Cargo.lock
crates/rooch-config/Cargo.toml
crates/rooch-framework/sources/coin.move
crates/rooch-key/Cargo.toml
crates/rooch-types/Cargo.toml
crates/rooch-types/src/chain_id.rs
crates/rooch-types/src/transaction/rooch.rs
crates/rooch/Cargo.toml
examples/private_generics/sources/private_generics.move
moveos/metrics/Cargo.toml
moveos/moveos-commons/accumulator/Cargo.toml
moveos/moveos-store/Cargo.toml
moveos/moveos-types/Cargo.toml

1, change dev as  default chain id, relative   https://github.com/rooch-network/rooch/issues/722
2, fixup warning when CI check

make dev as  default chain id and fixup warning when CI check

---

crates/rooch-framework/doc/coin.md
crates/rooch-framework/sources/account.move
crates/rooch-framework/sources/coin.move
crates/rooch-framework/sources/tests/coin_test.move
crates/rooch-framework/sources/tests/gas_coin_test.move
crates/rooch-rpc-server/src/lib.rs
crates/testsuite/features/cmd.feature
examples/coins/Move.toml
examples/coins/sources/fixed_supply_coin.move
examples/coins/sources/private_coin.move

* Rename `coin::is_coin_registered` -> `coin::is_registered`.
* Provide two coin examples:
1. Fixed supply coin
2. Private coin
This coins project encounters an error when publishing #742 
- Closes #741

[Examples] Coin examples

---

crates/rooch-config/src/lib.rs
crates/rooch-config/src/server_config.rs
crates/rooch-rpc-server/src/lib.rs
crates/rooch/src/commands/server/commands/clean.rs
crates/rooch/src/commands/server/commands/start.rs

adds custom port support to rooch server
- Closes #692

add custom port to `rooch server start`

---

docs/website/package.json
docs/website/theme.config.tsx

fix(website): update the edit button of website document

---

crates/rooch-framework-tests/tests/cases/init_function/init_function_invalid.exp
crates/rooch-framework-tests/tests/cases/init_function/init_function_invalid.move
crates/rooch-framework-tests/tests/cases/init_function/init_function_valid.exp
crates/rooch-framework-tests/tests/cases/init_function/init_function_valid.move

[Verification] Test cases for runtime init function verification.

---

moveos/moveos-stdlib/moveos-stdlib/doc/account_storage.md
moveos/moveos-stdlib/moveos-stdlib/sources/account_storage.move
moveos/moveos/src/moveos.rs

1. Fix publishing error when there are more than one modules in the package.
2. Fix user action error after session respawn.
- Closes #775

Fix publish error

---

moveos/moveos-commons/moveos-common/src/utils.rs
moveos/raw-store/src/rocks/mod.rs

[Fix Windows Build] Add Error Type In check_open_fds_limit To Fix windows build error

---

dashboard/src/@core/layouts/components/shared-components/UserDropdown.tsx
dashboard/src/context/auth/AuthContext.tsx
dashboard/src/context/types.ts
dashboard/src/context/wallet/MetamaskContext.tsx
dashboard/src/pages/login/index.tsx

fix secretKey import
add rememberMe
remove account manager

fix dashboard login & account manager

---

crates/rooch-rpc-client/src/client_config.rs
crates/rooch/src/commands/env/commands/switch.rs
crates/rooch/src/commands/init.rs

env add test net

---

.github/workflows/deploy_frontend.yml

deploy frontend workflow

---

crates/rooch-rpc-client/src/client_config.rs

Fix Rooch Testnet URL.
- Closes #851

[gh-851] fix testnet url link.

---

Cargo.lock
Cargo.toml
moveos/moveos/src/moveos_test_model_builder.rs
moveos/moveos/src/moveos_test_runner.rs

Remove temporary files generated by the `publish` and `run` commands in the integration tests.
**Approve this https://github.com/rooch-network/move/pull/10 PR first, which is dependent on it.**

Remove all temporary files from the integration tests.

---

docs/website/pages/docs/developer-guides/installation.en-US.mdx
docs/website/pages/docs/developer-guides/installation.zh-CN.mdx

[Docs] Add Windows installation Doc

---

docs/website/pages/blog/multi-chain_settlement_by_layer2-myth_or_Reality.en-US.mdx

fix multi-chain settlement by layer2 img path issue

docs(blog): fix multi-chain settlement by layer2 img path issue

---

.github/workflows/docker_build.yml

fix deploy docker

---

.github/workflows/docker_build.yml

fix docker deploy

---

.github/workflows/docker_build.yml

fix deploy docker by using the Docker image version

fix deploy docker by using the Docker image version

---

moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs
moveos/moveos-store/src/lib.rs
moveos/moveos-store/src/state_store/statedb.rs
moveos/moveos-types/src/state_resolver.rs
moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs

Refactor StateResolver to distinguish Object and Table
- Closes #909

refactor StateResolver

---

crates/rooch-framework/doc/README.md
crates/rooch-framework/doc/bcs.md
crates/rooch-framework/doc/ethereum_light_client.md
crates/rooch-framework/sources/bcs.move
crates/rooch-framework/sources/ethereum_light_client.move
crates/rooch-framework/src/natives/gas_parameter/bcd.rs
crates/rooch-framework/src/natives/gas_parameter/native.rs
crates/rooch-framework/src/natives/mod.rs
crates/rooch-framework/src/natives/rooch_framework/bcs.rs
crates/rooch-framework/src/natives/rooch_framework/mod.rs

resolve https://github.com/rooch-network/rooch/issues/919

Restrict the invocation of bcs::from_bytes to the current address only.

---

.github/workflows/docker_build.yml

add the missing docker pull step

miss the pulling image step

---

.github/workflows/deploy_examples.yml
scripts/deploy_examples.sh

auto deploy examples to rooch dev network
#892

auto deploy examples

---

.github/workflows/docker_build.yml
scripts/check_dev_deploy_status.sh

check deploy status if not running, clean data and redeploy the examples

---

scripts/check_dev_deploy_status.sh

fix relative path  when deploy examples to dev network

fix relative path and add a todo for the later rooch init feature

---

.github/workflows/check_build_test.yml
crates/rooch-key/src/key_derive.rs
crates/rooch-key/src/keystore.rs
crates/rooch-rpc-client/src/client_config.rs
crates/rooch-rpc-client/src/wallet_context.rs
crates/rooch-types/src/key_struct.rs
crates/rooch/src/commands/account/commands/create.rs
crates/rooch/src/commands/account/commands/import.rs
crates/rooch/src/commands/account/commands/list.rs
crates/rooch/src/commands/account/commands/nullify.rs
crates/rooch/src/commands/account/commands/update.rs
crates/rooch/src/commands/init.rs
crates/rooch/src/commands/move_cli/commands/publish.rs
crates/rooch/src/commands/move_cli/commands/run_function.rs
crates/rooch/src/commands/server/commands/start.rs
crates/rooch/src/commands/session_key/commands/create.rs
crates/testsuite/features/cmd.feature

Continuing of #942 
- Closes #933

[gh-933] move password hash into keystore.

---

crates/rooch/src/commands/init.rs

Add command explanations.
- Closes #933

[gh-933] add command explanations.

---

crates/rooch-framework/doc/bitcoin_address.md
crates/rooch-framework/doc/ecdsa_k1.md
crates/rooch-framework/doc/ecdsa_k1_recoverable.md
crates/rooch-framework/doc/ethereum_address.md
crates/rooch-framework/doc/ethereum_validator.md
crates/rooch-framework/doc/native_validator.md
crates/rooch-framework/doc/schnorr.md
crates/rooch-framework/doc/transaction_validator.md
crates/rooch-framework/sources/address_type/bitcoin_address.move
crates/rooch-framework/sources/address_type/ethereum_address.move
crates/rooch-framework/sources/auth_validator/ethereum_validator.move
crates/rooch-framework/sources/auth_validator/native_validator.move
crates/rooch-framework/sources/crypto/ecdsa_k1.move
crates/rooch-framework/sources/crypto/ecdsa_k1_recoverable.move
crates/rooch-framework/sources/crypto/schnorr.move
crates/rooch-framework/sources/transaction_validator.move
crates/rooch-framework/src/natives/rooch_framework/crypto/decoding.rs
crates/rooch-framework/src/natives/rooch_framework/crypto/ecdsa_k1.rs
crates/rooch-framework/src/natives/rooch_framework/crypto/ecdsa_k1_recoverable.rs
crates/rooch-framework/src/natives/rooch_framework/crypto/encoding.rs
crates/rooch-framework/src/natives/rooch_framework/crypto/schnorr.rs
moveos/moveos-stdlib/moveos-stdlib/doc/account_storage.md
moveos/moveos-stdlib/moveos-stdlib/doc/address.md
moveos/moveos-stdlib/moveos-stdlib/doc/copyable_any.md
moveos/moveos-stdlib/moveos-stdlib/doc/hex.md
moveos/moveos-stdlib/moveos-stdlib/sources/account_storage.move
moveos/moveos-stdlib/moveos-stdlib/sources/address.move
moveos/moveos-stdlib/moveos-stdlib/sources/copyable_any.move
moveos/moveos-stdlib/moveos-stdlib/sources/hex.move

resolve https://github.com/rooch-network/rooch/issues/946
The Error code starts from 1.

Unify framework error code start number

---

docs/website/pages/docs/dive-into-rooch/_meta.en-US.json
docs/website/pages/docs/dive-into-rooch/_meta.zh-CN.json
docs/website/pages/docs/dive-into-rooch/account-abstraction.en-CN.mdx
docs/website/pages/docs/dive-into-rooch/account-abstraction.zh-CN.mdx
docs/website/pages/docs/tech-highlights/_meta.en-US.json
docs/website/pages/docs/tech-highlights/_meta.zh-CN.json
docs/website/pages/docs/tech-highlights/account-abstraction.en-US.mdx
docs/website/pages/docs/tech-highlights/account-abstraction.zh-CN.mdx

TODO Design and Implementation of Account Abstraction 
- Closes #468

[Documents] Account abstraction

---

crates/rooch-executor/src/actor/executor.rs
crates/rooch-executor/src/actor/messages.rs
crates/rooch-executor/src/proxy/mod.rs
crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/api/rooch_api.rs
crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs
crates/rooch-rpc-client/src/rooch_client.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-rpc-server/src/service/aggregate_service.rs
crates/rooch-rpc-server/src/service/rpc_service.rs
dashboard/src/store/session/index.ts
moveos/moveos-store/src/lib.rs
moveos/moveos-store/src/state_store/statedb.rs
moveos/moveos-types/src/state_resolver.rs
moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs
moveos/smt/src/lib.rs
sdk/typescript/src/account/account.ts
sdk/typescript/src/provider/filtered-provider.test.ts
sdk/typescript/src/provider/filtered-provider.ts
sdk/typescript/src/provider/interface.ts
sdk/typescript/src/provider/json-rpc-provider.ts
sdk/typescript/tools/generator/template/name_mapping.json

1. Refactor ListView from Vec<Option<(Vec<u8>, State)>> to Vec<(Vec<u8>, State)>.
2. Remove `List` from `PageView`.

[RPC] Refactor rpc list view

---

dashboard/src/context/auth/AuthContext.tsx
dashboard/src/context/session/SessionContext.tsx
dashboard/src/context/wallet/index.tsx

Fix dashboard refresh lost login status

Fix dashboard refresh lost login status

---

.github/workflows/deploy_examples.yml
scripts/check_dev_deploy_status.sh
scripts/deploy_examples.sh

Should not rely the cmd on the vm

not rely vm cmd anymore

---

crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-rpc-server/src/service/aggregate_service.rs

resolve https://github.com/rooch-network/rooch/issues/970
If the tx hash is invalid, filled None when returned.

Multi key query RPC should return Vec<Option<V>>

---

crates/rooch-rpc-api/src/api/eth_api.rs
crates/rooch-rpc-server/src/lib.rs
crates/rooch-rpc-server/src/server/eth_server.rs
crates/testsuite/features/cmd.feature
crates/testsuite/tests/integration.rs

1. Add the net_version API
2. Fix the integration test bug
3. Add some tests to the ETH API

[RPC] Add net_version API

---

dashboard/src/context/auth/AuthContext.tsx
dashboard/src/context/rooch/index.tsx
dashboard/src/context/session/SessionContext.tsx
dashboard/src/context/wallet/index.tsx
dashboard/src/pages/scan/transaction/list/index.tsx
dashboard/src/store/scan/state/index.ts
scripts/deploy_examples.sh
sdk/typescript/src/constants/chain.ts
sdk/typescript/src/provider/json-rpc-provider.ts

1. fix clear local data, lost session status 
2. fix sdk dev chain url
3. fix transaction list
https://github.com/rooch-network/rooch/issues/876

fix dashboard bugs

---

dashboard/src/@core/components/session/SessionGuard.tsx
dashboard/src/configs/auth.ts
dashboard/src/context/auth/AuthContext.tsx
dashboard/src/context/session/SessionContext.tsx
dashboard/src/context/session/types.ts
dashboard/src/context/wallet/index.tsx
dashboard/src/store/session/index.ts
dashboard/src/views/feature/SessionKeyList.tsx

1. Add the eth address and rooch address mapping
2. Fix session list
3. Add method to get the current session (used to solve the session list processing to delete the current session) has not found a good solution
4. Fix Use Rooch address login, Unable to create a session

fix dashboard bug

---

dashboard/src/navigation/vertical/index.ts
dashboard/src/pages/login/index.tsx

1. hide login page oath option
2. hide sidebar list item (assets, example...)

hide dashboard todo feature

---

scripts/check_dev_deploy_status.sh

fix deploy devnet workflow with skip-password

fix deploy devnet workflow with skip-password

---

.github/workflows/docker_build.yml
scripts/check_dev_deploy_status.sh

Fix deploy with image_tag

---

dashboard/src/context/auth/AuthContext.tsx
dashboard/src/pages/scan/transaction/detail/[tx_hash].tsx
dashboard/src/pages/scan/transaction/list/index.tsx

fix transcation

---

docs/website/pages/docs/example-guides.en-US.mdx
docs/website/pages/docs/example-guides.zh-CN.mdx

add doc content that explains the project name of the `examples`

---

scripts/check_dev_deploy_status.sh

fix rooch init failed with phrase

---

scripts/check_dev_deploy_status.sh

fix "docker: invalid reference format."

fix deploy workflow

---

scripts/check_dev_deploy_status.sh

fix docker: invalid reference format

fix docker: invalid reference format

---

scripts/check_dev_deploy_status.sh

remove unused slash

---

docs/website/pages/_meta.en-US.json
docs/website/pages/_meta.zh-CN.json

rooch network add dashboard link menu

---

dashboard/src/@core/components/session/SessionGuard.tsx
dashboard/src/navigation/vertical/index.ts
dashboard/src/pages/tutorial/counter/index.tsx
dashboard/src/store/session/index.ts

Scope creation for the session key
option 1 : All scopes are counted here to provide optional authorization when first created
option 2 : Each app is authorized separately

add counter example

---

crates/rooch-framework-tests/tests/cases/object/basic.exp
moveos/moveos-stdlib/moveos-stdlib/doc/object.md
moveos/moveos-stdlib/moveos-stdlib/sources/context.move
moveos/moveos-stdlib/moveos-stdlib/sources/object.move
moveos/moveos-types/src/moveos_std/object.rs
moveos/moveos/src/vm/tx_argument_resolver.rs

Implement shared and frozen Object.
TODO: Add more tests and examples.
- Closes #1075

[Object] Implement shared and frozen Object

---

dashboard/src/@core/components/auth/AuthGuard.tsx
dashboard/src/@core/components/session/SessionGuard.tsx
dashboard/src/@core/layouts/components/shared-components/UserDropdown.tsx
dashboard/src/context/auth/AuthContext.tsx
dashboard/src/context/auth/types.ts
dashboard/src/context/session/SessionContext.tsx
dashboard/src/context/session/types.ts
dashboard/src/context/types.ts
dashboard/src/context/wallet/index.tsx
dashboard/src/context/wallet/types.ts
dashboard/src/layouts/components/vertical/AppBarContent.tsx
dashboard/src/pages/tutorial/counter/index.tsx
sdk/typescript/src/provider/json-rpc-provider.ts

fix multi-account-session

---

dashboard/src/@core/components/auth/AuthGuard.tsx
dashboard/src/context/auth/AuthContext.tsx
dashboard/src/context/session/SessionContext.tsx
dashboard/src/context/wallet/index.tsx

fix rooch account session key

---

sdk/typescript/src/account/account.test.ts

fix sdk account test

---

dashboard/src/pages/scan/state/[tab].tsx
dashboard/src/views/feature/SessionKeyList.tsx
dashboard/src/views/scan/state/list/index.tsx

fix table ui responsive

---

crates/rooch/src/commands/move_cli/commands/integration_test.rs
crates/rooch/src/commands/move_cli/mod.rs

resolve https://github.com/rooch-network/rooch/issues/1103

fixing the address parsing in integration test

---

crates/rooch-indexer/migrations/2023-10-31-085230_events/up.sql
crates/rooch-indexer/src/actor/indexer.rs
crates/rooch-indexer/src/actor/messages.rs
crates/rooch-indexer/src/proxy/mod.rs
crates/rooch-indexer/src/schema.rs
crates/rooch-indexer/src/store/sqlite_store.rs
crates/rooch-indexer/src/types.rs
crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/jsonrpc_types/execute_tx_response.rs
crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs
crates/rooch-rpc-client/src/client_config.rs
crates/rooch-rpc-server/src/lib.rs
crates/rooch-rpc-server/src/service/rpc_service.rs
moveos/moveos-types/src/event_filter.rs
moveos/moveos-types/src/moveos_std/event.rs
moveos/moveos-types/src/transaction.rs
moveos/moveos/src/moveos.rs
moveos/moveos/src/vm/moveos_vm.rs

Follow https://github.com/rooch-network/rooch/pull/1121 And Cotinue #1028
1.  Implements event indexer write
2. Add RawTransactionOutput to convert TransactionEvent into Event
- Closes #1037 
1. indexer transaction and event RPC

Implements event indexer write

---

crates/rooch-framework-tests/tests/cases/data_struct/data_struct_correct.exp
crates/rooch-framework-tests/tests/cases/data_struct/data_struct_correct.move
crates/rooch-framework-tests/tests/cases/data_struct/data_struct_incorrect.exp
crates/rooch-framework-tests/tests/cases/data_struct/data_struct_incorrect.move
crates/rooch-framework-tests/tests/cases/data_struct/data_struct_incorrect_ability.exp
crates/rooch-framework-tests/tests/cases/data_struct/data_struct_incorrect_ability.move
crates/rooch-framework-tests/tests/cases/data_struct/data_struct_incorrect_field.exp
crates/rooch-framework-tests/tests/cases/data_struct/data_struct_incorrect_field.move
examples/data_struct/Move.toml
examples/data_struct/sources/data_struct.move
moveos/moveos-verifier/src/metadata.rs
moveos/moveos-verifier/src/verifier.rs

Detailed explanation is provided here: https://github.com/rooch-network/rooch/issues/920

[DRAFT] Compiling and checking the structure and functions annotated with data_struct.

---

docker/Dockerfile

add libsqlite3-dev in the runtime

---

crates/rooch-framework/doc/address_mapping.md
crates/rooch-framework/doc/chain_id.md
crates/rooch-framework/sources/address_mapping.move
crates/rooch-framework/sources/chain_id.move
crates/testsuite/features/cmd.feature

[Framework] Make ChainID and AddressMapping to singleton Object

---

crates/rooch-indexer/src/models/transactions.rs
crates/rooch-indexer/src/types.rs
crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/api/rooch_api.rs
crates/rooch-rpc-api/src/jsonrpc_types/execute_tx_response.rs
crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs
crates/rooch-rpc-client/src/rooch_client.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-rpc-server/src/service/rpc_service.rs
crates/rooch-sequencer/src/actor/sequencer.rs
crates/rooch-sequencer/src/messages.rs
crates/rooch-sequencer/src/proxy/mod.rs
crates/rooch-store/src/lib.rs
crates/rooch-store/src/transaction_store/mod.rs
crates/rooch-types/src/authentication_key.rs
crates/rooch-types/src/sequencer.rs
crates/rooch-types/src/transaction/mod.rs
crates/rooch/src/commands/transaction/commands/get_transactions_by_order.rs
sdk/typescript/tools/generator/template/name_mapping.json

part of https://github.com/rooch-network/rooch/pull/1136
Make tx order type from u128 to u64

Make tx order type from u128 to u64

---

crates/rooch-framework-tests/src/tests/bitcoin_light_client_test.rs
crates/rooch-framework/doc/README.md
crates/rooch-framework/doc/bitcoin_light_client.md
crates/rooch-framework/doc/bitcoin_types.md
crates/rooch-framework/sources/bitcoin_light_client.move
crates/rooch-framework/sources/bitcoin_types.move
crates/rooch-relayer/src/actor/bitcoin_relayer.rs
crates/rooch-types/src/framework/bitcoin_light_client.rs
crates/rooch-types/src/framework/bitcoin_types.rs
crates/rooch-types/src/framework/mod.rs
crates/rooch-types/src/into_address.rs
crates/rooch-types/src/lib.rs

1. Define Bitcoin transaction
2. Progress transaction and store utxo
- Closes #992 
Part of #997

[bitcoin] Define bitcoin transaction types and progress transaction

---

crates/rooch-framework/doc/README.md
crates/rooch-framework/doc/bitcoin_opcode.md
crates/rooch-framework/sources/bitcoin_light_client.move
crates/rooch-framework/sources/bitcoin_opcode.move
crates/rooch-framework/sources/bitcoin_types.move
crates/rooch-relayer/src/actor/relayer.rs

[Framework] Define bitcoin_opcode

---

Cargo.lock
crates/rooch-indexer/Cargo.toml
crates/rooch-indexer/src/store/sqlite_store.rs
crates/rooch-indexer/src/utils.rs
crates/rooch-rpc-server/src/service/rpc_service.rs
crates/testsuite/features/cmd.feature

Resolve https://github.com/rooch-network/rooch/issues/1202
And catch indexer errors, does not affect transaction execution.

[Indexer] Fixup sqlite sql escape

---

.github/workflows/release_asset.yml
scripts/release.sh

fix windows release by install sqlite3

---

crates/rooch-executor/src/actor/executor.rs
crates/rooch-executor/src/actor/messages.rs
crates/rooch-executor/src/proxy/mod.rs
crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs
crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-rpc-server/src/service/aggregate_service.rs
crates/rooch-rpc-server/src/service/rpc_service.rs
moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs
moveos/moveos-types/src/moveos_std/raw_table.rs
moveos/moveos-types/src/state.rs
moveos/moveos-types/src/state_resolver.rs
sdk/typescript/rooch-sdk/src/account/account.ts
sdk/typescript/rooch-sdk/tools/generator/template/name_mapping.json

resolve https://github.com/rooch-network/rooch/issues/1179
- Closes #1179

[RPC] Support list table keys

---

crates/rooch-framework-tests/src/tests/bitcoin_light_client_test.rs
crates/rooch-framework-tests/src/tests/brc20_test.rs
crates/rooch-framework-tests/src/tests/mod.rs
crates/rooch-framework-tests/src/tests/ord_test.rs
crates/rooch-framework/doc/README.md
crates/rooch-framework/doc/address_mapping.md
crates/rooch-framework/doc/bitcoin_light_client.md
crates/rooch-framework/doc/bitcoin_types.md
crates/rooch-framework/doc/brc20.md
crates/rooch-framework/doc/genesis.md
crates/rooch-framework/doc/multichain_address.md
crates/rooch-framework/doc/ord.md
crates/rooch-framework/doc/utxo.md
crates/rooch-framework/sources/address_mapping.move
crates/rooch-framework/sources/address_type/multichain_address.move
crates/rooch-framework/sources/bitcoin_light_client.move
crates/rooch-framework/sources/bitcoin_types.move
crates/rooch-framework/sources/brc20.move
crates/rooch-framework/sources/genesis.move
crates/rooch-framework/sources/ord.move
crates/rooch-framework/sources/utxo.move
crates/rooch-framework/src/natives/rooch_framework/bitcoin/ord/inscription.rs
crates/rooch-framework/src/natives/rooch_framework/bitcoin/ord/mod.rs
crates/rooch-relayer/src/actor/bitcoin_relayer.rs
crates/rooch-types/src/framework/bitcoin_light_client.rs
crates/rooch-types/src/framework/brc20.rs
crates/rooch-types/src/framework/ord.rs
moveos/moveos-stdlib/moveos-stdlib/doc/simple_map.md
moveos/moveos-stdlib/moveos-stdlib/sources/simple_map.move

1. UTXO as Object
2. Inscription as Object
3. Support seal assets to UTXO. Ord Inscription is a seal.
part of #423 #1214 
1. Query UTXO object
```bash
rooch rpc request --method rooch_queryGlobalStates --params '[{"object_type":"0x3::utxo::UTXO"},null, "3", true]'
```
```json
{
"data": [
{
"object_id": "0xfff4d9c841e2ae378477e824ec27397f247ac82c7c303b34013226cdfd18dcc0",
"owner": "0x0000000000000000000000000000000000000000000000000000000000000003",
"flag": 0,
"value": {
"abilities": 8,
"type": "0x3::utxo::UTXO",
"value": {
"seals": {
"abilities": 7,
"type": "0x2::simple_map::SimpleMap<0x1::string::String, 0x2::object::ObjectID>",
"value": {
"data": [
{
"abilities": 7,
"type": "0x2::simple_map::Element<0x1::string::String, 0x2::object::ObjectID>",
"value": {
"key": …
```

Refactor utxo progress

---

Cargo.lock
Cargo.toml
moveos/moveos-stdlib/moveos-stdlib/sources/type_info.move

the native function type_name has return the correct conten

---

scripts/bitcoin/README.md
scripts/bitcoin/cmd_alias.sh
scripts/bitcoin/run_local_node.sh

[devops] Setup bitcoin local dev env

---

examples/steal_split/sources/steal_split.move
moveos/moveos-stdlib/move-stdlib/doc/README.md
moveos/moveos-stdlib/move-stdlib/doc/acl.md
moveos/moveos-stdlib/move-stdlib/doc/bit_vector.md
moveos/moveos-stdlib/move-stdlib/doc/error.md
moveos/moveos-stdlib/move-stdlib/doc/fixed_point32.md
moveos/moveos-stdlib/move-stdlib/doc/option.md
moveos/moveos-stdlib/move-stdlib/doc/signer.md
moveos/moveos-stdlib/move-stdlib/doc/string.md
moveos/moveos-stdlib/move-stdlib/doc/vector.md
moveos/moveos-stdlib/move-stdlib/sources/acl.move
moveos/moveos-stdlib/move-stdlib/sources/acl.spec.move
moveos/moveos-stdlib/move-stdlib/sources/bit_vector.move
moveos/moveos-stdlib/move-stdlib/sources/error.move
moveos/moveos-stdlib/move-stdlib/sources/fixed_point32.move
moveos/moveos-stdlib/move-stdlib/sources/option.move
moveos/moveos-stdlib/move-stdlib/sources/signer.move
moveos/moveos-stdlib/move-stdlib/sources/string.move
moveos/moveos-stdlib/move-stdlib/sources/string.spec.move
moveos/moveos-stdlib/move-stdlib/sources/vector.move

resolve https://github.com/rooch-network/rooch/issues/1230

sync the move-stdlib with the upstream

---

dashboard/src/@core/layouts/components/shared-components/SwitchChainDropdown.tsx
dashboard/src/context/rooch/index.tsx
dashboard/src/context/rooch/types.ts
dashboard/src/context/wallet/index.tsx
dashboard/src/context/wallet/types.ts
dashboard/src/pages/tutorial/counter/index.tsx
sdk/typescript/templates/react/src/context/rooch/index.tsx
sdk/typescript/templates/react/src/context/rooch/types.ts
sdk/typescript/templates/react/src/context/wallet/index.tsx
sdk/typescript/templates/react/src/context/wallet/types.ts

[fix] Fix spelling errors in SDK.

---

crates/rooch-framework-tests/tests/cases/private_generics/mismatches_function_definition.exp
moveos/moveos-verifier/src/metadata.rs
moveos/moveos-verifier/src/verifier.rs

resolve https://github.com/rooch-network/rooch/issues/1253

[Draft] refactor the code of verifier and resolve the security risks.

---

.github/workflows/deploy_frontend.yml

fix deploy

---

.github/workflows/deploy_frontend.yml

deploy dashboard to gcs

---

crates/rooch-types/src/transaction/ethereum.rs
crates/rooch-types/src/transaction/mod.rs
crates/rooch-types/src/transaction/rooch.rs
moveos/moveos-stdlib/moveos-stdlib/sources/tx_context.move
moveos/moveos-types/src/moveos_std/tx_context.rs
moveos/moveos-types/src/transaction.rs
moveos/moveos/src/gas/table.rs
moveos/moveos/src/moveos.rs
moveos/moveos/src/vm/moveos_vm.rs
sdk/typescript/rooch-sdk/test/e2e/sdk.test.ts

resolve https://github.com/rooch-network/rooch/issues/1267

Counting gas in several types

---

crates/rooch-config/src/da_config.rs

add test for parse_hashmap in da config

ci(da): add test for parse_hashmap in da config

---

Cargo.lock
crates/rooch-executor/src/actor/executor.rs
crates/rooch-framework/doc/onchain_config.md
crates/rooch-framework/sources/onchain_config.move
moveos/moveos/Cargo.toml
moveos/moveos/src/gas/table.rs
moveos/moveos/src/moveos.rs
moveos/moveos/src/vm/moveos_vm.rs
moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs

Retrieve GasSchedule from the chain and initialize GasParameters during transaction execution.

restore gas parameters from on chain state

---

scripts/bitcoin/README.md
scripts/bitcoin/node/run_local_node_docker.sh
scripts/bitcoin/node/run_local_node_podman.sh

[gh-1328] change scripts and add details to README.

---

.github/workflows/docker_build.yml

add testnet deploy workflow

---

crates/rooch-executor/src/actor/messages.rs
crates/rooch-executor/src/actor/reader_executor.rs
crates/rooch-executor/src/proxy/mod.rs
crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/api/rooch_api.rs
crates/rooch-rpc-client/src/rooch_client.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-rpc-server/src/service/rpc_service.rs
crates/rooch/src/commands/event.rs
crates/rooch/src/commands/transaction/commands/get_transactions_by_order.rs
crates/testsuite/features/cmd.feature
dashboard/src/pages/scan/transaction/detail/[tx_hash].tsx
dashboard/src/pages/scan/transaction/list/index.tsx
moveos/moveos-store/src/event_store/mod.rs
moveos/moveos-store/src/lib.rs
sdk/typescript/rooch-sdk/src/client/rooch-client.ts
sdk/typescript/rooch-sdk/src/client/types.ts

resolve https://github.com/rooch-network/rooch/issues/1347 , relative to https://github.com/rooch-network/rooch/issues/1022
- Closes #1347

[RPC] Support get transactions and events in reverse order

---

pnpm-lock.yaml
sdk/typescript/rooch-sdk-kit/package.json
sdk/typescript/rooch-sdk-kit/src/provider/walletProvider.tsx

fixbug for 'WalletProvider' cannot be used as a JSX component
https://github.com/rooch-network/rooch/issues/1339

feat: fixbug for 'WalletProvider' cannot be used as a JSX component

---

crates/rooch-config/src/config.rs
crates/rooch-config/src/da_config.rs
crates/rooch-da/src/server/openda/actor/server.rs
crates/rooch-rpc-server/src/lib.rs
crates/rooch/src/commands/server/commands/clean.rs
crates/rooch/src/commands/server/mod.rs

easy to clean up and development
- Closes #1357

feat(DA): add fs as open-da for dev env

---

.github/workflows/deploy_frontend_testnet.yml
dashboard/src/@core/layouts/components/shared-components/SwitchNetworkDropdown.tsx
dashboard/src/navigation/vertical/index.ts
dashboard/src/pages/_app.tsx
dashboard/src/pages/assets/inscription/list/index.tsx
dashboard/src/pages/assets/utxo/list/index.tsx
sdk/typescript/rooch-sdk/src/constants/networks.ts

1. Modify the current frontend deploy wrokflows
2. Analyze the inscriptions
3. Add utxo
4. Assets Only the user's assets are displayed

fix dashboard testnet

---

crates/rooch-da/src/server/openda/actor/server.rs

feat(DA): add log for openDA

---

scripts/bitcoin/README.md
scripts/bitcoin/env.sh

add bitcoin env shell

---

docker/Dockerfile

fix docker build by upgrade libssl version

upgrade libssl version

---

.github/workflows/deploy_testnet_match.yml

deploy rooch seed for match

---

crates/rooch/src/commands/move_cli/commands/new.rs

fix `move new` command

---

crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch/src/commands/object.rs
crates/rooch/src/commands/resource.rs
crates/rooch/src/commands/state.rs
examples/display/Move.toml
examples/display/sources/display.move
moveos/moveos-types/src/access_path.rs
moveos/moveos-types/src/moveos_std/display.rs
moveos/moveos-types/src/state.rs

Continuation of PR #1393. 
Resolve #1174.

Support display for Move resources and add an example

---

Cargo.lock
crates/rooch-framework/doc/genesis.md
crates/rooch-framework/sources/genesis.move
crates/rooch-genesis/Cargo.toml
crates/rooch-genesis/src/lib.rs
moveos/moveos-stdlib/moveos-stdlib/doc/README.md
moveos/moveos-stdlib/moveos-stdlib/doc/genesis.md
moveos/moveos-stdlib/moveos-stdlib/sources/genesis.move
moveos/moveos-stdlib/moveos-stdlib/sources/move_module.move
moveos/moveos-store/src/state_store/statedb.rs
moveos/moveos-store/src/tests/test_state_store.rs
moveos/moveos-types/src/addresses.rs
moveos/moveos-types/src/moveos_std/raw_table.rs
moveos/moveos/src/moveos.rs
moveos/moveos/src/vm/data_cache.rs
moveos/moveos/src/vm/moveos_vm.rs
moveos/moveos/src/vm/tx_argument_resolver.rs

1. Merge four genesis tx into one.
2. Deprecate the ChangeSet.
3. Create Module Object when genesis init.
part of #248 

[Genesis] refactor genesis init

---

crates/rooch-rpc-api/src/jsonrpc_types/eth/transaction.rs
crates/rooch-types/src/transaction/authenticator.rs
moveos/moveos-commons/accumulator/src/node_index.rs
moveos/moveos-stdlib/moveos-stdlib/doc/display.md
moveos/moveos-stdlib/moveos-stdlib/sources/display.move

chore: remove repetitive words

---

crates/rooch-framework/doc/account.md
crates/rooch-framework/doc/gas_coin.md
crates/rooch-framework/sources/account.move
crates/rooch-framework/sources/gas_coin.move
crates/rooch-framework/sources/genesis.move
crates/rooch-framework/sources/tests/gas_coin_test.move
crates/rooch-framework/sources/transaction_validator.move
crates/rooch/src/commands/move_cli/commands/publish.rs
frameworks/bitcoin-move/doc/light_client.md
frameworks/bitcoin-move/sources/light_client.move
moveos/moveos-stdlib/moveos-stdlib/doc/account.md
moveos/moveos-stdlib/moveos-stdlib/sources/account.move
moveos/moveos/src/vm/moveos_vm.rs

1. Avoid faucet DDOS attack.
2. Disable creating account for reserved address.

Review TODO & FIXME

---

crates/rooch-framework/src/natives/gas_parameter/object.rs
moveos/moveos-stdlib/moveos-stdlib/doc/object.md
moveos/moveos-stdlib/moveos-stdlib/sources/object.move
moveos/moveos-stdlib/src/natives/moveos_stdlib/object.rs
moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs
moveos/moveos/src/gas/parameter.rs

Check the object and object field type.
- Closes #1450

Check the object and object field type

---

docs/website/pages/blog/stackable-l2.en-US.mdx
docs/website/pages/blog/stackable-l2.zh-CN.mdx

fix stackable-l2 link

---

crates/rooch-framework/sources/crypto/encoding.move
moveos/moveos-stdlib-builder/src/dependency_order.rs
moveos/moveos-verifier/src/verifier.rs
sdk/typescript/rooch-sdk/src/types/hex.ts

chore: fix some typos

---

crates/rooch-framework-tests/tests/cases/data_struct/data_struct_incorrect_ability.move.bak
crates/rooch/src/commands/move_cli/commands/unit_test.rs
moveos/moveos-stdlib/src/natives/moveos_stdlib/object.rs
moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs
moveos/moveos-stdlib/src/natives/moveos_stdlib/tx_context.rs
moveos/moveos-store/src/tests/test_state_store.rs
moveos/moveos/src/moveos.rs
moveos/moveos/src/vm/data_cache.rs
moveos/moveos/src/vm/moveos_vm.rs
moveos/moveos/src/vm/tx_argument_resolver.rs
moveos/moveos/src/vm/unit_tests/data_cache_tests.rs

Just rename and do not change the logic for the following refactor.
include #1473

Rename NativeTableContext to ObjectRuntimeContext

---

.github/workflows/check_build_test.yml
crates/testsuite/features/cmd.feature
moveos/moveos/src/vm/tx_argument_resolver.rs

fix Argument length mismatch panic

---

rooch-portal-v1/README.md
rooch-portal-v1/src/common/interface.ts
rooch-portal-v1/src/components/skeleton-list.tsx
rooch-portal-v1/src/components/wallet-connect.tsx
rooch-portal-v1/src/pages/transactions/components/transactions-table.tsx

feature: get transactions data in `transactions-table.tsx`

---

crates/rooch-genesis/src/lib.rs
crates/rooch-types/src/bitcoin/network.rs
frameworks/bitcoin-move/doc/genesis.md
frameworks/bitcoin-move/doc/network.md
frameworks/bitcoin-move/sources/genesis.move
frameworks/bitcoin-move/sources/network.move

follow #1497 
refactor bitcoin-move genesis init, write BitcoinNetwork config to state.

refactor bitcoin-move genesis init

---

Cargo.lock
Cargo.toml
crates/rooch-benchmarks/Cargo.toml
crates/rooch-benchmarks/src/tx.rs
crates/rooch-executor/src/proxy/mod.rs
crates/rooch-pipeline-processor/Cargo.toml
crates/rooch-pipeline-processor/src/actor/messages.rs
crates/rooch-pipeline-processor/src/actor/mod.rs
crates/rooch-pipeline-processor/src/actor/processor.rs
crates/rooch-pipeline-processor/src/lib.rs
crates/rooch-pipeline-processor/src/proxy/mod.rs
crates/rooch-proposer/src/proxy/mod.rs
crates/rooch-rpc-api/src/jsonrpc_types/execute_tx_response.rs
crates/rooch-rpc-server/src/lib.rs
crates/rooch-rpc-server/src/server/btc_server.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-rpc-server/src/service/rpc_service.rs
crates/rooch-types/src/transaction/mod.rs

Introduce the rooch pipeline processor actor
1. process the tx pipeline.
2. TODO makes the relayer to an actor and directly calls the pipeline processor.

Introduce rooch pipeline processor actor

---

docs/website/components/pages/brand.tsx
docs/website/data/assets.tsx

feat: download svg

---

crates/rooch-types/src/bitcoin/utxo.rs
frameworks/bitcoin-move/doc/ord.md
frameworks/bitcoin-move/doc/utxo.md
frameworks/bitcoin-move/sources/light_client.move
frameworks/bitcoin-move/sources/ord.move
frameworks/bitcoin-move/sources/utxo.move

1. Remove SealPoint from UTXO seals.
2. Rename SealPoint to SatPoint.
3. Make the SatPoint to an intermediate struct to spend UTXO and progress tx.

[utxo] Remove SealPoint from utxo

---

.eslintrc.js
.prettierignore
grow-rooch-v1/src/pages/mint/mint-page.tsx
sdk/typescript/rooch-sdk-kit/src/provider/clientProvider.tsx
sdk/typescript/rooch-sdk/src/account/interface.ts
sdk/typescript/rooch-sdk/src/account/roochAccount.ts
sdk/typescript/rooch-sdk/src/account/roochSessionAccount.ts
sdk/typescript/rooch-sdk/src/client/roochClient.ts
sdk/typescript/rooch-sdk/src/constants/gas.ts
sdk/typescript/rooch-sdk/test/e2e/sdk.test.ts

fix sdk e2e test

---

examples/btc_holder_farmer/Move.toml
examples/btc_holder_farmer/sources/holder_farmer.move

https://github.com/rooch-network/rooch/issues/1509

[Example] Add example for hold bitcoin harvest new asset

---

frameworks/bitcoin-move/doc/ord.md
frameworks/bitcoin-move/sources/light_client.move
frameworks/bitcoin-move/sources/ord.move

Process the coinbase transactions in the block, pay the block reward + all transaction fees to the miners, and process the Ord Satpoint transfer.
- Closes #1505

[Bitcoin] Handle coinbase transaction for Ord

---

crates/rooch-executor/src/actor/executor.rs
crates/rooch-executor/src/actor/messages.rs
crates/rooch-executor/src/proxy/mod.rs
crates/rooch-indexer/src/actor/indexer.rs
crates/rooch-indexer/src/actor/messages.rs
crates/rooch-indexer/src/proxy/mod.rs
crates/rooch-pipeline-processor/src/actor/processor.rs
crates/rooch-rpc-server/src/lib.rs
crates/rooch-sequencer/src/actor/sequencer.rs
moveos/moveos-store/src/lib.rs
moveos/moveos-store/src/state_store/mod.rs
moveos/moveos-store/src/state_store/statedb.rs
moveos/moveos-store/src/tests/test_state_store.rs
moveos/raw-store/src/lib.rs
moveos/smt/src/lib.rs
moveos/smt/src/tests.rs

[statedb] Make smt tree stateless and statedb support batch write

[statedb] Make smt tree stateless and statedb support batch write

---

frameworks/moveos-stdlib/sources/display.move

add missing event for display

---

frameworks/moveos-stdlib/doc/README.md
frameworks/moveos-stdlib/doc/display.md
frameworks/moveos-stdlib/doc/features.md
frameworks/moveos-stdlib/doc/move_module.md
frameworks/moveos-stdlib/sources/features.move
frameworks/moveos-stdlib/sources/move_module.move
frameworks/rooch-framework/doc/account_authentication.md
frameworks/rooch-framework/doc/auth_validator_registry.md
frameworks/rooch-framework/doc/bitcoin_validator.md
frameworks/rooch-framework/doc/ethereum_light_client.md
frameworks/rooch-framework/doc/ethereum_validator.md
frameworks/rooch-framework/doc/native_validator.md
frameworks/rooch-framework/doc/onchain_config.md
frameworks/rooch-framework/doc/session_key.md
frameworks/rooch-framework/doc/transaction_validator.md
frameworks/rooch-framework/sources/account_authentication.move
frameworks/rooch-framework/sources/auth_validator/auth_validator_registry.move
frameworks/rooch-framework/sources/auth_validator/bitcoin_validator.move
frameworks/rooch-framework/sources/auth_validator/ethereum_validator.move
frameworks/rooch-framework/sources/auth_validator/native_validator.move
frameworks/rooch-framework/sources/ethereum_light_client.move
frameworks/rooch-framework/sources/onchain_config.move
frameworks/rooch-framework/sources/session_key.move
frameworks/rooch-framework/sources/transaction_validator.move

Add features to enable or disable Move functions

---

rooch-portal-v1/src/App.tsx
rooch-portal-v1/src/components/session-key-modal.tsx

Complete the session modal component

feature: add session key modal component

---

frameworks/moveos-stdlib/sources/features.move
frameworks/moveos-stdlib/sources/genesis.move
frameworks/moveos-stdlib/sources/move_module.move
frameworks/rooch-framework/sources/account_authentication.move
frameworks/rooch-framework/sources/auth_validator/auth_validator_registry.move
frameworks/rooch-framework/sources/genesis.move

init feature store in genesis

---

crates/rooch-types/src/address.rs
crates/rooch-types/src/bitcoin/ord.rs
frameworks/bitcoin-move/doc/ord.md
frameworks/bitcoin-move/doc/utxo.md
frameworks/bitcoin-move/sources/ord.move
frameworks/rooch-framework/sources/address_type/multichain_address.move

[Bitcoin] Make Inscription object as child object

---

Cargo.lock
Cargo.toml

fix(build): fix clap building issue after upgrade to rust 1.77.1

---

Cargo.toml
crates/rooch-benchmarks/README.md
crates/rooch-benchmarks/benches/bench_tx_sequence.rs
crates/rooch-benchmarks/benches/bench_tx_validate.rs
crates/rooch-benchmarks/src/config.rs
crates/rooch-benchmarks/src/tx_exec.rs

1. remove cannot resolve file moveos-cli
2. fix wrong kebab-case for btc block
3. refine bench config load
4. update bench README for new changes

ci(bench): update bench README for new changes

---

Cargo.lock
Cargo.toml
frameworks/moveos-stdlib/doc/bech32.md
frameworks/moveos-stdlib/sources/bech32.move
frameworks/moveos-stdlib/sources/hash.move
frameworks/moveos-stdlib/src/natives/moveos_stdlib/bech32.rs
frameworks/rooch-framework/doc/account_authentication.md
frameworks/rooch-framework/src/natives/gas_parameter/bech32.rs

Upgrade bech32 package and move bech32 functions.
- Closes #1552

[gh-1552] upgrade bech32 pkg and add new features of move bech32.

---

rooch-portal-v1/src/pages/assets/assets-details/tabs/coin/assets-coin.tsx
rooch-portal-v1/src/pages/settings/components/manage-sessions.tsx

1. Add "Pagination" logic and component on Assets page.
2. Add `overflow-auto` as scroll bar on Settings page.

feature(rooch-portal-v1): pagination functionality implementation and UI refactor

---

frameworks/rooch-framework/doc/account_coin_store.md
frameworks/rooch-framework/sources/account_coin_store.move
moveos/moveos-wasm/src/wasm.rs

chore: fix some typos in comments

---

crates/rooch/src/commands/move_cli/commands/publish.rs
crates/testsuite/features/cmd.feature
frameworks/moveos-stdlib/doc/features.md
frameworks/moveos-stdlib/doc/move_module.md
frameworks/moveos-stdlib/sources/features.move
frameworks/moveos-stdlib/sources/move_module.move
frameworks/rooch-framework/doc/onchain_config.md
frameworks/rooch-framework/sources/onchain_config.move
moveos/moveos/src/vm/moveos_vm.rs

1. Disable publishing through MoveAction::ModuleBundle;
2. Add allowlist when publishing modules.

Add allowlist when publishing modules

---

.github/workflows/check_build_test.yml
.gitignore
scripts/bitcoin/README.md
scripts/bitcoin/cmd_alias.sh
scripts/bitcoin/env.sh

Documentation for ord and env is currently not compatible with the latest version

update ord version & lock pnpm version in ci

---

examples/infinite_wand/Move.toml
examples/infinite_wand/sources/infinite_wand.move

[Example] Add example for infinite wand

---

frameworks/moveos-stdlib/doc/features.md
frameworks/moveos-stdlib/doc/wasm.md
frameworks/moveos-stdlib/sources/features.move
frameworks/moveos-stdlib/sources/wasm.move
frameworks/moveos-stdlib/src/natives/moveos_stdlib/rlp.rs
frameworks/rooch-framework/doc/onchain_config.md
frameworks/rooch-framework/sources/onchain_config.move

Add feature flag for wasm. For now, wasm execution in only enabled in local/dev/test network.

add feature flag for wasm

---

docs/website/pages/learn/architecture.en-US.mdx
docs/website/pages/learn/architecture.zh-CN.mdx
docs/website/pages/learn/core-concepts/accounts/_meta.en-US.json

fix links at architecture page

docs: fix links at architecture page

---

crates/rooch-rpc-client/src/lib.rs

resolve https://github.com/rooch-network/rooch/issues/1603

Fix the dead loop issue in data_struct.

---

docs/website/components/layout/footer.tsx
docs/website/components/pages/about.tsx
docs/website/pages/_meta.en-US.json
docs/website/pages/_meta.zh-CN.json
docs/website/pages/about.en-US.mdx
docs/website/pages/build/getting-started/first-blog-system.en-US.mdx
docs/website/pages/build/getting-started/first-blog-system.zh-CN.mdx
docs/website/pages/index.en-US.mdx
docs/website/pages/index.zh-CN.mdx
docs/website/theme.config.tsx

Refactor website content and component layout

Refactor website content and component layout

---

examples/btc_holder_farmer/sources/holder_farmer.move
examples/infinite_wand/sources/infinite_wand.move

fix: object input in infinite_wand & hold_farmer

---

frameworks/bitcoin-move/doc/ord.md
frameworks/bitcoin-move/sources/ord.move
scripts/bitcoin/test.sh

feat: ord add metaprotocol_validity

---

examples/btc_holder_farmer/sources/holder_farmer.move

fix: btc_holder_farmer test code

---

docs/website/pages/blog/the-application-layer-of-bitcoin.en-US.mdx
docs/website/pages/blog/the-application-layer-of-bitcoin.zh-CN.mdx

Add link to application layer of bitcoin

---

examples/btc_holder_farmer/sources/holder_farmer.move
pnpm-lock.yaml
rooch-portal-v1/package.json
rooch-portal-v1/script/env.sh
rooch-portal-v1/src/App.tsx
rooch-portal-v1/src/pages/assets/assets-details/tabs/indexed-assets/components/indexed-assets-btc.tsx
rooch-portal-v1/src/pages/assets/assets-details/tabs/indexed-assets/components/indexed-assets-ordi.tsx
rooch-portal-v1/src/pages/assets/assets-details/tabs/nft/assets-nft.tsx
scripts/bitcoin/env-testnet.sh
scripts/bitcoin/node/run_local_test_node_docker.sh
sdk/typescript/rooch-sdk-kit/src/hooks/client/useOwnedObject.ts
sdk/typescript/rooch-sdk/package.json

updata sdk & fix btc script

---

frameworks/moveos-stdlib/doc/README.md
frameworks/moveos-stdlib/doc/bls12381.md
frameworks/moveos-stdlib/sources/bls12381.move
frameworks/moveos-stdlib/src/natives/mod.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/bls12381.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/mod.rs
frameworks/rooch-framework/src/natives/gas_parameter/bls12381.rs
frameworks/rooch-framework/src/natives/gas_parameter/mod.rs
frameworks/rooch-framework/src/natives/mod.rs

Add bls12381 signature verification function based on fastcrypto according to Sui.
- Closes #1481

[gh-1481] add bls12381 verification.

---

crates/rooch-config/src/store_config.rs
moveos/raw-store/src/rocks/mod.rs

1. add db recovery mode for internal consistence: using PointInTimeRecovery
2. using pipeline write
3. smaller cache for rooch instance

feat(rocksdb): refine configs

---

docs/website/components/index/titleHero.tsx
docs/website/pages/index.en-US.mdx
docs/website/pages/index.zh-CN.mdx

[docs/website]: update the hero title

---

crates/rooch/src/commands/account/commands/mod.rs
crates/rooch/src/commands/account/commands/transfer.rs
crates/rooch/src/commands/account/mod.rs

only supports rooch addresses
#1658

[CLI] Support account transfer command

---

Cargo.toml
crates/rooch/src/commands/init.rs

Add framework-release to default member
Ensure the latest stdlib is generated when build.

[cargo] Add framework-release to default member

---

crates/rooch-framework-tests/src/tests/transaction_validator_tests.rs
crates/rooch-types/src/framework/auth_validator.rs
crates/rooch-types/src/framework/ethereum_validator.rs
crates/rooch-types/src/framework/session_key.rs

Fix session key create session key bug
- Closes #1625

[framework] Fix session key create session key bug

---

.github/workflows/cancel.yml

[ci] Auto cancel previous build

---

frameworks/rooch-framework/doc/ethereum_validator.md
frameworks/rooch-framework/sources/auth_validator/bitcoin_validator.move
frameworks/rooch-framework/sources/auth_validator/ethereum_validator.move
sdk/typescript/rooch-sdk-kit/src/types/WalletRoochSessionAccount.ts
sdk/typescript/rooch-sdk-kit/src/types/wellet/baseWallet.ts

fix btc sign info prefix len > 255

---

Cargo.lock

[release] fix cargo lock for release

[release] fix cargo lock for release

---

crates/rooch-faucet/src/discord.rs
crates/rooch-faucet/src/faucet.rs
crates/rooch-faucet/src/web.rs

update faucet tracing & default amount

---

Cargo.lock
Cargo.toml
crates/rooch-faucet/Cargo.toml
crates/rooch-faucet/README.md
crates/rooch-faucet/src/discord.rs
crates/rooch-faucet/src/faucet.rs
crates/rooch-faucet/src/main.rs
crates/rooch-faucet/src/responses.rs
crates/rooch-faucet/src/web.rs

##web server
- fix web server bid address
- add web api get info
- Insufficient gas balance notify
- Transfer gases failed notify

Faucet discord notify

---

infra/rooch-portal/src/pages/assets/assets-details/tabs/coin/assets-coin.tsx
infra/rooch-portal/src/utils/format.ts
sdk/typescript/rooch-sdk-kit/src/types/WalletAccount.ts

fix portal coin decimals & sdk-kit build error

---

examples/orderbook/Move.toml
examples/orderbook/sources/market.move
examples/orderbook/sources/utils/critbit.move
examples/orderbook/sources/utils/linked_table.move

[Example] Add example for coin orderbook

---

Cargo.lock
Cargo.toml
frameworks/moveos-stdlib/Cargo.toml
frameworks/moveos-stdlib/doc/README.md
frameworks/moveos-stdlib/doc/evm.md
frameworks/moveos-stdlib/sources/evm.move
frameworks/moveos-stdlib/src/natives/mod.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/evm.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/mod.rs
frameworks/rooch-framework/src/natives/gas_parameter/evm.rs
frameworks/rooch-framework/src/natives/gas_parameter/mod.rs
frameworks/rooch-framework/src/natives/mod.rs

implement `0x02 sha256`, `0x06 ecAdd`, `0x08 ecPairing`
- #1465

[moveos_std] Add evm precompiled functions

---

.eslintrc.js
.prettierignore

[pr](https://github.com/rooch-network/rooch/pull/1708/files) move product dir forgot to modify lint checks

fix pnpm lint

---

.github/workflows/docker_build.yml
scripts/check_dev_deploy_status.sh

build and deploy  debug image to dev

---

docs/website/pages/learn/core-concepts/objects/object.en-US.mdx
docs/website/pages/learn/core-concepts/objects/object.zh-CN.mdx
frameworks/moveos-stdlib/doc/object.md
frameworks/moveos-stdlib/sources/object.move

Add doc of object dynamic fields

Doc of object dynamic fields

---

crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
frameworks/moveos-stdlib/sources/evm.move

fix queryObjectStates response bug 

---

crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-rpc-server/src/service/rpc_service.rs
crates/rooch/src/commands/account/commands/list.rs
crates/rooch/src/commands/account/commands/transfer.rs
crates/rooch/src/commands/move_cli/commands/run_function.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/move_module.rs
moveos/metrics/src/op_counters.rs
moveos/moveos-object-runtime/src/runtime.rs
moveos/moveos-types/src/state.rs
moveos/moveos-wasm/src/wasm.rs
moveos/moveos/src/vm/tx_argument_resolver.rs
moveos/moveos/src/vm/unit_tests/vm_arguments_tests.rs

fix some typos

---

frameworks/bitcoin-move/doc/bitcoin.md
frameworks/bitcoin-move/doc/types.md
frameworks/bitcoin-move/sources/bitcoin.move
frameworks/bitcoin-move/sources/types.move

I have added a test case. #1763

[Bitcoin] Verify the bitcoin header

---

crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs
crates/rooch-rpc-server/src/server/rooch_server.rs

Fixup get state by filed bugs. 
- Closes #1794

[State] Fixup state query bug

---

.github/workflows/deploy_testnet.yml

fix testnet deploy

---

crates/rooch-types/src/address.rs

[cli] ParsedAddress support Bitcoin address

---

docs/website/pages/blog/the-application-layer-of-bitcoin.en-US.mdx
docs/website/pages/blog/the-application-layer-of-bitcoin.zh-CN.mdx
docs/website/pages/learn/overview.en-US.mdx

[blog] Update the application layer of bitcoin

---

.github/workflows/release_asset.yml

Accord to the docs from https://github.com/arduino/setup-protoc
use github token to avoid rate limiting

avoid rate limiting with token

---

docs/website/pages/build/getting-started/first-contract.en-US.mdx
docs/website/pages/build/getting-started/first-contract.zh-CN.mdx

modify hello world

---

docs/website/pages/index.en-US.mdx
docs/website/pages/index.zh-CN.mdx

update the ecosystem:
- Remove `Babylon`
- Add `Donut`

refactor: update the ecosystem

---

frameworks/moveos-stdlib/sources/wasm.move

remove unused alias
remove unused alias

remove unused alias

---

docs/website/pages/build/getting-started/connect-to-rooch/connect-testnet.en-US.mdx
docs/website/pages/build/getting-started/connect-to-rooch/connect-testnet.zh-CN.mdx

`rooch env switch test`  ==> `rooch env switch --alias test`

switch testnet

---

docs/website/pages/build/getting-started/first-token/coin-intro.en-US.mdx
docs/website/pages/build/getting-started/first-token/coin-intro.zh-CN.mdx

modify first coin

---

.github/actions/rust-setup/action.yaml

[ci] action-rs/toolchain to v1

---

crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/api/rooch_api.rs
crates/rooch-rpc-api/src/jsonrpc_types/address.rs
crates/rooch-rpc-api/src/jsonrpc_types/event_view.rs
crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs
crates/rooch-rpc-api/src/jsonrpc_types/transaction_view.rs
crates/rooch-rpc-client/src/rooch_client.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/testsuite/features/cmd.feature

Introduce RoochOrBitcoinAddressView

---

docs/website/pages/build/rooch-framework/_meta.en-US.json
docs/website/pages/build/rooch-framework/_meta.zh-CN.json
docs/website/pages/build/rooch-framework/data-struct.en-US.mdx
docs/website/pages/build/rooch-framework/data-struct.zh-CN.mdx
docs/website/pages/build/rooch-framework/private-generics.en-US.mdx
docs/website/pages/build/rooch-framework/private-generics.zh-CN.mdx
docs/website/pages/learn/core-concepts/move-contracts/built-in-library.en-US.mdx
docs/website/pages/learn/core-concepts/move-contracts/built-in-library.zh-CN.mdx
docs/website/pages/learn/core-concepts/move-contracts/move-on-rooch.en-US.mdx
docs/website/pages/learn/core-concepts/move-contracts/move-on-rooch.zh-CN.mdx
docs/website/pages/learn/core-concepts/objects/object.en-US.mdx
docs/website/pages/learn/core-concepts/objects/object.zh-CN.mdx
frameworks/moveos-stdlib/doc/bcs.md
frameworks/moveos-stdlib/sources/bcs.move

[docs] Update move-on-rooch relative docs

---

crates/rooch-indexer/src/actor/reader_indexer.rs
crates/rooch-indexer/src/indexer_reader.rs
crates/rooch-indexer/src/store/sqlite_store.rs
crates/rooch-indexer/src/tests/test_indexer.rs
crates/rooch/src/commands/indexer/commands/rebuild.rs
crates/rooch/src/commands/statedb/README.md
crates/rooch/src/commands/statedb/commands/export.rs

Followup @https://github.com/rooch-network/rooch/pull/1829

[CLI] Remove export filed state for rebuild indexer cli

---

.github/workflows/check_build_test.yml

Using relative path to reference the action in the current branch

---

docs/website/theme.config.tsx

feat: update meta tags

---

infra/rooch-portal/package.json
infra/rooch-portal/src/components/amount-input.tsx
infra/rooch-portal/src/components/recipient-input.tsx
infra/rooch-portal/src/pages/assets/assets-details/tabs/bitcoin-assets/components/bitcoin-assets-ordi.tsx
infra/rooch-portal/src/pages/assets/assets-details/tabs/coin/assets-coin.tsx
infra/rooch-portal/src/pages/settings/components/manage-sessions.tsx
infra/rooch-portal/src/pages/settings/settings-layout.tsx
infra/rooch-portal/src/utils/format.ts
pnpm-lock.yaml

Portal 240616

---

infra/rooch-portal/package.json
infra/rooch-portal/src/pages/settings/components/manage-sessions.tsx
infra/rooch-portal/src/utils/format.ts
pnpm-lock.yaml

Portal 240617

---

crates/rooch/src/commands/move_cli/commands/build.rs

Export package binary in BCS  when `rooch move bulid`
- Closes #1889

export package binary

---

.github/CODEOWNERS
.github/dependabot.yml

[ci] Update dependabot config

---

scripts/dev_setup.sh

retry rustup

---

.github/workflows/cancel.yml
.github/workflows/deploy_mainnet.yml

[ci] Auto cancel the docker_build task

---

crates/rooch-db/src/lib.rs
crates/rooch-sequencer/src/actor/sequencer.rs
crates/rooch-store/src/lib.rs
crates/rooch-store/src/tests/mod.rs
crates/rooch-store/src/tests/test_accumulator.rs

Following #/1932
1. Add sequencer accumulator test cases
2. Update last accumulator info in sequencer

[Testcase] Add sequencer accumulator test cases

---

docs/website/components/blog/blogIndex.tsx
docs/website/components/blog/postHeader.tsx
docs/website/pages/blog/early-builders.en-US.mdx
docs/website/pages/blog/early-builders.zh-CN.mdx
docs/website/pages/blog/partnership-announcement-avail.en-US.mdx
docs/website/pages/blog/partnership-announcement-avail.zh-CN.mdx
docs/website/pages/blog/showcase-insights.en-US.mdx
docs/website/pages/blog/showcase-insights.zh-CN.mdx
docs/website/pages/blog/sprouting-of-rooch.en-US.mdx
docs/website/pages/blog/sprouting-of-rooch.zh-CN.mdx
docs/website/pages/blog/the-application-layer-of-bitcoin.en-US.mdx
docs/website/pages/blog/the-application-layer-of-bitcoin.zh-CN.mdx

Website blog

---

crates/rooch-relayer/src/actor/bitcoin_relayer.rs
crates/rooch-relayer/src/actor/ethereum_relayer.rs
crates/rooch-relayer/src/actor/messages.rs
crates/rooch-relayer/src/actor/mod.rs
crates/rooch-relayer/src/actor/relayer.rs
crates/rooch-relayer/src/actor/relayer_proxy.rs
crates/rooch-relayer/src/lib.rs
crates/rooch-types/src/bitcoin/pending_block.rs
frameworks/bitcoin-move/doc/pending_block.md
frameworks/bitcoin-move/sources/genesis.move
frameworks/bitcoin-move/sources/pending_block.move

Part of #1797 , follow #1933
TODO
1. test rerog

[bitcoin] Refactor bitcoin relayer to load ready l1 txs from pending block contract

---

docs/website/components/blog/postHeader.tsx
docs/website/theme.config.tsx

[Website] SEO Enhancement

---

infra/rooch-portal/src/pages/assets/assets-details/tabs/coin/assets-coin.tsx
sdk/typescript/rooch-sdk/src/constants/gas.ts

fix portal gas

---

docs/website/theme.config.tsx

[Website] update theme configuration

---

docs/website/components/blog/postHeader.tsx

refactor: update `postHeader.tsx`

---

crates/rooch-config/src/store_config.rs
crates/rooch-db/src/lib.rs
crates/rooch/src/commands/indexer/commands/mod.rs
moveos/moveos-store/src/lib.rs
moveos/moveos-store/src/transaction_store/mod.rs

Merge Storage Instance to one
- Closes #1596

[storage] Merge Storage Instance

---

docs/website/components/blog/postHeader.tsx
docs/website/theme.config.tsx

[Website] Update

---

.github/workflows/deploy_testnet.yml
Cargo.lock
Cargo.toml
crates/rooch-open-rpc-spec/schemas/openrpc.json

Prepare v0.5.6

---

docs/website/components/blog/postHeader.tsx
docs/website/theme.config.tsx

feat: update head

---

crates/rooch-framework-tests/src/tests/mod.rs
crates/rooch-framework-tests/src/tests/view_function_gas.rs
crates/testsuite/features/cmd.feature
examples/view_function_loop/Move.toml
examples/view_function_loop/readme.md
examples/view_function_loop/sources/wasm.move
examples/view_function_loop/web/README.md
moveos/moveos/src/moveos.rs

resolve https://github.com/rooch-network/rooch/issues/1675

Enable gas metering for the view function

---

crates/rooch/src/commands/statedb/commands/genesis_ord.rs
crates/rooch/src/commands/statedb/mod.rs

1. add genesis-ord cmd for statedb
2. fix bitcoin address according new changes

chore: add genesis-ord cmd for statedb

---

frameworks/moveos-stdlib/src/natives/moveos_stdlib/object.rs
moveos/moveos-object-runtime/src/field_value.rs
moveos/moveos-object-runtime/src/lib.rs
moveos/moveos-object-runtime/src/runtime.rs
moveos/moveos-object-runtime/src/runtime_object.rs
moveos/moveos-object-runtime/src/tx_context.rs
moveos/moveos/src/vm/data_cache.rs
moveos/moveos/src/vm/tx_argument_resolver.rs

Refactor ObjectRuntime split runtime.rs to mods, no business logic changed, prepare for future refactor, part of #2024

[object] Refactor ObjectRuntime split runtime.rs to mods

---

Cargo.lock
Cargo.toml
crates/rooch-faucet/Cargo.toml
crates/rooch-faucet/src/metrics_layer.rs
crates/rooch-faucet/src/web.rs
frameworks/bitcoin-move/Cargo.toml
frameworks/bitcoin-move/src/natives/ord/inscription.rs
frameworks/rooch-framework/Cargo.toml

- Closes #1929
replace http with axum::http`

[deps] remove http

---

crates/rooch/src/commands/statedb/commands/genesis_ord.rs

The commit introduces a fallback mechanism for getting the public key from a script buffer when the initial attempt from a string fails. This ensures that the program won't crash if the address passed is not directly transformable to a public key. A ScriptBuf instance is created from the address and its public key is retrieved.

fix(statedb): Add fallback for getting public key from script buffer

---

crates/rooch/src/commands/statedb/commands/genesis_ord.rs
moveos/raw-store/src/rocks/mod.rs

origin way not work: set blob option in db option

fix(rocks): set blob option for each column family

---

docs/website/pages/index.en-US.mdx
docs/website/pages/index.zh-CN.mdx

[Website] Update the ecosystem

---

Cargo.lock
crates/rooch-open-rpc-spec-builder/src/examples.rs
crates/rooch-rpc-server/Cargo.toml
crates/rooch-rpc-server/src/lib.rs

rooch rpc request --method rpc.discover
- Closes #2021

[rpc] Implement json rpc Discovery method

---

docs/website/pages/build/getting-started/installation.en-US.mdx
docs/website/pages/build/getting-started/installation.zh-CN.mdx

[writing error](https://github.com/rooch-network/rooch/commit/4d80e20d0e3d05ff7730593c2c3958ca85d1bc98)

writing error

---

Cargo.lock
Cargo.toml
frameworks/move-stdlib/doc/vector.md
frameworks/move-stdlib/sources/vector.move

resolve #2093 
The relatated Move library commit is https://github.com/rooch-network/move/commit/8cadfe162379deb96ae88a3764fac3dea58cb944

Add a native function implementation of 0x1::vector::append. 

---

.github/workflows/release_asset.yml

release both intel and arm for macOS

---

docs/website/pages/build/getting-started/installation.en-US.mdx
docs/website/pages/build/getting-started/installation.zh-CN.mdx
docs/website/pages/build/tutorial/blog-demo.en-US.mdx
docs/website/pages/build/tutorial/blog-demo.zh-CN.mdx

chore(links): Update wget link for binary installation

---

examples/orderbook/sources/market.move
examples/orderbook/sources/utils/linked_table.move

fix: change orderbook example create object function

---

Cargo.lock
Cargo.toml
crates/rooch-indexer/src/indexer_reader.rs
crates/rooch-indexer/src/lib.rs

1. Resolve the problem of trace log being hijacked and not outputting
2. Optimize Sqlite connection acquisition and database locked exception

[Log] Resolve the problem of trace log being hijacked and not outputting

---

crates/rooch-types/src/framework/session_key.rs
crates/rooch/src/commands/session_key/commands/list.rs
crates/testsuite/features/cmd.feature

[cli] refactor list

---

Cargo.lock
Cargo.toml
frameworks/moveos-stdlib/Cargo.toml
frameworks/moveos-stdlib/src/natives/moveos_stdlib/hash.rs

Replace with external libs and upstream fastcrypto.
- Closes #2152

[gh-2152] use external dependencies to replace with the custom fastcrypto lib.

---

examples/btc_holder_farmer/sources/holder_farmer.move

feat: add check_asset_is_staked func

---

crates/rooch/src/lib.rs

make more pretty to command help inteface

---

Cargo.lock
Cargo.toml
frameworks/moveos-stdlib/Cargo.toml
frameworks/moveos-stdlib/doc/README.md
frameworks/moveos-stdlib/doc/groth16.md
frameworks/moveos-stdlib/sources/groth16.move
frameworks/moveos-stdlib/src/natives/mod.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/groth16.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/mod.rs
frameworks/rooch-framework/src/natives/gas_parameter/groth16.rs
frameworks/rooch-framework/src/natives/gas_parameter/mod.rs
frameworks/rooch-framework/src/natives/mod.rs
moveos/smt/src/jellyfish_merkle/jellyfish_merkle_test.rs
moveos/smt/src/tests.rs

Add preparation of verifying key and verification of Groth16 proof based on Sui implementation.
- Closes #1644

[gh-1644] add groth16 verification support.

---

pnpm-lock.yaml
sdk/typescript/rooch-sdk/package.json
sdk/typescript/rooch-sdk/src/client/client.ts
sdk/typescript/rooch-sdk/src/client/types/generated.ts
sdk/typescript/rooch-sdk/src/client/types/params.ts
sdk/typescript/rooch-sdk/src/crypto/authenticator.test.ts
sdk/typescript/rooch-sdk/src/crypto/authenticator.ts
sdk/typescript/rooch-sdk/src/keypairs/secp256k1/keypair.ts
sdk/typescript/rooch-sdk/src/session/session.ts
sdk/typescript/rooch-sdk/src/utils/bytes.ts
sdk/typescript/rooch-sdk/test-e2e/case/session.test.ts
sdk/typescript/templates/react-counter/src/main.tsx

update sdk gen & fix bitcoin auth length

---

sdk/typescript/rooch-sdk/README.md
sdk/typescript/rooch-sdk/src/client/types/generated.ts

update sdk gen & doc

---

crates/rooch-indexer/src/actor/indexer.rs
crates/rooch-indexer/src/indexer_reader.rs
crates/rooch-indexer/src/tests/test_indexer.rs
crates/rooch-rpc-api/src/jsonrpc_types/address.rs
crates/rooch-rpc-api/src/jsonrpc_types/btc/ord.rs
crates/rooch-rpc-api/src/jsonrpc_types/btc/utxo.rs
crates/rooch-rpc-server/src/service/aggregate_service.rs
crates/rooch-types/src/indexer/state.rs

Unify owner to AccountAddress to ensure write and read consistency
- Closes #2175

Fixup object query random fail

---

crates/rooch-key/src/key_derive.rs
crates/rooch-key/src/keystore/account_keystore.rs
crates/rooch-key/src/keystore/base_keystore.rs
crates/rooch-rpc-api/src/jsonrpc_types/export_view.rs
crates/rooch-rpc-api/src/jsonrpc_types/mod.rs
crates/rooch-types/src/crypto.rs
crates/rooch-types/src/lib.rs
crates/rooch-types/src/rooch_key.rs
crates/rooch/src/commands/account/commands/export.rs
crates/rooch/src/commands/account/commands/import.rs
crates/rooch/src/commands/account/commands/mod.rs
crates/rooch/src/commands/account/mod.rs
crates/testsuite/features/cmd.feature

Add `account import` module as a pair of #2134.
- Closes #1094

[gh-1094] add account import module.

---

crates/rooch/src/commands/statedb/commands/genesis_ord.rs
crates/rooch/src/commands/statedb/commands/genesis_utxo.rs

print:
1. cost of produce updates batch
2. max height of utxo
3. state root of utxo/ord/address_map

chore: print more details in genesis_<ord/utxo> tool process

---

crates/rooch-key/src/keystore/base_keystore.rs
crates/rooch-key/src/keystore/types.rs
crates/rooch-types/src/address.rs
crates/rooch-types/src/crypto.rs
crates/rooch/src/commands/account/commands/list.rs

Rooch CLI `account list` command outputs the nostr bech32 public key.
- Closes #2211

[gh-2211] print nostr bech32 address.

---

crates/rooch-benchmarks/src/tx.rs
crates/rooch-config/src/lib.rs
crates/rooch-executor/src/actor/executor.rs
crates/rooch-framework-tests/src/binding_test.rs
crates/rooch-pipeline-processor/src/actor/processor.rs
crates/rooch-rpc-api/src/lib.rs
crates/rooch-rpc-server/src/lib.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-sequencer/src/actor/sequencer.rs
crates/rooch-sequencer/tests/test_sequencer.rs

Add read_only option to server option to figure out the panic issue.
#2232

[system] Add read_only option to server option

---

frameworks/moveos-stdlib/src/natives/moveos_stdlib/move_module.rs

resolve https://github.com/rooch-network/rooch/issues/2232

Hold the panic from move verifier.

---

crates/rooch-rpc-client/src/wallet_context.rs
moveos/moveos-types/src/moveos_std/gas_schedule.rs

Set CLI default max gas amount to 1_00_000_000

[cli] Update CLI default max gas amount

---

Cargo.lock
crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/Cargo.toml
crates/rooch-rpc-api/src/api/rooch_api.rs
crates/rooch-rpc-api/src/jsonrpc_types/address.rs
crates/rooch-rpc-api/src/jsonrpc_types/btc/ord.rs
crates/rooch-rpc-api/src/jsonrpc_types/btc/utxo.rs
crates/rooch-rpc-api/src/jsonrpc_types/event_view.rs
crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs
crates/rooch-rpc-api/src/jsonrpc_types/transaction_view.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
crates/rooch-types/src/address.rs
crates/testsuite/features/cmd.feature

According to discussion of #2209.
- Closes #2233

[gh-2233] rename address view and update address view to include nostr.

---

crates/rooch/src/commands/statedb/commands/export.rs

Refactor the `export.rs` logic in `Rooch` for easier management and repeated use. Abstracted the object states retrieval and genesis field export logic into their own functions. This makes them more modular and promotes code reuse. Both the `export_genesis` and `export_indexer` functions have been modified to use these abstracted functions.

fix(statedb): fix export indexer

---

crates/rooch-rpc-server/src/service/rpc_service.rs

Fix bug of #2241 
- Closes #2241

fix rpc owner_bitcoin_address

---

crates/rooch/src/commands/move_cli/commands/build.rs
pnpm-lock.yaml
sdk/typescript/rooch-sdk/package.json
sdk/typescript/rooch-sdk/src/client/client.ts
sdk/typescript/rooch-sdk/src/utils/b64.ts
sdk/typescript/rooch-sdk/test-e2e/case/checkpoint.test.ts
sdk/typescript/rooch-sdk/test-e2e/case/module-abi.test.ts
sdk/typescript/rooch-sdk/test-e2e/case/session.test.ts
sdk/typescript/rooch-sdk/test-e2e/setup.ts

sdk add publish package, but the build has not yet fully exported the binary

add discover & add module abi 

---

infra/rooch-portal/src/pages/mint/list/coming-soon.tsx
infra/rooch-portal/src/pages/mint/list/demo-tokens.tsx
infra/rooch-portal/src/pages/mint/list/layout.tsx
sdk/typescript/rooch-sdk/test-e2e/case/session.test.ts

mint add coming-soon tokens

---

crates/rooch/Cargo.toml
crates/rooch/build.rs
crates/rooch/src/lib.rs

Support Git commit hash in `rooch -V` or `rooch --version`.
- Closes #2242

[gh-2242] change to long_version.

---

docs/website/components/blog/blogIndex.tsx

[Summary about this PR](fix: fix blog repeat)

fix: fix blog repeat

---

frameworks/framework-release/released/2/README.md
frameworks/framework-release/released/3/README.md

[docs] Add framework release notes

---

crates/rooch/src/commands/object.rs

update rooch object default filter
update default object filter as query active_address's objects.

update rooch object default filter

---

frameworks/bitcoin-move/doc/utxo.md
frameworks/bitcoin-move/sources/utxo.move

[bitcoin-move] Deprecated utxo seal function

---

docs/website/pages/build/bitcoin/programming_with_utxo_and_inscription.zh-CN.mdx

fix doc error

---

crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/jsonrpc_types/rpc_options.rs
crates/rooch-rpc-client/src/wallet_context.rs
crates/rooch-rpc-server/src/server/rooch_server.rs
sdk/typescript/rooch-sdk/src/client/types/generated.ts

decode transaction events

---

crates/rooch/src/commands/statedb/commands/mod.rs

Added `min` and `max` boundaries for `OutpointInscriptionsMap` to ensure better filtering of outpoints.

chore(statedb/genesis): add boundaries and verification to OutpointInscriptionsMap

---

crates/rooch/src/commands/move_cli/commands/run_view_function.rs

typo: run a view function

---

crates/rooch/src/commands/statedb/commands/genesis_verify.rs
crates/rooch/src/commands/statedb/commands/mod.rs
crates/rooch/src/commands/statedb/commands/utxo.rs

has verified: raw_data -> data_in_statedb <- raw_data
added in this PR: raw_data -> data_in_statedb -> raw_data
reverse UTXO got from statedb to raw UTXO, then comparing them:
UTXO has more complicated struct than Inscirption in state_db: complex struct like SimpleMap.

refactor(statedb/genesis-verify): reserve UTXO got from statedb to raw UTXO for verifying

---

crates/rooch-executor/src/actor/executor.rs
moveos/moveos/src/moveos.rs

resolve https://github.com/rooch-network/rooch/issues/2382

[VM] Reload all the native functions after the gas schedule upgrade.

---

crates/rooch-types/src/framework/coin.rs
moveos/moveos-types/src/move_types.rs

Implement TypeTag&StructTag from_canonical_string
fix #2394

[move] Implement TypeTag&StructTag from_canonical_string

---

crates/rooch/src/commands/statedb/commands/export.rs

1. export top level fields of object
2. implements detailed logging during export processes
3. improves CSV writer configuration for better performance.
4. remove dead code

refactor(statedb/export): refactor export logic and enhance logging

---

crates/rooch-framework-tests/src/tests/multisign_account_tests.rs
crates/rooch-types/src/nursery/multisign_account.rs
frameworks/rooch-nursery/doc/multisign_account.md
frameworks/rooch-nursery/sources/multisign_account.move

Follow #2294 and #2373 
Sort the x-only public keys when generating multisign account

[multisign_account] Sort x only public keys when generate multisign account

---

frameworks/rooch-nursery/doc/multisign_account.md
frameworks/rooch-nursery/doc/taproot_builder.md
frameworks/rooch-nursery/sources/multisign_account.move
frameworks/rooch-nursery/sources/taproot_builder.move
frameworks/rooch-nursery/tests/taproot_builder_test.move

Follow #2373 and #2416, `taprot_builder::finalize` function return `Result<address, TaprootBuilder>`.

[bitcoin] taproot builder return result

---

crates/rooch/src/commands/statedb/commands/genesis_verify.rs

Extended the `genesis_verify` script to track and display counters for not found UTXOs and addresses, in addition to mismatched counts. Updated logging statements to include this information, improving diagnostic capabilities.

chore: add counters for not found UTXOs and addresses in genesis-verify process

---

crates/rooch/src/commands/indexer/commands/rebuild.rs

Replace std::thread with tokio::task::spawn_blocking for producing and applying updates. This improves asynchronous handling and integrates better with the Tokio runtime.
fixed this when rebuild:
```shell
2024-08-14T21:58:40.926122Z INFO rooch::commands::indexer::commands::rebuild: indexer rebuild started
thread '<unnamed>' panicked at crates/rooch-indexer/src/indexer_reader.rs:119:13:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Indexer rebuild task finished(0 updates applied) in: 21.674956ms
Error: Produce updates error
```

fix(indexer/rebuild): switch to Tokio for threading in rebuild.rs for fixing panic when rebuild indexer

---

frameworks/bitcoin-move/sources/ord.move

1. rm is_cursed check when create new inscription
2. reformat code and improve readability

refactor(bitcoin-move): rm is_cursed check when create new inscription

---

frameworks/moveos-stdlib/doc/bcs.md
frameworks/moveos-stdlib/sources/bcs.move

Add `peel` function referred from Sui for `bcs.move`.
- Closes #2417

[gh-2417] add peel functions for bcs.move.

---

crates/rooch/src/lib.rs
crates/testsuite/features/cmd.feature

Alias `tx` for subcommand `transaction`.
- Closes #2468

[gh-2468] add a visible alias for transaction.

---

scripts/bitcoin/README.md
scripts/bitcoin/cmd_alias_docker.sh
scripts/bitcoin/cmd_alias_podman.sh

Optimizing the Bitcoin local development environment documentation

Optimizing the Bitcoin local development environment documentation

---

docker/Dockerfile
docker/DockerfileDebug

install SQLite 3.46.1 in the dockerfile

---

sdk/typescript/rooch-sdk/test-e2e/case/bitcoin.test.ts

sdk query inscriptions test

---

crates/rooch-rpc-api/src/jsonrpc_types/execute_tx_response.rs
crates/rooch/src/commands/move_cli/commands/run_function.rs

Following #2458 
- Closes #2385 again.

[gh-2458] return dry run result before executing txs.

---

frameworks/bitcoin-move/doc/multisign_account.md
frameworks/bitcoin-move/sources/multisign_account.move
frameworks/bitcoin-move/sources/script_buf.move
frameworks/move-stdlib/doc/vector.md
frameworks/move-stdlib/sources/vector.move
frameworks/move-stdlib/tests/vector_tests.move
frameworks/moveos-stdlib/doc/README.md
frameworks/moveos-stdlib/doc/compare.md
frameworks/moveos-stdlib/doc/sort.md
frameworks/moveos-stdlib/sources/compare.move
frameworks/moveos-stdlib/sources/sort.move
frameworks/moveos-stdlib/tests/sort_tests.move

1. [moveos_std] Implement compare::compare
2. [moveos_std] Implement sort::sort
3. [move_std] Sync vector::slice from aptos-move

[framework] Implement compare and sort

---

frameworks/bitcoin-move/doc/bitcoin.md
frameworks/bitcoin-move/sources/bitcoin.move

[framework] add unpack_transfer_utxo_event function

---

infra/rooch-portal/package.json
pnpm-lock.yaml

[Summary about this PR](fix: package compatible)

fix: package compatible

---

Cargo.lock
crates/rooch/Cargo.toml
crates/rooch/src/commands/statedb/commands/mod.rs

Refactor UTXO_SEAL_INSCRIPTION_PROTOCOL to use lazy_static for initialization.

chore(statedb/genesis): migrate protocol constant to lazy_static

---

infra/rooch-portal-v2/src/sections/account/view.tsx
infra/rooch-portal-v2/src/sections/search/overview.tsx

[Summary about this PR](fix: portal search account issue)

fix: portal search account issue

---

crates/rooch-rpc-client/src/rooch_client.rs
crates/rooch/src/cli_types.rs
crates/rooch/src/commands/transaction/commands/mod.rs
crates/rooch/src/commands/transaction/commands/query.rs
crates/rooch/src/commands/transaction/mod.rs

Closes #2239 
Support query transaction.
```bash
rooch transaction query
error: the following required arguments were not provided:
<--sender <SENDER>|--tx-hashes <TX_HASHES>|--start-time <START_TIME>|--end-time <END_TIME>|--from-order <FROM_ORDER>|--to-order <TO_ORDER>>
```
```bash
rooch transaction query --from-order 1
error: the following required arguments were not provided:
--to-order <TO_ORDER>
```
```bash
rooch transaction query --sender tb1pegyjdeycwtwt9s05eafwmj4qf93qjkvujem8myhx5rwktxutfq5ss2ndms --limit 1
```
```json
{
"data": [
{
"transaction": {
"data": {
"type": "l2_tx",
"sequence_number": "1060",
"sender": "rooch1vlvfs806fd4dy64qjv87ek5h9jhgvkvctvcr8nwlmaqj34r9888ssm6jk2",
"sender_bitcoin_address": "tb1pegyjdeycwtwt9s05eafwmj4qf93qjkvujem8myhx5rwktxutfq5ss2ndms", …
```

feat(cli): support query transaction

---

Cargo.lock
Cargo.toml
moveos/moveos-wasm/src/middlewares/gas_metering.rs

upgrade wasmer-compiler-singlepass to v.4.3.6

---

frameworks/bitcoin-move/doc/README.md
frameworks/bitcoin-move/doc/consensus_codec.md
frameworks/bitcoin-move/sources/consensus_codec.move

Implement Bitcoin consensus encode/decode

[bitcoin-move] Implement Bitcoin consensus encode/decode

---

crates/rooch/src/commands/statedb/README.md
crates/rooch/src/commands/statedb/commands/export.rs

1. Added detailed steps in the README to guide users through setting up the genesis state. 
2. Improved the export command to handle optional paths more gracefully.

feat(rooch): add new instructions for exporting states for rebuilding indexer

---

docker/Dockerfile
docker/DockerfileDebug

add oracle

---

frameworks/rooch-framework/sources/address_mapping.move
frameworks/rooch-framework/sources/tests/transfer_test.move
frameworks/rooch-framework/sources/transfer.move

[framework] Binding bitcoin address when transfer

---

crates/rooch-rpc-client/src/wallet_context.rs
crates/rooch/src/cli_types.rs
crates/rooch/src/commands/transaction/commands/build.rs

Support custom account sequence_number for rooch tx build
- Closes #2632

[Cli] Build tx with sequence number

---

scripts/deploy_rooch_mainnet.sh
scripts/deploy_rooch_testnet.sh

Distinguish between the container names of mainnet and testnet for log collection.

mainnet and testnet container name

---

frameworks/moveos-stdlib/doc/json.md
frameworks/moveos-stdlib/sources/json.move
frameworks/moveos-stdlib/src/natives/moveos_stdlib/json.rs
frameworks/rooch-framework/src/natives/gas_parameter/json.rs
scripts/bitcoin/test.sh

https://github.com/rooch-network/rooch/issues/2655

feat: impl to_json

---

crates/rooch-relayer/src/actor/bitcoin_relayer.rs
crates/rooch-relayer/src/actor/relayer.rs
crates/rooch-relayer/src/actor/relayer_proxy.rs
scripts/deploy_rooch_testnet.sh

fix relayer stall caused by blocking actor

[relayer] Refactor relayer to resolve the sync process block issue

---

crates/rooch/src/commands/move_cli/commands/publish.rs

batch-get the modules to the client before verifying.
- Closes #2627

download modules when verify

---

crates/rooch/src/commands/transaction/commands/build.rs
crates/rooch/src/commands/upgrade/commands/upgrade_gas_config.rs

Fix upgrade-gas-config command, build tx and do not directly sign and execute

[cli] Fix upgrade-gas-config command, build tx and do not directly sign and execute

---

infra/rooch-portal-v2/contract/gas_market/sources/gas_market.move
infra/rooch-portal-v2/contract/gas_market/sources/trusted_oracle.move

refact gas market info and format code

---

moveos/moveos-types/src/access_path.rs

[rpc] fix accesspath

---

crates/rooch-db/src/lib.rs
crates/rooch-framework-tests/src/tests/multisign_account_tests.rs
crates/rooch-key/src/keystore/base_keystore.rs
crates/rooch-key/src/keystore/file_keystore.rs
crates/rooch-key/src/keystore/memory_keystore.rs
crates/rooch-open-rpc-macros/src/lib.rs
crates/rooch-rpc-api/src/jsonrpc_types/btc/utxo.rs
crates/rooch/src/commands/account/commands/list.rs
crates/rooch/src/commands/statedb/commands/mod.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/json.rs
frameworks/rooch-nursery/src/natives/wasm.rs
moveos/raw-store/src/lib.rs

use HashMap::with_capacity avoid resize

use HashMap::with_capacity

---

docs/website/pages/blog/hacker-house-1th.en-US.mdx
docs/website/pages/blog/hacker-house-1th.zh-CN.mdx

blog: add Balylon hacker house zh

---

infra/rooch-portal-v2/src/app/faucet/[address]/page.tsx
infra/rooch-portal-v2/src/app/faucet/page.tsx
infra/rooch-portal-v2/src/components/swap/swap-transaction-header.tsx
infra/rooch-portal-v2/src/config/constant.ts
infra/rooch-portal-v2/src/hooks/use-networks.ts
infra/rooch-portal-v2/src/layouts/config-nav-dashboard.tsx
infra/rooch-portal-v2/src/middleware.ts
infra/rooch-portal-v2/src/routes/paths.ts
infra/rooch-portal-v2/src/sections/faucet/overview.tsx
infra/rooch-portal-v2/src/sections/faucet/view.tsx
infra/rooch-portal-v2/src/sections/gas-swap/index.tsx

portal gas faucet

---

infra/rooch-portal-v2/src/utils/env.ts

fix portal main env

---

crates/rooch-faucet/src/discord.rs

[faucet]beautify error message

---

crates/rooch-da/src/actor/server.rs

Enhanced error messages during background submission and improved clarity of log statements. This facilitates better debugging and provides clearer status updates.

fix(rooch-da): improve error handling and logging

---

infra/rooch-portal-v2/src/app/account/page.tsx
infra/rooch-portal-v2/src/app/faucet/[address]/page.tsx
infra/rooch-portal-v2/src/app/faucet/page.tsx
infra/rooch-portal-v2/src/components/auth/session-key-guard-button.tsx
infra/rooch-portal-v2/src/sections/assets/components/coin-transfer-modal.tsx
infra/rooch-portal-v2/src/sections/assets/overview.tsx
infra/rooch-portal-v2/src/sections/faucet/view.tsx
infra/rooch-portal-v2/src/sections/transactions/overview.tsx
infra/rooch-portal-v2/src/utils/env.ts

[Summary about this PR](feat: portal session key optimization)

feat: portal session key optimization

---

examples/btc_holder_farmer/sources/holder_farmer.move
frameworks/bitcoin-move/sources/bitcoin.move

support bbn mining grow

---

Cargo.lock
crates/testsuite/features/vector_object.feature
examples/vector_object/Move.toml
examples/vector_object/sources/main.move
moveos/moveos-object-runtime/Cargo.toml
moveos/moveos-object-runtime/src/resolved_arg.rs
moveos/moveos-object-runtime/src/runtime.rs
moveos/moveos/Cargo.toml
moveos/moveos/src/vm/tx_argument_resolver.rs

Implemented passing vector<Object<T>> type in parameters, with type and permission checks completed.

Implement the vector<Object<T>> type in entry function

---

infra/rooch-portal-v2/next.config.mjs
infra/rooch-portal-v2/src/sections/assets/components/asset-row-item.tsx
infra/rooch-portal-v2/src/sections/assets/components/assets-table-card.tsx

[Summary about this PR](feat: portal assets table add coin icon display)
related PR: https://github.com/rooch-network/rooch/issues/2789

feat: portal assets table add coin icon display

---

.github/workflows/deploy_mainnet.yml
scripts/deploy_rooch_mainnet.sh

Added OPENDA_GCP_MAINNET_BUCKET and OPENDA_GCP_MAINNET_CREDENTIAL to deploy_mainnet.yml and deploy_rooch_mainnet.sh. This facilitates easy deployment by providing necessary GCP resources.

feat(ci): update deploy script to include GCP bucket and credentials

---

kube/testnet/tbtc-faucet/tbtc-deployment.yaml
kube/testnet/tbtc-faucet/tbtc-pvc.yaml

add tbtc kube file

---

Cargo.lock
Cargo.toml
crates/rooch-types/src/crypto.rs

bump derive_more from 0.99.18 to 1.0.0

---

Cargo.toml
crates/rooch-db/src/lib.rs
crates/rooch-rpc-api/src/jsonrpc_types/execute_tx_response.rs
crates/rooch-types/src/crypto.rs
crates/rooch-types/src/transaction/rooch.rs
crates/rooch/src/commands/bitseed/inscribe.rs
crates/rooch/src/commands/upgrade/commands/upgrade_gas_config.rs
frameworks/bitcoin-move/src/natives/ord/envelope.rs
frameworks/rooch-nursery/src/natives/wasm.rs
moveos/metrics/src/lib.rs
moveos/metrics/src/metered_channel.rs
moveos/metrics/src/monitored_mpsc.rs
moveos/moveos-commons/accumulator/src/node_index.rs
moveos/moveos-commons/accumulator/src/tests/test_accumulator.rs
moveos/moveos-commons/accumulator/src/tree.rs
moveos/moveos-gas-profiling/src/flamegraph.rs
moveos/moveos-types/src/state.rs
moveos/moveos-verifier/src/error_code.rs
moveos/moveos-verifier/src/metadata.rs
moveos/smt/Cargo.toml
moveos/smt/src/jellyfish_merkle/node_type/mod.rs
moveos/smt/src/jellyfish_merkle/node_type/node_type_test.rs
moveos/smt/src/jellyfish_merkle/tree_cache/mod.rs
rust-toolchain.toml

[toolchain] Bump rust toolchain to 1.82.0

---

infra/rooch-portal-v2/.eslintrc.js
infra/rooch-portal-v2/package.json
infra/rooch-portal-v2/src/app/layout.tsx
infra/rooch-portal-v2/src/global.css
infra/rooch-portal-v2/src/layouts/config-nav-dashboard.tsx
infra/rooch-portal-v2/src/middleware.ts
infra/rooch-portal-v2/src/routes/hooks/useAddressChanged.tsx
infra/rooch-portal-v2/src/sections/account/overview.tsx
infra/rooch-portal-v2/src/sections/account/view.tsx
infra/rooch-portal-v2/src/sections/assets/overview.tsx
infra/rooch-portal-v2/src/sections/assets/view.tsx
infra/rooch-portal-v2/src/sections/faucet/overview.tsx
infra/rooch-portal-v2/src/sections/faucet/view.tsx
infra/rooch-portal-v2/src/sections/settings/view.tsx
infra/rooch-portal-v2/src/sections/transactions/overview.tsx
infra/rooch-portal-v2/src/sections/transactions/view.tsx
infra/rooch-portal-v2/src/sections/tx/view.tsx
infra/rooch-portal-v2/src/utils/env.ts
pnpm-lock.yaml

feat: twitter verify upgrade to rpc, wallet change hooks optimization

feat: twitter verify upgrade to rpc, wallet change hooks optimization

---

apps/grow_bitcoin/sources/grow_information.move
apps/grow_bitcoin/sources/grow_point.move
apps/orderbook/Move.toml
apps/orderbook/sources/market.move

[apps] grow bitcoin

---

apps/orderbook/sources/market.move

[app] market v2

---

apps/grow_bitcoin/sources/grow_bitcoin.move

Fix grow bitcoin

---

crates/rooch/src/commands/move_cli/commands/publish.rs
crates/testsuite/features/cmd.feature

Support publish rpd file directly.
- Closes #2826

feat: support publish rpd file directly

---

infra/rooch-portal-v2/src/sections/settings/view.tsx

feat: tweet optimization

---

infra/rooch-portal-v2/src/sections/settings/view.tsx

The tweet address must be split by the ADDRESS_SPLIT_CHARS

fix twitter bind bug

---

Cargo.lock
Cargo.toml
crates/rooch-config/src/da_config.rs
crates/rooch-da/Cargo.toml
crates/rooch-da/README.md
crates/rooch-da/src/backend/celestia/mod.rs
crates/rooch-da/src/backend/openda/avail.rs
crates/rooch-da/src/backend/openda/mod.rs
crates/rooch-da/src/backend/openda/operator.rs

Added Avail backend support for OpenDA(access by app light client). Implemented AvailClient for segment submission and refactored operator handling to accommodate the new backend.

feat(openda): implement Avail backend support

---

apps/orderbook/sources/market.move

fix: accept bid

---

kube/testnet/tbtc-faucet/tbtc-deployment.yaml

tbtc-faucet 0.0.3

---

apps/grow_bitcoin/sources/grow_information.move
apps/grow_bitcoin/sources/grow_point.move

[app] Migrating project id from u64 to String

---

Cargo.toml
crates/rooch-rpc-server/src/lib.rs
crates/rooch-rpc-server/src/service/blocklist.rs
scripts/deploy_rooch_mainnet.sh
scripts/deploy_rooch_testnet.sh

1. Use SmartIpKeyExtractor for GovernorConfigBuilder.
2. BlockList Layer only check the client ip from SmartIpKeyExtractor, do not check the PeerIP.
- Closes #2895

[rpc] Fix rate limit bug

---

crates/rooch-config/src/lib.rs
crates/rooch-rpc-server/src/lib.rs
crates/testsuite/tests/integration.rs
scripts/deploy_rooch_mainnet.sh
scripts/deploy_rooch_testnet.sh

rate limit traffic use  millisecond

[rpc] rate limit traffic use  millisecond

---

kube/mainnet/faucet/mainnet-faucet-deployment.yaml
kube/mainnet/oracle/mainnet-oracle-binance-deployment.yaml
kube/mainnet/oracle/mainnet-oracle-okx-deployment.yaml
kube/mainnet/oracle/mainnet-oracle-pyth-deployment.yaml
kube/mainnet/schedule/mainnet-gas-market-schedule.yaml
kube/testnet/faucet/testnet-faucet-deployment.yaml
kube/testnet/oracle/testnet-oracle-binance-deployment.yaml
kube/testnet/oracle/testnet-oracle-okx-deployment.yaml
kube/testnet/oracle/testnet-oracle-pyth-deployment.yaml
kube/testnet/schedule/testnet-gas-market-schedule.yaml

[k8s] Update rooch version in k8s config

---

crates/rooch-da/src/actor/server.rs
crates/rooch-proposer/src/actor/proposer.rs
crates/rooch-proposer/src/scc/mod.rs
crates/rooch-rpc-server/src/lib.rs
crates/rooch-store/src/da_store/mod.rs
crates/rooch-store/src/lib.rs

1.  Adjusted the condition check in the background submission job to use `done_count` instead of `max_block_number_submitted` to correctly identify when no blocks have been submitted.
2. feat(rooch-proposer): add set_last_proposed and try_get_block_state methods for enhanced block state management

fix(rooch-da): correct condition check in background submission job

---

crates/rooch-da/src/actor/messages.rs
crates/rooch-da/src/actor/server.rs
crates/rooch-da/src/proxy/mod.rs
crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/jsonrpc_types/status.rs
crates/rooch-rpc-server/src/service/rpc_service.rs
crates/rooch-types/src/da/mod.rs
crates/rooch-types/src/da/status.rs

1. rename DAServerStatus to DAInfoView and 
2. use StrView for DAInfoView

refactor(rooch-da): put da info into rooch status

---

crates/rooch-proposer/src/scc/mod.rs

for monitor propose process.
implement RPC later

feat(rooch-proposer): add block retrieval and root getters

---

infra/rooch-portal-v2/src/hooks/use-networks.ts
infra/rooch-portal-v2/src/sections/account/view.tsx
infra/rooch-portal-v2/src/sections/settings/view.tsx

fix twitter check & copy address

---

apps/invitation_record/sources/invitation.move

fix: remove lottery public

---

apps/invitation_record/sources/invitation.move

fix: remove simple rng use fun

---

docs/website/pages/blog/unveiling-rooch-pre-mainnet.en-US.mdx
docs/website/pages/blog/unveiling-rooch-pre-mainnet.zh-CN.mdx

fix univeiling blog date

---

apps/twitter_binding/sources/tweet_fetcher.move
apps/twitter_binding/sources/tweet_v2.move

[twitter_binding] Use batch API to fetch tweet

---

kube/promtail/promtail-config.yaml
kube/testnet/tbtc-faucet/tbtc-deployment.yaml

1. use proper parser for k8s log collect
2. tbtc bot up to 0.0.4

Log collect parser

---

infra/rooch-portal-v2/src/components/auth/session-key-guard-button-v1.tsx
infra/rooch-portal-v2/src/sections/settings/view.tsx

fix twitter

---

crates/rooch-faucet/src/faucet.rs
crates/rooch-faucet/src/invitation_module.rs

[gas-faucet] fix: call twitter function args

---

crates/rooch-indexer/src/indexer_reader.rs
crates/rooch-oracle/src/data_process.rs

[devops] Change log level

---

kube/mainnet/faucet/mainnet-faucet-deployment.yaml
kube/mainnet/oracle/mainnet-oracle-binance-deployment.yaml
kube/mainnet/oracle/mainnet-oracle-okx-deployment.yaml
kube/mainnet/oracle/mainnet-oracle-pyth-deployment.yaml
kube/mainnet/schedule/mainnet-gas-market-schedule.yaml
kube/mainnet/schedule/mainnet-tweet-fetch-schedule.yaml
kube/testnet/faucet/testnet-faucet-deployment.yaml
kube/testnet/oracle/testnet-oracle-binance-deployment.yaml
kube/testnet/oracle/testnet-oracle-okx-deployment.yaml
kube/testnet/oracle/testnet-oracle-pyth-deployment.yaml
kube/testnet/schedule/testnet-gas-market-schedule.yaml
kube/testnet/schedule/testnet-tweet-fetch-schedule.yaml

[kube] Upgrade to v0.8.4

---

infra/rooch-portal-v2/src/sections/assets/components/ordinal-list-card.tsx

opt bbn assets

---

infra/rooch-portal-v2/src/components/twitter/share.tsx
infra/rooch-portal-v2/src/hooks/use-networks.ts
infra/rooch-portal-v2/src/routes/hooks/useAddressChanged.tsx
infra/rooch-portal-v2/src/sections/invitations/components/invitation-list.tsx
infra/rooch-portal-v2/src/sections/invitations/view.tsx
infra/rooch-portal-v2/src/sections/settings/view.tsx
infra/rooch-portal-v2/src/utils/inviter.ts

fix swap gas & add invite btn

---

infra/rooch-portal-v2/src/sections/assets/components/asset-row-item.tsx

add intl format

---

infra/rooch-portal-v2/src/sections/assets/components/asset-row-item.tsx

fix BITXP decimals

---

crates/rooch/src/commands/da/commands/exec.rs

Updated variable name from verified_tx_order to executed_tx_order for clarity and consistency with functionality.
Increased MPSC channel buffer size to improve performance during high transaction loads.

refactor(rooch-da): rename verified_tx_order to executed_tx_order

---

apps/invitation_record/sources/invitation.move

add deposit rgas coin from module address

---

frameworks/rooch-framework/doc/simple_rng.md
frameworks/rooch-framework/sources/simple_rng.move
scripts/bitcoin/test.sh

Fix Calling simple_rng::seed() multiple times in the same transaction returns the same value
https://github.com/rooch-network/rooch/issues/2837

feat: add rand_u64_with_count and rand_u128_with_count

---

frameworks/rooch-framework/doc/address_mapping.md
frameworks/rooch-framework/doc/bitcoin_address.md
frameworks/rooch-framework/sources/address_mapping.move
frameworks/rooch-framework/sources/address_type/bitcoin_address.move
frameworks/rooch-framework/sources/genesis.move
frameworks/rooch-framework/sources/transaction_validator.move
frameworks/rooch-framework/sources/transfer.move

1. Support batch resolve bitcoin address in address_mapping.
2. Public `bind_bitcoin_address` in address_maping.
close #3086

[framework] support batch resolve bitcoin address in address_mapping

---

kube/mainnet/roochbot/mainnet-roochbot-deployment.yaml
kube/mainnet/roochbot/mainnet-roochbot-pvc.yaml

[kube] Update roochbot

---

Cargo.toml

Removed multiple unused dependencies from Cargo.toml to simplify project maintenance and reduce potential overhead. This cleanup enhances clarity and ensures only necessary packages are included.

chore(dependencies): remove unused dependencies

---

kube/mainnet/roochbot/mainnet-roochbot-deployment.yaml

upgrade roochbot

---

crates/rooch/src/commands/da/commands/namespace.rs

Add option to specify a custom genesis file in the NamespaceCommand. This allows users to load genesis data from a file instead of relying on the default generation process.

feat(rooch-da): support custom genesis file in namespace

---

infra/rooch-portal-v2/src/sections/faucet/view.tsx

fix faucet bug

---

infra/rooch-portal-v2/src/hooks/use-networks.ts
infra/rooch-portal-v2/src/layouts/config-nav-dashboard.tsx

market main

---

infra/rooch-portal-v2/src/layouts/config-nav-dashboard.tsx
infra/rooch-portal-v2/src/sections/trade/view.tsx

fix total supply

---

docs/website/pages/_meta.en-US.json
docs/website/pages/_meta.zh-CN.json

rooch network add apps

---

infra/rooch-portal-v2/src/app/apps/page.tsx
infra/rooch-portal-v2/src/layouts/config-nav-dashboard.tsx
infra/rooch-portal-v2/src/sections/apps/view.tsx
infra/rooch-portal-v2/src/utils/avatar.ts

portal apps add grow project

---

moveos/smt/src/lib.rs

[smt] remove redundant clone

---

infra/rooch-portal-v2/src/sections/faucet/inviter.tsx
infra/rooch-portal-v2/src/sections/faucet/view.tsx
pnpm-lock.yaml
sdk/typescript/rooch-sdk-kit/src/components/fauct-modal/views/FaucetView.tsx

fix faucet

---

crates/rooch-types/src/transaction/rooch.rs
crates/testsuite/tests/integration.rs

[integration] rm redundant clone

[integration] rm redundant clone

---

frameworks/rooch-framework/doc/bitcoin_address.md
frameworks/rooch-framework/doc/coin.md
frameworks/rooch-framework/sources/coin.move
frameworks/rooch-framework/sources/tests/coin_test.move
frameworks/rooch-framework/sources/transaction_fee.move

[framework] Copy the CoinInfo and keep global CoinMetadata

---

docs/website/pages/_meta.en-US.json
docs/website/pages/_meta.zh-CN.json

rooch navigation

---

crates/rooch-da/src/backend/openda/avail.rs

Introduces `turbo_payment_token` to AvailFusionClientConfig and AvailTurboClient. Allows customization of payment tokens with a fallback to a default value. Updates request header content type to "text/plain".

feat(rooch-da): add turbo payment token support

---

Cargo.lock
crates/rooch-common/Cargo.toml
crates/rooch-common/src/utils/humanize.rs
crates/rooch/src/commands/da/commands/exec.rs
crates/rooch/src/commands/da/commands/mod.rs
crates/rooch/src/commands/db/commands/dump_tx_root.rs
crates/rooch/src/commands/db/commands/get_execution_info_by_order.rs

Refactored TxDAIndexer to include RoochStore for advanced transaction sequencing. Improved the rollback process with enhanced handling of startup and sequencer information. Updated execution modes for better clarity and refined RocksDB cache size parsing.

feat(rooch-da): enhance execution and rollback logic in DA

---

crates/rooch/src/commands/da/commands/exec.rs

Introduce the `force-align` flag to align execution order during discrepancies. Adds proper handling and warning messaging for mismatched processes of sequencing and executing when we want to run with `--mode all`

feat(rooch-da): add force-align option to exec command

---

examples/foc_eliza/README.md
examples/foc_eliza/sources/charactor.move
examples/foc_eliza/sources/types.move

[foc_eliza] Deploy foc eliza to testnet

---

apps/rooch_dex/sources/route.move
apps/rooch_dex/sources/swap.move

fix: assert add liquidity when create token pair

---

apps/rooch_dex/sources/liquidity_incentive.move
apps/rooch_dex/sources/router.move
apps/rooch_dex/sources/swap.move
apps/rooch_dex/sources/swap_utils.move

Fix liquidity incentive

---

apps/orderbook/sources/market.move

fix: order event owner

---

crates/rooch-open-rpc-spec/schemas/openrpc.json
infra/rooch-portal-v2/src/app/history/[tick]/page.tsx
infra/rooch-portal-v2/src/components/iconify copy/iconify.tsx
infra/rooch-portal-v2/src/components/iconify copy/index.ts
infra/rooch-portal-v2/src/components/iconify copy/types.ts
infra/rooch-portal-v2/src/components/market/inscription-shop-card.tsx
infra/rooch-portal-v2/src/routes/paths.ts
infra/rooch-portal-v2/src/sections/history/components/empty-content.tsx
infra/rooch-portal-v2/src/sections/history/components/order-table-row.tsx
infra/rooch-portal-v2/src/sections/history/components/order.ts
infra/rooch-portal-v2/src/sections/history/components/table-empty-rows.tsx
infra/rooch-portal-v2/src/sections/history/components/table-no-data.tsx
infra/rooch-portal-v2/src/sections/history/components/table-pagination-custom.tsx
infra/rooch-portal-v2/src/sections/history/components/types.ts
infra/rooch-portal-v2/src/sections/history/components/use-table.ts
infra/rooch-portal-v2/src/sections/history/utils/common.ts
infra/rooch-portal-v2/src/sections/history/utils/types.ts
infra/rooch-portal-v2/src/sections/history/view.tsx
infra/rooch-portal-v2/src/sections/trade/market/view.tsx
infra/rooch-portal-v2/src/utils/env.ts

feat: marketplace order book history

feat: marketplace order book history

---

infra/rooch-portal-v2/src/utils/env.ts

fix testnet

---

infra/rooch-portal-v2/src/sections/trade/components/select-token-pair.tsx

fix swap bug

---

.github/workflows/deploy_testnet.yml
crates/rooch-config/src/da_config.rs
crates/rooch-da/src/backend/README.md
crates/rooch-da/src/backend/openda/avail.rs
scripts/deploy_rooch_testnet.sh

changes configs and API according to upgrade

refactor(rooch-da): upgrade turboDA from v0.1 to v1

---

examples/onchain_ai_chat/sources/ai_service.move
examples/onchain_ai_chat/web/.npmrc
examples/onchain_ai_chat/web/package-lock.json
examples/onchain_ai_chat/web/package.json
examples/onchain_ai_chat/web/src/pages/Room.tsx

[example] Fix onchain ai chat web deployment error

---

examples/onchain_ai_chat/README.md
examples/onchain_ai_chat/sources/ai_request.move
examples/onchain_ai_chat/sources/ai_service.move
examples/onchain_ai_chat/web/src/components/Layout.tsx
examples/onchain_ai_chat/web/src/components/OracleBalance.tsx
examples/onchain_ai_chat/web/src/constants.ts
examples/onchain_ai_chat/web/src/main.tsx
examples/onchain_ai_chat/web/src/networks.ts
examples/onchain_ai_chat/web/src/pages/Room.tsx

Display Oracle balance and improve the gas usage to call OpenAI

[onchain-ai-chat] Display oracle balance and improve the gas usage to call OpenAI

---

examples/onchain_ai_chat/sources/ai_callback.move
examples/onchain_ai_chat/sources/ai_request.move
examples/onchain_ai_chat/sources/ai_service.move
examples/onchain_ai_chat/sources/room.move
examples/onchain_ai_chat/web/package-lock.json
examples/onchain_ai_chat/web/package.json
examples/onchain_ai_chat/web/src/components/ChatInput.tsx
examples/onchain_ai_chat/web/src/components/ChatMessage.tsx
examples/onchain_ai_chat/web/src/components/ErrorToast.tsx
examples/onchain_ai_chat/web/src/containers/RoomListContainer.tsx
examples/onchain_ai_chat/web/src/main.tsx
examples/onchain_ai_chat/web/src/pages/Home.tsx
examples/onchain_ai_chat/web/src/pages/Room.tsx
examples/onchain_ai_chat/web/src/utils/errors.ts

[onchain-ai-chat] Create room with message

[onchain-ai-chat] Create room with message and auto update title

---

examples/onchain_ai_chat/sources/ai_request.move
examples/onchain_ai_chat/sources/ai_service.move
examples/onchain_ai_chat/web/src/components/TypingIndicator.tsx
examples/onchain_ai_chat/web/src/pages/Room.tsx

Ai chat optimize
1. Support summary of the history.
2. Add AI thinking.

[example] Ai chat optimize

---

examples/onchain_ai_chat/README.md
examples/onchain_ai_chat/web/src/components/Layout.tsx

[ai_chat] Add links

---

infra/rooch-portal-v2/src/sections/trade/swap-v2/view.tsx

fix: swap invalid params

---

infra/rooch-portal-v2/src/layouts/config-nav-dashboard.tsx
infra/rooch-portal-v2/src/sections/trade/components/select-token-pair.tsx
infra/rooch-portal-v2/src/sections/trade/components/token-pair.tsx
infra/rooch-portal-v2/src/sections/trade/components/types.ts
infra/rooch-portal-v2/src/sections/trade/hooks/use-all-liquidity.ts
infra/rooch-portal-v2/src/sections/trade/hooks/use-owner-liquidity.ts
infra/rooch-portal-v2/src/sections/trade/hooks/use-token-pair.ts
infra/rooch-portal-v2/src/sections/trade/liquidity/list/all_liquidity_list.tsx
infra/rooch-portal-v2/src/sections/trade/liquidity/list/farm-row-item.tsx
infra/rooch-portal-v2/src/sections/trade/liquidity/list/farm_list.tsx
infra/rooch-portal-v2/src/sections/trade/liquidity/list/owner-liquidity-row-item.tsx
infra/rooch-portal-v2/src/sections/trade/liquidity/list/owner_liquidity_list.tsx
infra/rooch-portal-v2/src/sections/trade/swap-v2/confirm-modal.tsx
infra/rooch-portal-v2/src/sections/trade/swap-v2/view.tsx
infra/rooch-portal-v2/src/sections/trade/swap/confirm-modal.tsx
infra/rooch-portal-v2/src/sections/trade/swap/view.tsx
infra/rooch-portal-v2/src/utils/number.ts

fix bug & opt dex

---

crates/rooch-types/src/da/batch.rs
crates/rooch/src/commands/da/README.md
crates/rooch/src/commands/da/commands/mod.rs
crates/rooch/src/commands/da/commands/unpack.rs

Add support for chunk-specific unpacking and force unpacking with new CLI flags. Refactored logic to verify transaction order only when required and improved error messages for better debugging.

feat(rooch-da): add granular control options for unpacking

---

crates/rooch-open-rpc-spec/schemas/openrpc.json
crates/rooch-rpc-api/src/jsonrpc_types/rooch_types.rs
crates/rooch-rpc-api/src/jsonrpc_types/transaction_view.rs
moveos/moveos-store/src/event_store/mod.rs

1. Add chain_id and max_gas_amount to TransactionView #3227
2. Fixup get events reverse order has_next page error  #3269
- Closes #3227 #3269

[RPC ] Add chain_id and max_gas_amount to TransactionView

---

crates/rooch-pipeline-processor/src/actor/processor.rs

[processor] Revert tx when execute_tx error

[processor] Revert tx when execute_tx error

---

infra/rooch-portal-v2/src/components/gas-swap/curve-type-select.tsx
infra/rooch-portal-v2/src/components/gas-swap/pool-version-select.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-coin-input.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-coin-select-button.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-container.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-details.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-header.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-hint-text.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-info-card.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-switch-icon.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-transaction-header.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap-transaction-info-card.tsx
infra/rooch-portal-v2/src/components/gas-swap/swap.tsx
infra/rooch-portal-v2/src/components/gas-swap/types.ts
infra/rooch-portal-v2/src/components/gas-swap/typography/header.tsx
infra/rooch-portal-v2/src/components/gas-swap/typography/label.tsx
infra/rooch-portal-v2/src/components/gas-swap/typography/text.tsx
infra/rooch-portal-v2/src/components/swap/swap-info-card.tsx
infra/rooch-portal-v2/src/layouts/config-nav-dashboard.tsx
infra/rooch-portal-v2/src/sections/gas-swap/index.tsx
infra/rooch-portal-v2/src/sections/trade/hooks/use-token-pair.ts
infra/rooch-portal-v2/src/sections/trade/swap-v2/confirm-modal.tsx
infra/rooch-portal-v2/src/sections/trade/swap-v2/view.tsx
infra/rooch-portal-v2/src/utils/number.ts

fix: fix swap invalid params

---

infra/rooch-portal-v2/src/sections/trade/liquidity/list/add-liquidity-modal.tsx
infra/rooch-portal-v2/src/utils/env.ts

fix add liquidity ycoin decimals

---

examples/onchain_ai_chat/sources/ai_service.move
examples/onchain_ai_chat/sources/message.move
examples/onchain_ai_chat/sources/room.move
examples/onchain_ai_chat/sources/room_tests.move
examples/onchain_ai_chat/web/README.md
examples/onchain_ai_chat/web/src/constants.ts
examples/onchain_ai_chat/web/src/main.tsx

[chat] Use Object to store Message

---

docs/website/theme.config.tsx

update static path

---

pnpm-lock.yaml
sdk/typescript/bitseed-sdk/src/datasource/rooch/rooch_datasource.test.ts
sdk/typescript/rooch-sdk/README.md
sdk/typescript/rooch-sdk/package.json
sdk/typescript/rooch-sdk/src/client/client.ts
sdk/typescript/rooch-sdk/src/client/httpTransport.ts
sdk/typescript/rooch-sdk/src/client/index.ts
sdk/typescript/rooch-sdk/src/client/transportInterface.ts
sdk/typescript/rooch-sdk/src/client/wsTransport.ts
sdk/typescript/rooch-sdk/test-e2e/case/ws-transport.test.ts
sdk/typescript/rooch-sdk/test-e2e/setup.ts

Impl websocket transport
https://github.com/rooch-network/rooch/issues/3312

feat: add wsTransport impl

---

infra/rooch-portal-v2/src/app/faucet/inviter/[address]/page.tsx
infra/rooch-portal-v2/src/app/invitation/[address]/page.tsx
infra/rooch-portal-v2/src/app/invitation/page.tsx
infra/rooch-portal-v2/src/app/trade/market/page.tsx
infra/rooch-portal-v2/src/components/guard/WalletGuard.tsx
infra/rooch-portal-v2/src/components/market/marketplace-item-card.tsx
infra/rooch-portal-v2/src/hooks/account/use-account-btc-balance.ts
infra/rooch-portal-v2/src/hooks/account/use-account-rgas-balance.ts
infra/rooch-portal-v2/src/hooks/account/use-account-twitter-id.ts
infra/rooch-portal-v2/src/hooks/gas/use-gas-market-rate.ts
infra/rooch-portal-v2/src/hooks/liquidity/use-token-pair-infos.ts
infra/rooch-portal-v2/src/sections/account/view.tsx
infra/rooch-portal-v2/src/sections/assets/components/utxo-list-card.tsx
infra/rooch-portal-v2/src/sections/faucet/inviter.tsx
infra/rooch-portal-v2/src/sections/faucet/view.tsx
infra/rooch-portal-v2/src/sections/gas-swap/index.tsx
infra/rooch-portal-v2/src/sections/invitations/view.tsx
infra/rooch-portal-v2/src/sections/settings/components/session-keys-table-card.tsx
infra/rooch-portal-v2/src/sections/settings/view.tsx
infra/rooch-portal-v2/src/sections/trade/hooks/use-all-liquidity.ts
infra/rooch-portal-v2/src/sections/trade/liquidity/list/all_liquidity_list.tsx
infra/rooch-portal-v2/src/sections/trade/market/home-view.tsx
infra/rooch-portal-v2/src/sections/transactions/view.tsx
infra/rooch-portal-v2/src/utils/env.ts
pnpm-lock.yaml

feat: encapsulate hooks

---

infra/rooch-portal-v2/src/sections/trade/liquidity/components/farm-list.tsx
infra/rooch-portal-v2/src/sections/trade/liquidity/components/farm-row-item.tsx

show end farms

---

frameworks/moveos-stdlib/doc/address.md
frameworks/moveos-stdlib/doc/bech32.md
frameworks/moveos-stdlib/sources/address.move
frameworks/moveos-stdlib/sources/bech32.move
moveos/moveos-types/src/addresses.rs

[moveos_std] Provide address to_bech32_string and from_bech32_string

---

docker/Dockerfile
docker/DockerfileDebug

[devops] upgrade libssl to fixup docker build error

---

frameworks/rooch-framework/doc/coin.md
frameworks/rooch-framework/sources/account_coin_store.move
frameworks/rooch-framework/sources/coin.move
frameworks/rooch-framework/sources/transfer.move

[Framework] Support get coin info by coin type name

---

infra/rooch-portal-v2/src/layouts/config-nav-dashboard.tsx

add tunnel external entry

---

infra/rooch-portal-v2/src/sections/trade/liquidity/components/add-liquidity-modal.tsx

fix liquidity bug

---

crates/rooch-executor/src/actor/executor.rs
moveos/moveos-types/src/moveos_std/tx_context.rs

part of #2763, L1 tx validate first launches the contract, then opens the Rust code

Open the l1 tx validate rust code

---

crates/rooch-config/src/da_config.rs
scripts/deploy_rooch_testnet.sh

set da-min-block-to-submit to 9033 for testnet

ci(deploy): add `da-min-block-to-submit` param in testnet deloy config

---

sdk/typescript/rooch-sdk/src/address/rooch.test.ts
sdk/typescript/rooch-sdk/src/address/rooch.ts
sdk/typescript/rooch-sdk/src/address/util.ts
sdk/typescript/rooch-sdk/src/bcs/serializer.test.ts
sdk/typescript/rooch-sdk/src/bcs/serializer.ts
sdk/typescript/rooch-sdk/src/utils/bytes.ts

sdk support account name object id

---

frameworks/moveos-stdlib/doc/account.md
frameworks/moveos-stdlib/doc/decimal_value.md
frameworks/moveos-stdlib/doc/string_utils.md
frameworks/moveos-stdlib/sources/account.move
frameworks/moveos-stdlib/sources/decimal_value.move
frameworks/moveos-stdlib/sources/object.move
frameworks/moveos-stdlib/sources/string_utils.move

* [account] Add get functions for Account and AccountCap
* [decimal_value] Add with_precision, math functions, from_string/to_string for decimal_value
* [string_utils] Add more parse functions, to_string functions, start_with, contains, trim, strip_prefix to string_utils

[moveos_std] Improve decimal_value and string utils

---

.github/actions/rust-setup/action.yaml
.github/workflows/check_build_test.yml
.github/workflows/cleanup.yml
scripts/pr.sh

Improved CI workflow by introducing file change filters using `dorny/paths-filter` to optimize execution of steps based on affected files. Added conditional steps for Rust, Web, SDK, and Docker validations to streamline the build and test process.

feat(ci): add file change filters and conditional steps

---

docs/website/next.config.js

fix clickjacking

---

Cargo.lock
crates/rooch/Cargo.toml
crates/rooch/src/commands/move_cli/commands/publish.rs
crates/rooch/src/tx_runner.rs
crates/testsuite/features/cmd.feature
crates/testsuite/features/friend_module_renaming.feature
crates/testsuite/tests/integration.rs
frameworks/framework-builder/src/releaser.rs
moveos/moveos-types/src/moveos_std/module_store.rs

Check the modules compatibility when publish

[cli] Check the modules compatibility when publish

---

frameworks/moveos-stdlib/doc/string_utils.md
frameworks/moveos-stdlib/sources/string_utils.move

make starts_with and contains functions to public in string_utils

[moveos_std] make starts_with and contains functions to public in string_utils

---

frameworks/moveos-stdlib/doc/features.md
frameworks/moveos-stdlib/sources/features.move
frameworks/moveos-stdlib/src/natives/moveos_stdlib/move_module.rs
frameworks/rooch-framework/sources/onchain_config.move
moveos/moveos-types/src/moveos_std/onchain_features.rs

Add a FeatureFlag to control the Compatibility Checker V2

---

.github/workflows/check_build_test.yml
Cargo.lock
Cargo.toml
crates/rooch-framework-tests/src/tests/bbn_test.rs
crates/rooch-types/src/bitcoin/bbn.rs
crates/rooch-types/src/crypto.rs
frameworks/framework-builder/src/releaser.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/evm.rs
frameworks/moveos-stdlib/src/natives/moveos_stdlib/groth16.rs
pnpm-workspace.yaml
scripts/pr.sh

https://github.com/MystenLabs/fastcrypto/pull/847
- Closes #3279

Upgrade fastcrypto to fix building on MacOS 15.11 issue

---

crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs
examples/complex_struct/README.md

For compatibility reasons, add a feature flag to break changes about specific struct in PR #3478 
reopen #3445

Add feature flag for specific  struct option

---

crates/rooch-genesis/src/lib.rs

Update gas config v2

---

crates/rooch-db/src/lib.rs
crates/rooch-store/src/lib.rs

Added more informative logging for sequenced transaction repair. Introduced a new `check_changeset_store` method in `RoochDB` to validate the presence of state change sets and issue warnings for missing ones.

feat(rooch-store): enhance repair and validation with detailed logging and checks

---

docs/website/pages/build/reference/rpc/json-rpc.en-US.mdx
docs/website/pages/build/reference/rpc/json-rpc.zh-CN.mdx

fix rooch_queryObjectStates docs

---

docs/website/pages/blog/nuwa-web3.en-US.mdx
docs/website/pages/blog/nuwa-web3.zh-CN.mdx

[blob] modify nuwa blob header

---

crates/rooch/src/commands/upgrade/commands/upgrade_gas_config.rs
frameworks/rooch-framework/src/natives/gas_parameter/events.rs

disable gas schedule version check

---

examples/nostr/README.md

Update README.md to reflect this PR: https://github.com/aljazceru/awesome-nostr/pull/557.
- Closes #3376.

[gh-3376] docs: update nostr readme to reflect changes made on nostr.net.

---

examples/nostr/sources/event.move
examples/nostr/sources/inner.move

Fix user metadata handling, add move events, and clean code.
- Closes #3376.

[gh-3376] examples/nostr: fix user metadata handling, add move events, and clean code.

---

examples/nostr/README.md

Add prerequisites and install sections to README.md for newcomers.
- Closes #3376.

[gh-3376] examples/nostr: add prerequisites and install sections to readme for newcomers.

---

README.md

chore: added badge release and link to it

---

crates/rooch-rpc-client/src/lib.rs
crates/rooch-sequencer/tests/test_sequencer.rs
crates/testsuite/features/cmd.feature

Hey team! Fixed error:
crates/rooch-rpc-client/src/lib.rs
`verison` - `version`
crates/rooch-sequencer/tests/test_sequencer.rs
`aviod` - `avoid`
crates/testsuite/features/cmd.feature
`contians` - `contains`

minor docstring fixups

---

README.md

chore: add badge and link to Twitter social network

---

scripts/dev_setup.sh
scripts/pr.sh

fix cargo-nextest version

---

crates/rooch-genesis/src/lib.rs
frameworks/rooch-framework/src/natives/rooch_framework/crypto/ecdsa_r1.rs

fix ecdsa_r1 debug_assert and init genesis gas v6

---

frameworks/rooch-framework/doc/README.md
frameworks/rooch-framework/doc/rs256.md
frameworks/rooch-framework/sources/crypto/rs256.move
frameworks/rooch-framework/sources/tests/rs256_test.move
frameworks/rooch-framework/src/natives/gas_parameter/mod.rs
frameworks/rooch-framework/src/natives/gas_parameter/rs256.rs
frameworks/rooch-framework/src/natives/mod.rs
frameworks/rooch-framework/src/natives/rooch_framework/crypto/mod.rs
frameworks/rooch-framework/src/natives/rooch_framework/crypto/rs256.rs

Add RS256 to support RSA cryptography to be used in JWT, WebAuthn, etc.
- Closes #1160

[gh-1160] frameworks/rooch-framework: introduce rs256.

---

crates/rooch-genesis/src/lib.rs

[gh-3630] crates/rooch-genesis: add rs256 to v6 framework gas parameters.

---

Cargo.lock
Cargo.toml
crates/rooch/Cargo.toml
crates/rooch/src/commands/account/commands/mod.rs
crates/rooch/src/commands/account/commands/tx.rs
crates/rooch/src/commands/account/mod.rs
crates/testsuite/features/cmd.feature

Add `rooch account tx` command.
- Closes #3633.

[gh-3633] commands/account: account tx.

---

.cursorrules
.github/copilot-instructions.md
.github/workflows/linux_macos_release.yml
.github/workflows/windows_release.yml
.gitignore
Makefile
docs/dev-guide/rooch_move_guide.md

Optimize ai config and guide

---

Makefile
frameworks/moveos-stdlib/doc/address.md
frameworks/moveos-stdlib/doc/string_utils.md
frameworks/moveos-stdlib/sources/address.move
frameworks/moveos-stdlib/sources/string_utils.move
frameworks/rooch-framework/doc/did.md
frameworks/rooch-framework/doc/session_key.md
frameworks/rooch-framework/sources/did.move
frameworks/rooch-framework/sources/session_key.move
frameworks/rooch-framework/sources/tests/did_custom_scopes_test.move
frameworks/rooch-framework/sources/tests/did_test_common.move

Did session scope

---

crates/rooch-config/src/lib.rs
scripts/deploy_rooch_testnet.sh

Deploy script support hash tag

---

Cargo.toml
crates/rooch-config/src/prune_config.rs
crates/rooch-pruner/Cargo.toml
crates/rooch-pruner/src/lib.rs
crates/rooch-pruner/src/pruner.rs
crates/rooch-pruner/src/reachability.rs
crates/rooch-pruner/src/sweep_expired.rs
crates/rooch-pruner/src/util.rs
moveos/moveos-store/Cargo.toml
moveos/moveos-store/src/lib.rs
moveos/moveos-store/src/prune/mod.rs
moveos/moveos-types/src/prune.rs

[Pruner] support traverse both globle and table state

---

scripts/deploy_rooch_testnet.sh

disable testnet bitcoin sync

---

Cargo.lock
crates/rooch-pruner/src/pruner.rs
crates/rooch-pruner/src/sweep_expired.rs
crates/rooch-pruner/src/tests/test_pruner.rs
crates/rooch-pruner/src/util.rs
crates/rooch-rpc-server/src/lib.rs
moveos/moveos-store/Cargo.toml
moveos/moveos-store/src/state_store/mod.rs
moveos/raw-store/src/rocks/mod.rs
scripts/deploy_rooch_testnet.sh

[Pruner] Enable pruner

---

crates/rooch-pruner/src/pruner.rs
crates/rooch-pruner/src/sweep_expired.rs
moveos/moveos-store/src/state_store/mod.rs

[Pruner] Pruner opt compact

---

.github/workflows/windows_release.yml

fix release windows.
- Closes #3729.

[gh-3729] ci/workflows: fix windows release.
